/* Purpose: check a gap query and its index through the embedded source interface.
 * Source: examples/ch18-performance/18-01-larger-workloads/06-a-gap-query-and-its-index.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (nodes $n) (if (== $n 0) done (let $t (add-atom &self (node $n tag)) (nodes (- $n 1)))))\n",
        "!(add-atom &self (edge a b))\n",
        "!(add-atom &self (edge a c))\n",
        "!(add-atom &self (edge a d e))\n",
        "!(test (nodes 200) done)\n",
        "!(test (inferences 1000 (length (collapse (match &self (edge a $y) $y)))) 2)\n",
        "!(test (inferences 1000 (length (collapse (match &self (edge ... $y) $y)))) 3)\n",
        "!(test (nodes 2000) done)\n",
        "!(test (inferences 1000 (length (collapse (match &self (edge a $y) $y)))) 2)\n",
        "!(test (inferences 1000 (length (collapse (match &self (edge ... $y) $y)))) 3)\n",
        "!(test (length (collapse (match &self (node ... $y) $y))) 2200)\n",
        "!(test (sort-atom (collapse (match &self (edge a $y) $y))) (b c))\n",
        "!(test (sort-atom (collapse (match &self (edge a (:seg $rest)) $rest))) ((b) (c) (d e)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "a_gap_query_and_its_index");
}
