/* Purpose: check add atom fun space through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/07-add_atom_fun_space.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (space) my_space_name)\n",
        "!(add-atom (space) (my test atom))\n",
        "!(test (match (space) $a $a) (my test atom))\n",
        "!(test (is-space my_space_name) false)\n",
        "!(test (is-space &self) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "add_atom_fun_space");
}
