/* Purpose: check alpha member through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/08-alpha_member.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (is-alpha-member x ()) false)\n",
        "!(test (is-alpha-member $x (a b c)) false)\n",
        "!(test (is-alpha-member a (a b c)) true)\n",
        "!(test (is-alpha-member d (a b c)) false)\n",
        "!(test (is-alpha-member (f $x) ((f $y) (g $z))) true)\n",
        "!(test (is-alpha-member (f $x) ((f $y) (f $y))) true)\n",
        "!(test (is-alpha-member (f (g $x) $y) ((f (g $a) $b) (h $c $d))) true)\n",
        "!(test (is-alpha-member (f (g $x) $x) ((f (g $a) $b) (f (g $c) $c))) true)\n",
        "!(test (is-alpha-member (f $x) ((f $x $y) (g $z))) false)\n",
        "!(test (is-alpha-member 42 (1 2 42 3)) true)\n",
        "!(test (is-alpha-member 99 (1 2 42 3)) false)\n",
        "!(test (is-alpha-member (1 $x) ((1 2) (3 4))) true)\n",
        "!(test (is-alpha-member (1 $x) ((2 3) (4 5))) false)\n",
        "!(test (is-alpha-member a (a b a c)) true)\n",
        "!(test (is-alpha-member (f $x $y) ((f $a $b) (f $c $d))) true)\n",
        "!(test (is-alpha-member a (a)) true)\n",
        "!(test (is-alpha-member b (a)) false)\n",
        "!(test (is-alpha-member $x ($y $z $w)) true)\n",
        "!(test (is-alpha-member (a (b (c $x))) ((a (b (c $d))) (e $f))) true)\n",
        "!(test (is-alpha-member (f $x) ((g $y) (h $z))) false)\n",
        "!(test (is-alpha-member () (() a b)) true)\n",
        "!(test (is-alpha-member () (a b c)) false)\n",
        "!(let* (($pat (hi name boss)) ($dummy1 (println! (pattern:- $pat))) ($bool (is-alpha-member $new $pat)) ($dummy2 (println! (is member:- $bool in pattern:- $pat)))) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "alpha_member");
}
