/* Purpose: check alpha unique atom through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/09-alpha_unique_atom.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (let $unique (alpha-unique-atom ((link $x human) (link $y human) (link $z human))) (=alpha $unique ((link $a human)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((parent $x human) (parent $y human) (child $z human))) (=alpha $unique ((parent $a human) (child $b human)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((parent $x human) (child $y human) (friend $z human))) (=alpha $unique ((parent $a human) (child $b human) (friend $c human)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((likes $x) (hates $y) (knows $z))) (=alpha $unique ((likes $a) (hates $b) (knows $c)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((link (foo $x) human) (link (foo $y) human) (link (bar $z) human))) (=alpha $unique ((link (foo $a) human) (link (bar $b) human)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((parent (child $x) human) (parent (child $y) human) (parent (child $x) human))) (=alpha $unique ((parent (child $a) human)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((link $x human) (parent $x human) (link $y human) (parent $z human) (link $x human))) (=alpha $unique ((link $a human) (parent $a human)))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((foo $x) (foo $y) (bar $x) (foo $x) (bar $y))) (=alpha $unique ((foo $a) (bar $a)))) true)\n",
        "!(test (let $unique (alpha-unique-atom (1 2 2 3 1 4 4 5)) (=alpha $unique (1 2 3 4 5))) true)\n",
        "!(test (let $unique (alpha-unique-atom (a b a c b d e a)) (=alpha $unique (a b c d e))) true)\n",
        "!(test (let $unique (alpha-unique-atom ()) (=alpha $unique ())) true)\n",
        "!(test (let $unique (alpha-unique-atom (1)) (=alpha $unique (1))) true)\n",
        "!(test (let $unique (alpha-unique-atom ((link $x human))) (=alpha $unique ((link $a human)))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "alpha_unique_atom");
}
