/* Purpose: check and then or else through the embedded source interface.
 * Source: examples/ch07-control-flow/07-01-if-and-booleans/10-and_then_or_else.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (and-then true yes) yes)\n",
        "!(test (and-then false yes) false)\n",
        "!(test (or-else true no) true)\n",
        "!(test (or-else false fallback) fallback)\n",
        "!(test (and-then (> 2 1) (> 3 2)) true)\n",
        "!(test (or-else (> 1 2) (> 3 2)) true)\n",
        "!(bind! &ran (new-space))\n",
        "(= (note $tag) (let $_1 (add-atom &ran (ran $tag)) true))\n",
        "!(and-then false (note skipped-by-and-then))\n",
        "!(or-else true (note skipped-by-or-else))\n",
        "!(and-then true (note taken-by-and-then))\n",
        "!(or-else false (note taken-by-or-else))\n",
        "!(test (collapse (get-atoms &ran)) ((ran taken-by-and-then) (ran taken-by-or-else)))\n",
        "!(bind! &ran2 (new-space))\n",
        "(= (note2 $tag) (let $_1 (add-atom &ran2 (ran $tag)) true))\n",
        "!(and false (note2 and-runs-it))\n",
        "!(and-then false (note2 and-then-skips-it))\n",
        "!(test (collapse (get-atoms &ran2)) ((ran and-runs-it)))\n",
        "!(test (collapse (if (and-then (or-else $p true) $q) ($p $q))) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "and_then_or_else");
}
