/* Purpose: check and or through the embedded source interface.
 * Source: examples/ch07-control-flow/07-01-if-and-booleans/07-and_or.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (if (or (and true false) true) 1 2) 1)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "and_or");
}
