/* Purpose: check assertion difference through the embedded source interface.
 * Source: examples/ch12-testing/03-assertion_difference.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (let $reported (catch (assertEqual (+ 1 1) 3)) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqual (+ 1 1) 3) (3) (2))\")\n",
        "!(test (let $reported (catch (assertEqualToResult (superpose (1 2)) (1 2 3))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqualToResult (superpose (1 2)) (1 2 3)) (3) ())\")\n",
        "!(test (let $reported (catch (assertEqual (superpose (a a b)) (superpose (a b b)))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqual (superpose (a a b)) (superpose (a b b))) (b) (a))\")\n",
        "!(test (let $reported (catch (assertIncludes (superpose (1 2)) (7))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertIncludes (superpose (1 2)) (7)) (7) $_0)\")\n",
        "!(test (let $reported (catch (assertEqual (superpose (1 2)) (superpose (2 1)))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqual (superpose (1 2)) (superpose (2 1))) () ())\")\n",
        "!(test (let $reported (catch (assertEqualMsg (+ 1 2) 4 \"sums differ\")) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqualMsg (+ 1 2) 4 \\\"sums differ\\\") (4) (3))\")\n",
        "!(test (let $reported (catch (assert (== 1 2))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed false $_0 $_1)\")\n",
        "!(test (assertEqual (+ 1 2) (- 6 3)) true)\n",
        "!(test (assertEqualToResult (superpose (1 2)) (2 1)) true)\n",
        "!(test (assertEqualMsg (+ 1 2) (- 6 3) \"sums differ\") true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "assertion_difference");
}
