/* Purpose: check assert answers through the embedded source interface.
 * Source: examples/ch12-testing/04-assert_answers.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (assert-answers true (my-check 1) (1 2) (1 2)) true)\n",
        "!(test (assert-answers (== 1 1) (my-check 1) (1) (1)) true)\n",
        "!(test (let $reported (catch (assert-answers false (my-check 1) (1 2) (1 3))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (my-check 1) (3) (2))\")\n",
        "!(test (let $reported (catch (assert-answers false (checked (f 1)) (a a b) (a b b))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (checked (f 1)) (b) (a))\")\n",
        "!(test (assert-includes-answers true (my-check 2) (1 2 3) (1 2)) true)\n",
        "!(test (let $reported (catch (assert-includes-answers false (my-check 2) (1 2) (7))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (my-check 2) (7) $_0)\")\n",
        "!(test (let $reported (catch (assertEqual (+ 1 1) 3)) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqual (+ 1 1) 3) (3) (2))\")\n",
        "!(test (let $reported (catch (assertIncludes (superpose (1 2)) (7))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertIncludes (superpose (1 2)) (7)) (7) $_0)\")\n",
        "(: assert-sorted (-> Atom Bool))\n",
        "(= (assert-sorted $expression) (let* (($answers (collapse $expression)) ($sorted (sort-atom $answers))) (assert-answers (== $answers $sorted) (assert-sorted $expression) $answers $sorted)))\n",
        "!(test (assert-sorted (superpose (1 2 3))) true)\n",
        "!(test (let $reported (catch (assert-sorted (superpose (3 1 2)))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assert-sorted (superpose (3 1 2))) () ())\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "assert_answers");
}
