/* Purpose: check atomops through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/07-atomops.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (cons-atom 0 (1 2 3)) (0 1 2 3))\n",
        "!(test (car-atom (1 2 3)) 1)\n",
        "!(test (cdr-atom (1 2 3)) (2 3))\n",
        "!(test (index-atom (1 2 3) 1) 2)\n",
        "!(test (id 5) 5)\n",
        "!(test (=alpha (Father $X) (Father $Y)) true)\n",
        "!(test (=alpha (Father $X) (Son $X)) false)\n",
        "!(test (first-from-pair (A B)) A)\n",
        "!(test (second-from-pair (A B)) B)\n",
        "!(test (index-atom (1 2 3) 5) ())\n",
        "!(test (index-atom (1 2 3) a) ())\n",
        "!(test (size-atom 5) ())\n",
        "!(test (sort-atom 5) ())\n",
        "!(test (unique-atom 5) ())\n",
        "!(test (alpha-unique-atom 5) ())\n",
        "!(test (min-atom 5) ())\n",
        "!(test (max-atom 5) ())\n",
        "!(test (intersection-atom 5 (a)) ())\n",
        "!(test (if-error (catch (car-atom $unbound)) refused answered) refused)\n",
        "!(test (if-error (catch (size-atom $unbound)) refused answered) refused)\n",
        "!(test (if-error (catch (sort-atom $unbound)) refused answered) refused)\n",
        "!(test (if-error (catch (index-atom $unbound 0)) refused answered) refused)\n",
        "!(test (if-error (catch (subtraction-atom $unbound (a b))) refused answered) refused)\n",
        "!(test (if-error (catch (car-atom (1 2))) refused answered) answered)\n",
        "!(test (car-atom (1 2)) 1)\n",
        "!(test (collapse (index-atom (a b c) $i)) (a b c))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "atomops");
}
