/* Purpose: check backward arithmetic through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-04-arithmetic-that-runs-backwards/01-backward_arithmetic.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (double $x) (* 2 $x))\n",
        "!(test (double 5) 10)\n",
        "!(test (let 10 (double $x) $x) 5)\n",
        "!(test (let 5 (+ $p 2) $p) 3)\n",
        "!(test (let 12 (* $q 4) $q) 3)\n",
        "!(test (let 6 (- $r 4) $r) 10)\n",
        "!(test (let 3 (/ $s 4) $s) 12)\n",
        "!(test (collapse (let 7 (double $x) $x)) ())\n",
        "(= (square $x) (* $x $x))\n",
        "!(test (collapse (let 25 (square $x) $x)) (noeval (-5 5)))\n",
        "!(test (collapse (let 25 (* $x $y) ($x $y))) (noeval ((-25 -1) (-5 -5) (-1 -25) (1 25) (5 5) (25 1))))\n",
        "!(test (collapse (let true (#>= $x 0) (let 25 (square $x) $x))) (5))\n",
        "!(test (let 20 (#* (#+ $a 1) 4) $a) 4)\n",
        "!(test (#div 13 4) 3)\n",
        "!(test (#mod 13 4) 1)\n",
        "!(test (#min 3 7) 3)\n",
        "!(test (#max 3 7) 7)\n",
        "!(test (#< 1 2) true)\n",
        "!(test (#< 2 1) false)\n",
        "!(test (#> 2 1) true)\n",
        "!(test (#= 3 3) true)\n",
        "!(test (#\\= 3 4) true)\n",
        "!(test (#=< 1 2) true)\n",
        "!(test (#=< 2 1) false)\n",
        "!(test (#>= 2 1) true)\n",
        "!(test (#>= 1 2) false)\n",
        "!(test (let 20 (#* (#+ $a 1) 4) $a) 4)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "backward_arithmetic");
}
