/* Purpose: check callquoteevalreduce2 through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/02-callquoteevalreduce2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (fib $N) (if (< $N 2) $N (+ (fib (- $N 1)) (fib (- $N 2)))))\n",
        "(= (myfunc) 5)\n",
        "(= (call-fib) (call (fib (myfunc))))\n",
        "(= (quote-fib) (quote (fib (myfunc))))\n",
        "(= (eval-fib) (eval (fib (myfunc))))\n",
        "(= (reduce-fib) (reduce (fib (myfunc))))\n",
        "!(test (fib-call (call-fib)) (fib-call 5))\n",
        "!(test (fib-quote (quote-fib)) (fib-quote (quote (fib (myfunc)))))\n",
        "!(test (fib-eval (eval-fib)) (fib-eval 5))\n",
        "!(test (fib-reduce (reduce-fib)) (fib-reduce 5))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "callquoteevalreduce2");
}
