/* Purpose: check callquoteevalreduce through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/01-callquoteevalreduce.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (before-call) (call-before (call (fib 5))))\n",
        "(= (before-quote) (quote-before (quote (fib 5))))\n",
        "(= (before-eval) (eval-before (eval (fib 5))))\n",
        "(= (before-reduce) (reduce-before (reduce (fib 5))))\n",
        "(= (compilefib) (let $temp (add-atom &self (= (fib $N) (if (< $N 2) $N (+ (fib (- $N 1)) (fib (- $N 2)))))) ((within (fib 5)) (call-within (call (fib 5))) (quote-within (quote (fib 5))) (eval-within (eval (fib 5))) (reduce-within (reduce (fib 5))))))\n",
        "!(test (before-call-errors-ofc (before-quote) (before-eval) (before-reduce)) (before-call-errors-ofc (quote-before (quote (fib 5))) (eval-before (eval (fib 5))) (reduce-before (reduce (fib 5)))))\n",
        "!(test (compilefib) ((within (noeval (fib 5))) (call-within 5) (quote-within (quote (fib 5))) (eval-within 5) (reduce-within 5)))\n",
        "(= (after-call) (call-after (call (fib 5))))\n",
        "(= (after-quote) (quote-after (quote (fib 5))))\n",
        "(= (after-eval) (eval-after (eval (fib 5))))\n",
        "(= (after-reduce) (reduce-after (reduce (fib 5))))\n",
        "!(test ((before-call) (before-quote) (before-eval) (before-reduce)) ((call-before 5) (quote-before (quote (fib 5))) (eval-before 5) (reduce-before 5)))\n",
        "!(test ((after-call) (after-quote) (after-eval) (after-reduce)) ((call-after 5) (quote-after (quote (fib 5))) (eval-after 5) (reduce-after 5)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "callquoteevalreduce");
}
