/* Purpose: check carrier vocabulary through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/09-carrier_vocabulary.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (match &metta (vocabulary semiring (:seg $names)) $names) (bool visibility bag counting set ranked tropical prob prov budget formula polynomial amplitude))\n",
        "!(test (match &metta (algebra budget $combine $extend $zero $one $laws $carrier $requires $owner) ($zero $owner)) (infinity global))\n",
        "!(test (match &metta (claim semiring budget $property $direction) ($property $direction)) (ordered ascending))\n",
        "!(test (match &metta (claim semiring tropical $property $direction) ($property $direction)) (ordered ascending))\n",
        "!(test (match &metta (algebra amplitude $c $e $z $o $l $ca $r $w) $z) (complex 0 0))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "carrier_vocabulary");
}
