/* Purpose: check case through the embedded source interface.
 * Source: examples/ch07-control-flow/07-02-case/01-case.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (casetest $x) (case $x ((4 42) ($otherpattern 44) ($otherother $45))))\n",
        "!(test (casetest 5) 44)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "case");
}
