/* Purpose: check case duals through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-01-logic-programs/06-case-duals.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (case-band $key) (case $key ((90 true) ($remaining (case $remaining ((40 false)))))))\n",
        "(= (case-default $key) (case $key ((90 true) ($remaining (case $remaining ((40 false) ($other false)))))))\n",
        "!(test (not-provable (case-band 90)) false)\n",
        "!(test (not-provable (case-band 40)) true)\n",
        "!(test (not-provable (case-band 55)) true)\n",
        "!(test (collapse (case-band 55)) ())\n",
        "!(test (not-provable (case-default 90)) false)\n",
        "!(test (not-provable (case-default 40)) true)\n",
        "!(test (not-provable (case-default 55)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "case_duals");
}
