/* Purpose: check casenew through the embedded source interface.
 * Source: examples/ch06-many-answers/02-casenew.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (wu1) (empty))\n",
        "(= (wu2) (full))\n",
        "(= (wu) (superpose ((wu1) (wu2))))\n",
        "!(test (wu) (full))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "casenew");
}
