/* Purpose: check case2 through the embedded source interface.
 * Source: examples/ch07-control-flow/07-02-case/02-case2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (compile $stmt) (case $stmt (($stmt (superpose (what what2))))))\n",
        "!(test (collapse (compile wat)) (what what2))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "case2");
}
