/* Purpose: check catalog through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/08-catalog.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (match &metta (vocabulary fidelity $a $b $c $d) ($a $b $c $d)) (Exact Partial Sound Refuse))\n",
        "!(test (match &metta (kind handles $ctx $entry $claim $det) $claim) (one-of fidelity))\n",
        "!(test (match &metta (claim semiring ranked $p $dir) ($p $dir)) (ordered descending))\n",
        "!(test (match &metta (claim semiring tropical $p $dir) ($p $dir)) (ordered ascending))\n",
        "!(add-atom &metta (vocabulary freshness-level live cached stale))\n",
        "!(add-atom &metta (kind freshness symbol pattern (one-of freshness-level)))\n",
        "!(add-atom &metta (freshness &rows (edge $a $b) cached))\n",
        "!(test (match &metta (freshness &rows $shape $level) $level) cached)\n",
        "!(add-atom &metta (routed-by-shape freshness))\n",
        "!(test (match &metta (routed-by-shape freshness) found) found)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "catalog");
}
