/* Purpose: check chain through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/06-chain.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (chain (+ 2 4) $n (* 3 $n)) 18)\n",
        "!(test (chain (+ 1 3) $n (chain (* 2 $n) $m (+ $n $m))) 12)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "chain");
}
