/* Purpose: check channels pools and the machine through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/05-channels_pools_and_the_machine.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_thread))\n",
        "(: inc (-> Number Number))\n",
        "(= (inc $x) (+ $x 1))\n",
        "!(test (let $c (channel) (collapse (try-recv $c))) ())\n",
        "!(test (let $c (channel) (let $_1 (send $c hello) (collapse (try-recv $c)))) (hello))\n",
        "!(test (let $c (channel) (let $_1 (send $c one) (let $__ (send $c two) (let $first (try-recv $c) (let $second (try-recv $c) ($first $second (collapse (try-recv $c)))))))) (one two ()))\n",
        "!(test (let $c (channel) (channel-close $c)) true)\n",
        "!(test (let $c (channel) (let $_1 (channel-close $c) (let $reported (catch (channel-close $c)) (unify $reported (Error $ball $context) (index-atom $ball 1) no-error)))) metta_channel)\n",
        "!(test (let $c (channel) (let $_1 (channel-close $c) (let $reported (catch (try-recv $c)) (unify $reported (Error $ball $context) (car-atom $ball) no-error)))) existence_error)\n",
        "!(test (let $p (pool reporting-pool 2) (pool-stats reporting-pool)) ((size 2) (running 0) (backlog 0) (free 2)))\n",
        "!(test (let $stats (pool-stats reporting-pool) (let $running (index-atom (index-atom $stats 1) 1) (let $free (index-atom (index-atom $stats 3) 1) (+ $running $free)))) 2)\n",
        "!(test (let $h (submit reporting-pool (inc 9)) (await $h)) 10)\n",
        "!(test (pool-stats reporting-pool) ((size 2) (running 0) (backlog 0) (free 2)))\n",
        "!(test (pool-destroy reporting-pool) true)\n",
        "!(test (let $p (pool reporting-pool 1) (pool-stats reporting-pool)) ((size 1) (running 0) (backlog 0) (free 1)))\n",
        "!(test (pool-destroy reporting-pool) true)\n",
        "!(test (let $t (every 0.05 (inc 41)) (let $_1 (sleep 0.2) (let $__ (cancel $t) stopped))) stopped)\n",
        "!(test (let $t (every 30 (inc 41)) (let $settled (settled? $t) (let $_2 (cancel $t) $settled))) false)\n",
        "!(test (> (cpu-count) 0) true)\n",
        "!(test (> (thread-count) 0) true)\n",
        "!(test (let $before (thread-count) (let $f (spawn (let $_2 (sleep 0.2) 1)) (let $during (thread-count) (let $__ (await $f) (> $during $before))))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "channels_pools_and_the_machine");
}
