/* Purpose: check class entities through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/10-class_entities.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &Account (: Account (-> Atom Account)))\n",
        "!(add-atom &Account (internal owned-by _field-owner _field-balance))\n",
        "!(add-atom &Account (= (Account-balance (Account $id)) (match &Account (_field-balance (Account $id) $n) $n)))\n",
        "!(add-atom &Account (= (Account-balance! (Account $id) $n) (transaction (progn (remove-atom &Account (_field-balance (Account $id) $old)) (add-atom &Account (_field-balance (Account $id) $n)) true))))\n",
        "!(add-atom &Account (= (make-Account $owner $balance) (transaction (progn (add-atom &Account (owned-by (Account $id)) $id) (add-atom &Account (_field-owner (Account $id) $owner)) (add-atom &Account (_field-balance (Account $id) $balance)) (Account $id)))))\n",
        "!(add-atom &Account (= (Account-deposit (Account $id) $n) (Account-balance! (Account $id) (+ (Account-balance (Account $id)) $n))))\n",
        "!(add-atom &Account (= (Account-withdraw (Account $id) $n) (if (< (Account-balance (Account $id)) $n) (Error (Account $id) overdraft) (Account-balance! (Account $id) (- (Account-balance (Account $id)) $n)))))\n",
        "!(add-atom &self (from &Account))\n",
        "!(bind! &alice (make-Account alice 40))\n",
        "!(bind! &bob (make-Account bob 80))\n",
        "!(test (Account-deposit &alice 25) true)\n",
        "!(test (Account-balance &alice) 65)\n",
        "!(test (if-error (transaction (Account-withdraw &alice 500)) refused unexpected) refused)\n",
        "!(test (Account-balance &alice) 65)\n",
        "!(test (Account-withdraw &bob 30) true)\n",
        "!(test (msort (collapse (match &Account (_field-balance $account $n) $n))) (50 65))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "class_entities");
}
