/* Purpose: check class decorators through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/13-class_decorators.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &Circle (: Circle (-> Number Circle)))\n",
        "!(add-atom &Circle (= (Circle-area (Circle $r)) (* 3 (* $r $r))))\n",
        "!(add-atom &Circle (= (Circle-unit Circle) (Circle 1)))\n",
        "!(add-atom &Circle (= (Circle-grow $r $by) (+ $r $by)))\n",
        "!(add-atom &Money (: Money (-> Number Money)))\n",
        "!(add-atom &Money (= (Money-eq (Money $a) (Money $b)) (== $a $b)))\n",
        "!(add-atom &Money (= (Money-lt (Money $a) (Money $b)) (< $a $b)))\n",
        "!(add-atom &Money (= (Money-le $a $b) (or (Money-lt $a $b) (Money-eq $a $b))))\n",
        "!(add-atom &Money (= (Money-gt $a $b) (Money-lt $b $a)))\n",
        "!(add-atom &Vector (: Vector (-> Number Number Vector)))\n",
        "!(add-atom &Vector (= (Vector-add (Vector $x1 $y1) (Vector $x2 $y2)) (Vector (+ $x1 $x2) (+ $y1 $y2))))\n",
        "!(add-atom &Stack (: Stack (-> Expression Stack)))\n",
        "!(add-atom &Stack (= (Stack-len (Stack $items)) (size-atom $items)))\n",
        "!(add-atom &Stack (= (Stack-iter (Stack $items)) (superpose $items)))\n",
        "!(add-atom &Adder (: Adder (-> Number Adder)))\n",
        "!(add-atom &Adder (= (Adder-call (Adder $n) $x) (+ $n $x)))\n",
        "!(add-atom &Shape (: Shape Type))\n",
        "!(add-atom &Shape (: Shape-area (-> Shape Number)))\n",
        "!(add-atom &Square (: Square (-> Number Square)))\n",
        "!(add-atom &Square (:< Square Shape))\n",
        "!(add-atom &Square (= (Square-area (Square $s)) (* $s $s)))\n",
        "!(add-atom &self (from &Circle))\n",
        "!(add-atom &self (from &Money))\n",
        "!(add-atom &self (from &Vector))\n",
        "!(add-atom &self (from &Stack))\n",
        "!(add-atom &self (from &Adder))\n",
        "!(add-atom &self (from &Shape))\n",
        "!(add-atom &self (from &Square))\n",
        "!(test (Circle-area (Circle 2)) 12)\n",
        "!(test (Circle-unit Circle) (Circle 1))\n",
        "!(test (Circle-grow 2 3) 5)\n",
        "!(test (Money-le (Money 5) (Money 5)) true)\n",
        "!(test (Money-gt (Money 7) (Money 5)) true)\n",
        "!(test (Money-gt (Money 5) (Money 5)) false)\n",
        "!(test (Vector-add (Vector 1 2) (Vector 3 4)) (Vector 4 6))\n",
        "!(test (Stack-len (Stack (1 2 3))) 3)\n",
        "!(test (collapse (Stack-iter (Stack (1 2 3)))) (1 2 3))\n",
        "!(test (Adder-call (Adder 10) 4) 14)\n",
        "!(test (Square-area (Square 3)) 9)\n",
        "!(test (collapse (match &Shape (: Shape-area $arrow) $arrow)) ((-> Shape Number)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "class_decorators");
}
