/* Purpose: check class values through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/09-class_values.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &Point (: Point (-> Number Number Point)))\n",
        "!(add-atom &Point (= (Point-x (Point $x $y)) $x))\n",
        "!(add-atom &Point (= (Point-y (Point $x $y)) $y))\n",
        "!(add-atom &Point (= (Point-norm (Point $x $y)) (sqrt-math (+ (* $x $x) (* $y $y)))))\n",
        "!(add-atom &Point (= (Point-add (Point $x1 $y1) (Point $x2 $y2)) (Point (+ $x1 $x2) (+ $y1 $y2))))\n",
        "!(add-atom &Point (= (Point-quadrant $p) (case $p (((Point 0 0) origin) ((Point 0 $y) axis) ((Point $x $y) plane)))))\n",
        "!(add-atom &self (from &Point))\n",
        "!(test (Point-norm (Point 3 4)) 5.0)\n",
        "!(test (Point-add (Point 1 2) (Point 3 4)) (Point 4 6))\n",
        "!(test (Point-quadrant (Point 0 0)) origin)\n",
        "!(test (Point-quadrant (Point 0 4)) axis)\n",
        "!(test (Point-quadrant (Point 3 4)) plane)\n",
        "!(test (== (Point-add (Point 1 2) (Point 3 4)) (Point 4 6)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "class_values");
}
