/* Purpose: check class dispatch through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/11-class_dispatch.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &Shape (: Shape Type))\n",
        "!(add-atom &Shape (= (Shape-describe $shape) (area-of (area $shape))))\n",
        "!(add-atom &Circle (: Circle (-> Number Circle)))\n",
        "!(add-atom &Circle (:< Circle Shape))\n",
        "!(add-atom &Circle (from &Shape))\n",
        "!(add-atom &Circle (= (Circle-area (Circle $r)) (* 3 (* $r $r))))\n",
        "!(add-atom &Circle (= (Circle-describe (Circle $r)) (circle (Shape-describe (Circle $r)))))\n",
        "!(add-atom &Circle (= (area (Circle $r)) (Circle-area (Circle $r))))\n",
        "!(add-atom &Circle (= (describe (Circle $r)) (Circle-describe (Circle $r))))\n",
        "!(add-atom &Square (: Square (-> Number Square)))\n",
        "!(add-atom &Square (:< Square Shape))\n",
        "!(add-atom &Square (from &Shape))\n",
        "!(add-atom &Square (= (Square-area (Square $s)) (* $s $s)))\n",
        "!(add-atom &Square (= (area (Square $s)) (Square-area (Square $s))))\n",
        "!(add-atom &Square (= (describe (Square $s)) (Shape-describe (Square $s))))\n",
        "!(add-atom &Shape (from &Circle (only (area describe))))\n",
        "!(add-atom &Shape (from &Square (only (area describe))))\n",
        "!(add-atom &self (from &Shape))\n",
        "!(add-atom &self (from &Circle))\n",
        "!(add-atom &self (from &Square))\n",
        "!(test (area (Circle 2)) 12)\n",
        "!(test (area (Square 3)) 9)\n",
        "!(test (describe (Square 3)) (area-of 9))\n",
        "!(test (describe (Circle 2)) (circle (area-of 12)))\n",
        "!(test (collapse (get-type (Circle 2))) (quote (Circle Shape)))\n",
        "!(test (collapse (match &Circle (:< Circle $base) $base)) (Shape))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "class_dispatch");
}
