/* Purpose: check class prototypes through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/12-class_prototypes.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &Actor (: Actor (-> SpaceType Actor)))\n",
        "!(add-atom &Actor (internal _field-mood))\n",
        "!(add-atom &Actor (= (Actor-mood (Actor $space)) (match $space (_field-mood $mood) $mood)))\n",
        "!(add-atom &Actor (= (make-Actor $mood) (let $space (new-space) (progn (add-atom $space (from &Actor)) (add-atom $space (_field-mood $mood)) (Actor $space)))))\n",
        "!(add-atom &Actor (= (Actor-decide (Actor $space)) (act-on (Actor-mood (Actor $space)))))\n",
        "!(add-atom &Actor (= (decide (Actor $space)) (Actor-decide (Actor $space))))\n",
        "!(add-atom &self (from &Actor))\n",
        "!(bind! &calm (make-Actor calm))\n",
        "!(bind! &alert (make-Actor alert))\n",
        "!(test (decide &calm) (act-on calm))\n",
        "!(test (decide &alert) (act-on alert))\n",
        "!(let (Actor $space) &calm (add-atom $space (= (private-rule $actor) (secret (Actor-mood $actor)))))\n",
        "!(test (let (Actor $space) &calm (evalc (private-rule &calm) $space)) (secret calm))\n",
        "!(test (== (private-rule &calm) (quote (private-rule &calm))) true)\n",
        "!(add-atom &Scout (: Scout (-> SpaceType Scout)))\n",
        "!(add-atom &Scout (:< Scout Actor))\n",
        "!(add-atom &Scout (from &Actor))\n",
        "!(add-atom &Scout (= (make-Scout $mood) (let $space (new-space) (progn (add-atom $space (from &Scout)) (add-atom $space (_field-mood $mood)) (Scout $space)))))\n",
        "!(add-atom &Scout (= (Scout-decide (Scout $space)) (scouting (Actor-mood (Actor $space)))))\n",
        "!(add-atom &Scout (= (decide (Scout $space)) (Scout-decide (Scout $space))))\n",
        "!(add-atom &self (from &Scout))\n",
        "!(bind! &scout (make-Scout curious))\n",
        "!(test (decide &scout) (scouting curious))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "class_prototypes");
}
