/* Purpose: check collapse through the embedded source interface.
 * Source: examples/ch06-many-answers/03-collapse.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (collapse (1 2 3)) ((1 2 3)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "collapse");
}
