/* Purpose: check combinatorics lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/11-combinatorics_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_combinatorics))\n",
        "!(test (sort-atom (collapse (choose2 (a b c)))) ((a b) (a c) (b c)))\n",
        "!(test (collapse (choose2 (a))) ())\n",
        "!(test (collapse (choose2 ())) ())\n",
        "!(test (choose2l (a b c)) ((a b) (a c) (b c)))\n",
        "!(test (choose2l (a)) ())\n",
        "!(test (chooseKl (a b c) 2) ((a b) (a c) (b c)))\n",
        "!(test (chooseKl (a b c d) 3) ((a b c) (a b d) (a c d) (b c d)))\n",
        "!(test (== (chooseKl (a b c) 2) (choose2l (a b c))) true)\n",
        "!(test (chooseKl (a b c) 0) (()))\n",
        "!(test (chooseKl () 2) ())\n",
        "!(test (chooseKl () 0) (()))\n",
        "!(test (sort-atom (collapse (chooseK (a b c) 2))) ((a b) (a c) (b c)))\n",
        "!(test (collapse (chooseK (a b c) 0)) (()))\n",
        "!(test (takeK 2 (a b c)) (a b))\n",
        "!(test (takeK 0 (a b c)) ())\n",
        "!(test (takeK 5 (a b c)) (a b c))\n",
        "!(test (takeK 2 ()) ())\n",
        "!(test (collapse (range 0 4)) (0 1 2 3))\n",
        "!(test (collapse (range-step 0 10 3)) (0 3 6 9))\n",
        "!(test (collapse (range-step 5 0 -2)) (5 3 1))\n",
        "!(test (collapse (range-step 0 0 1)) ())\n",
        "!(test (collapse (range-step 0 5 -1)) ())\n",
        "!(test (if-error (catch (collapse (range-step 0 5 0))) refused fine) refused)\n",
        "!(test (collapse (permutations (a b c))) ((a b c) (a c b) (b a c) (b c a) (c a b) (c b a)))\n",
        "!(test (collapse (permutations ())) (()))\n",
        "!(test (size-atom (collapse (permutations (a a)))) 2)\n",
        "!(test (collapse (subsets (a b))) ((a b) (b) (a) ()))\n",
        "!(test (collapse (subsets ())) (()))\n",
        "!(test (size-atom (collapse (subsets (a b c d)))) 16)\n",
        "!(test (collapse (tuples ((1 2) (x y)))) ((1 x) (1 y) (2 x) (2 y)))\n",
        "!(test (collapse (tuples ((1 2) ()))) ())\n",
        "!(test (collapse (tuples ())) (()))\n",
        "!(test (collapse (cartesian-power (0 1) 2)) ((0 0) (0 1) (1 0) (1 1)))\n",
        "!(test (size-atom (collapse (cartesian-power (0 1) 3))) 8)\n",
        "!(test (collapse (cartesian-power (a b) 0)) (()))\n",
        "!(test (factorial 5) 120)\n",
        "!(test (factorial 0) 1)\n",
        "!(test (binomial 5 2) 10)\n",
        "!(test (binomial 52 5) 2598960)\n",
        "!(test (binomial 5 0) 1)\n",
        "!(test (binomial 5 9) 0)\n",
        "!(test (permutation-count 5 2) 20)\n",
        "!(test (permutation-count 5 5) (factorial 5))\n",
        "!(test (permutation-count 5 0) 1)\n",
        "!(test (if-error (catch (factorial -1)) refused fine) refused)\n",
        "!(test (== (size-atom (collapse (permutations (a b c)))) (factorial 3)) true)\n",
        "!(test (== (size-atom (collapse (chooseK (a b c d) 2))) (binomial 4 2)) true)\n",
        "!(test (== (size-atom (collapse (subsets (a b c)))) (pow-math 2 3)) true)\n",
        "!(test (== (size-atom (collapse (cartesian-power (a b) 3))) (pow-math 2 3)) true)\n",
        "!(test (choose2 (quote ((+ 1 2) a))) (quote ((+ 1 2) a)))\n",
        "!(test (chooseKl (quote ((+ 1 2) a)) 1) (quote (((+ 1 2)) (a))))\n",
        "!(test (takeK 1 (quote ((+ 1 2) a))) (quote ((+ 1 2))))\n",
        "!(test (collapse (permutations (quote ((+ 1 2) (Error a b))))) (quote (((+ 1 2) (Error a b)) ((Error a b) (+ 1 2)))))\n",
        "!(test (collapse (subsets (quote ((+ 1 2) a)))) (quote (((+ 1 2) a) (a) ((+ 1 2)) ())))\n",
        "!(test (collapse (tuples (quote (((+ 1 2) (Error a b)) (a))))) (quote (((+ 1 2) a) ((Error a b) a))))\n",
        "!(test (once (chooseK (collapse (range 0 100)) 50)) (collapse (range 0 50)))\n",
        "!(test (collapse (cartesian-power () 9999999999999999999999999999999)) ())\n",
        "!(test (if-error (catch (tuples (() 3))) refused fine) refused)\n",
        "!(test (if-error (catch (cartesian-power (0 1) 1.0)) refused fine) refused)\n",
        "!(test (if-error (catch (factorial 1.0)) refused fine) refused)\n",
        "!(test (binomial 100 50) 100891344545564193334812497256)\n",
        "!(test (collapse (range-step 0.5 2.0 1)) (0.5 1.5))\n",
        "!(test (collapse (if-error (catch (range-step 1e20 1e21 1)) refused fine)) (fine refused))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "combinatorics_lib");
}
