/* Purpose: check compiled overloads through the embedded source interface.
 * Source: examples/ch09-types/18-compiled_overloads.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: compiled-identity (-> Number Number))\n",
        "(: compiled-identity (-> String String))\n",
        "(= (compiled-identity $value) $value)\n",
        "!(test (collapse (get-type compiled-identity)) ((-> Number Number) (-> String String)))\n",
        "!(test (compiled-identity 7) 7)\n",
        "!(test (compiled-identity \"word\") \"word\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "compiled_overloads");
}
