/* Purpose: check compose through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/21-compose.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_patrick))\n",
        "(: inc (-> Number Number))\n",
        "(= (inc $x) (+ $x 1))\n",
        "(: double (-> Number Number))\n",
        "(= (double $x) (* $x 2))\n",
        "!(test (compose (inc) (5)) 6)\n",
        "!(test (compose (double) (5)) 10)\n",
        "!(test (compose (inc double) (5)) 11)\n",
        "!(test (compose (double inc) (5)) 12)\n",
        "!(test (compose (+) (2 3)) 5)\n",
        "!(test (compose (inc +) (2 3)) 6)\n",
        "!(test (compose (double inc +) (2 3)) 12)\n",
        "!(test (compose (inc) ((compose (double) (5)))) 11)\n",
        "!(test (== (compose (inc double) (5)) (compose (inc) ((compose (double) (5))))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "compose");
}
