/* Purpose: check conformance through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/09-conformance.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_conformance))\n",
        "!(import_prolog_functions_from_file \"./fixtures/libraries/demo_provider.pl\" ())\n",
        "!(test (check-space-provider &demo_provider) (\"match: declared, seam:foreign_match/3 has clauses\" \"enumerate: declared, seam:foreign_atoms/2 has clauses\" \"match: over-approximation holds over 2 atoms and their pattern families\" \"source: repeated, two enumerations agree\" \"round trip: not asked, the provider does not declare add, remove and enumerate together\" \"pushdown: 0 of 2 patterns claimed exact, and are\" \"plan: not declared, so a conjunction takes the engine's split\"))\n",
        "!(test (sort-atom (collapse (match &demo_provider (edge a $y) $y))) (b))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "conformance");
}
