/* Purpose: check constraint domains through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-04-arithmetic-that-runs-backwards/03-constraint_domains.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_constraints))\n",
        "!(test (let true (clpq (= (* 2 $x) 1)) (repr $x)) \"1r2\")\n",
        "!(test (let true (clpq (= (* 2 $x) 1)) (* 2 $x)) 1)\n",
        "!(test (collapse (let true (clpq (>= $a 0)) (clpq-entailed (>= $a 0)))) (true))\n",
        "!(test (collapse (let true (clpq (>= $b 0)) (clpq-entailed (>= $b 5)))) (false))\n",
        "!(test (collapse (let true (clpq (= $c 1)) (clpq (= $c 2)))) ())\n",
        "!(test (collapse (let true (clpq (= $d 1)) (let true (clpq (= $e 2)) (clpq (=\\= $d $e))))) (true))\n",
        "!(test (let true (clpq (>= $f 0)) (let true (clpq (=< $f 3)) (repr (residual-goals $f)))) \"(({} (, (>= $_0 0) (=< $_0 3))))\")\n",
        "!(test (collapse (let true (clpb (card (1) ($m $n))) (clpb-labeling ($m $n)))) ((0 1) (1 0)))\n",
        "!(test (clpb-taut (+ $t (~ $t))) true)\n",
        "!(test (clpb-taut (* $u (~ $u))) false)\n",
        "!(test (if (and (or $x true) $y) ($x $y)) ((true true) (false true)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "constraint_domains");
}
