/* Purpose: check constanthead through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-02-patterns-and-bindings/05-constanthead.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (h (justdata haha $B) $C) (+ $B $C))\n",
        "!(test (h (justdata haha 30) 40) 70)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "constanthead");
}
