/* Purpose: check crypto lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/06-crypto_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_crypto))\n",
        "!(test (crypto-hash sha256 \"hello\") \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\")\n",
        "!(test (crypto-hash sha512 \"hello\") \"9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca72323c3d99ba5c11d7c7acc6e14b8c5da0c4663475c2e5c3adef46f73bcdec043\")\n",
        "(= (content-key $text) (crypto-hash sha256 $text))\n",
        "!(test (content-key \"hello\") \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\")\n",
        "!(test (crypto_hash sha256 \"hello\") \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\")\n",
        "!(test (crypto-hash-bytes sha256 (104 101 108 108 111)) \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\")\n",
        "!(test (crypto-hash-bytes sha256 ()) \"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\")\n",
        "!(test (crypto-hmac sha256 \"Jefe\" \"what do ya want for nothing?\") \"5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843\")\n",
        "!(test (crypto-hmac-bytes sha256 (195 169) (0 255)) \"6a96aac37f1ab07208ddcd8a71292bd9fc92722a85ca984fa3adcd07fede237d\")\n",
        "!(import! &self (library lib_string))\n",
        "!(test (crypto_random_hex 0) \"\")\n",
        "!(test (string-length (crypto-random-hex 4)) 8)\n",
        "!(test (crypto-random-bytes 0) ())\n",
        "!(test (size-atom (crypto-random-bytes 8)) 8)\n",
        "!(test (crypto-random-integer -9 -8) -9)\n",
        "!(test (let $n (crypto-random-integer -20 7) (and (>= $n -20) (< $n 7))) true)\n",
        "!(test (let $record (crypto-password-hash \"fixture\") (crypto-password-verify \"fixture\" $record)) true)\n",
        "!(test (let $record (crypto-password-hash \"fixture\" 2) (crypto-password-verify \"fixture\" $record)) true)\n",
        "!(test (let $record (crypto-password-hash \"fixture\" 2) (crypto-password-verify \"different\" $record)) false)\n",
        "!(import! &self (library lib_file))\n",
        "!(test (let* (($path (temp-path! \"crypto-content\")) ($_1 (write-file! $path \"hello\")) ($digest (crypto-hash-file! sha256 $path))) (chain (delete-file! $path) $_3 $digest)) \"2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "crypto_lib");
}
