/* Purpose: check csv lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/17-csv_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_csv))\n",
        "!(test (csv-parse \"001,\\\"a,b\\\"\\r\\n002,9\\r\\n\") ((\"001\" \"a,b\") (\"002\" \"9\")))\n",
        "!(test (csv-encode ((\"001\" \"a,b\") (\"002\" \"9\"))) \"001,\\\"a,b\\\"\\r\\n002,9\\r\\n\")\n",
        "!(test (csv-parse \"id;value\\n001;a\\n001;a\\n\" (quote ((separator \";\") (skip 1)))) ((\"001\" \"a\") (\"001\" \"a\")))\n",
        "!(test (csv-encode ((\"001\" \"a;b\")) (quote ((separator \";\") (newline \"\\n\")))) \"001;\\\"a;b\\\"\\n\")\n",
        "!(test (csv-parse \"\") ())\n",
        "!(test (csv-encode ()) \"\")\n",
        "!(test (csv-parse \"\\n\\\"\\\"\\n,\\n\" (quote ((width any)))) (() (\"\") (\"\" \"\")))\n",
        "!(test (csv-parse \"a\\\"b,c\\n\" (quote ((quote \"\")))) ((\"a\\\"b\" \"c\")))\n",
        "!(test (csv-parse (csv-encode ((\"é🦊\" \"λ\\r\\n\")) (quote ((separator \"🦊\") (quote \"λ\")))) (quote ((separator \"🦊\") (quote \"λ\")))) ((\"é🦊\" \"λ\\r\\n\")))\n",
        "!(import! &self (library lib_file))\n",
        "!(bind! &csv-dir (temp-dir! \"metta-csv\"))\n",
        "!(bind! &csv-path (path-join &csv-dir \"records.csv\"))\n",
        "!(test (csv-write! &csv-path ((\"001\" \"a,b\") (\"002\" \"9\"))) true)\n",
        "!(test (collapse (csv-read! &csv-path)) ((\"001\" \"a,b\") (\"002\" \"9\")))\n",
        "!(test (csv-append! &csv-path ((\"002\" \"9\"))) true)\n",
        "!(test (collapse (csv-read! &csv-path)) ((\"001\" \"a,b\") (\"002\" \"9\") (\"002\" \"9\")))\n",
        "!(bind! &csv-live (csv-space &csv-path))\n",
        "!(test (collapse (match &csv-live (row $id $value) ($id $value))) ((\"001\" \"a,b\") (\"002\" \"9\") (\"002\" \"9\")))\n",
        "!(bind! &csv-shot (csv-snapshot! &csv-path))\n",
        "!(test (collapse (match &csv-shot (row $n $id $value) ($n $id $value))) ((1 \"001\" \"a,b\") (2 \"002\" \"9\") (3 \"002\" \"9\")))\n",
        "!(test (csv-write! &csv-path ((\"id\" \"value\") (\"003\" \"a;b\")) (quote ((separator \";\")))) true)\n",
        "!(test (csv-append! &csv-path ((\"004\" \"7\")) (quote ((separator \";\")))) true)\n",
        "!(test (collapse (csv-read! &csv-path (quote ((separator \";\") (skip 1))))) ((\"003\" \"a;b\") (\"004\" \"7\")))\n",
        "!(bind! &csv-configured (csv-space &csv-path (quote ((separator \";\") (skip 1)))))\n",
        "!(test (collapse (match &csv-configured (row $id $value) ($id $value))) ((\"003\" \"a;b\") (\"004\" \"7\")))\n",
        "!(bind! &csv-numbered (csv-snapshot! &csv-path (quote ((separator \";\") (skip 1)))))\n",
        "!(test (collapse (match &csv-numbered (row $n $id $value) ($n $id $value))) ((2 \"003\" \"a;b\") (3 \"004\" \"7\")))\n",
        "!(test (collapse (match &csv-shot (row $n $id $value) ($n $id $value))) ((1 \"001\" \"a,b\") (2 \"002\" \"9\") (3 \"002\" \"9\")))\n",
        "!(csv-write! &csv-path ((\"id\" \"value\") (\"005\" \"later\")) (quote ((separator \";\"))))\n",
        "!(test (collapse (match &csv-configured (row $id $value) ($id $value))) ((\"005\" \"later\")))\n",
        "!(delete-file! &csv-path)\n",
        "!(delete-file! (path-join &csv-dir \"records.csv.metta-csv.lock\"))\n",
        "!(delete-dir! &csv-dir)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "csv_lib");
}
