/* Purpose: check curry through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/04-curry.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f $a $b) (+ $a $b))\n",
        "(= (g $a $b $c) (+ $c (+ $a $b)))\n",
        "(= (show) (repr (f 1)))\n",
        "!(test (repr (f 1)) \"(partial f (1))\")\n",
        "!(test ((f 1) 2) 3)\n",
        "!(test (repr (g 1 2)) \"(partial g (1 2))\")\n",
        "(= (h $A $B) (append ($A) $B))\n",
        "!(test ((h 42) (1 2 3)) (42 1 2 3))\n",
        "!(test (repr (h 42)) \"(partial h (42))\")\n",
        "!(test (map-atom (1 2 3) (+ 1)) (2 3 4))\n",
        "!(test (repr (catch (+ 1 2 3))) \"(Error (domain_error (function_input_arities + (2)) 3) none)\")\n",
        "!(test (repr (catch (reduce (+ 1 2 3)))) \"(Error (domain_error (function_input_arities + (2)) 3) none)\")\n",
        "!(test (repr (catch (empty 1 2))) \"(Error (domain_error (function_input_arities empty (0)) 2) none)\")\n",
        "!(test (nosuchfn 1 2 3) (nosuchfn 1 2 3))\n",
        "(= (overloaded-curry $a) $a)\n",
        "(= (overloaded-curry $a $b $c) (+ $a (+ $b $c)))\n",
        "!(test (repr (overloaded-curry 1 2)) \"(partial overloaded-curry (1 2))\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "curry");
}
