/* Purpose: check cut through the embedded source interface.
 * Source: examples/ch07-control-flow/07-04-bounded-and-committed-searches/04-cut.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(foo 1)\n",
        "(foo 2)\n",
        "(= (match-single $space $pat $ret) (let* (($x (match $space $pat $ret)) ($temp (cut))) $x))\n",
        "!(let $x (match-single &self (foo $1) $1) (add-atom &self (bar $x)))\n",
        "!(test (collapse (match &self (bar $1) (bar $1))) ((bar 1)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "cut");
}
