/* Purpose: check datastructures lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/21-datastructures_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_datastructures))\n",
        "!(bind! &prices (map-from-pairs ((pear 5) (apple 3) (plum 7))))\n",
        "!(test (map-size &prices) 3)\n",
        "!(test (map-keys &prices) (apple pear plum))\n",
        "!(test (map-values &prices) (3 5 7))\n",
        "!(test (map-pairs &prices) ((apple 3) (pear 5) (plum 7)))\n",
        "!(test (map-get &prices pear) 5)\n",
        "!(test (collapse (map-get &prices durian)) ())\n",
        "!(test (map-get-or &prices durian 0) 0)\n",
        "!(test (map-has &prices apple) true)\n",
        "!(test (map-has &prices durian) false)\n",
        "!(test (map-min &prices) (apple 3))\n",
        "!(test (map-max &prices) (plum 7))\n",
        "!(bind! &raised (map-put &prices pear 6))\n",
        "!(test (map-pairs &raised) ((apple 3) (pear 6) (plum 7)))\n",
        "!(test (map-pairs &prices) ((apple 3) (pear 5) (plum 7)))\n",
        "!(test (map-pairs (map-remove &prices pear)) ((apple 3) (plum 7)))\n",
        "!(test (map-pairs (map-remove &prices durian)) ((apple 3) (pear 5) (plum 7)))\n",
        "!(test (map-size (map-empty)) 0)\n",
        "!(test (map-pairs (map-put (map-empty) k v)) ((k v)))\n",
        "!(test (if-error (catch (map-from-pairs ((k 1) (k 2)))) refused fine) refused)\n",
        "!(test (if-error (catch (map-get 42 k)) refused fine) refused)\n",
        "!(bind! &work (pq-from-pairs ((3 sweep) (1 wake) (2 boil))))\n",
        "!(test (pq-size &work) 3)\n",
        "!(test (pq-min &work) (1 wake))\n",
        "!(test (pq-pairs &work) ((1 wake) (2 boil) (3 sweep)))\n",
        "!(test (let ($priority $value $rest) (pq-pop &work) ($priority $value (pq-size $rest))) (1 wake 2))\n",
        "!(test (let ($priority $value $rest) (pq-pop &work) (pq-pairs $rest)) ((2 boil) (3 sweep)))\n",
        "!(test (pq-size &work) 3)\n",
        "!(test (pq-size (pq-from-pairs ((1 a) (1 b)))) 2)\n",
        "!(test (pq-pairs (pq-insert &work 0 rise)) ((0 rise) (1 wake) (2 boil) (3 sweep)))\n",
        "!(test (pq-pairs (pq-merge &work (pq-from-pairs ((0 rise))))) ((0 rise) (1 wake) (2 boil) (3 sweep)))\n",
        "!(test (pq-pairs (pq-remove &work 2 boil)) ((1 wake) (3 sweep)))\n",
        "!(test (collapse (pq-remove &work 2 absent)) ())\n",
        "!(test (pq-size (pq-empty)) 0)\n",
        "!(test (collapse (pq-min (pq-empty))) ())\n",
        "!(test (collapse (pq-pop (pq-empty))) ())\n",
        "!(test (if-error (catch (pq-size 42)) refused fine) refused)\n",
        "!(test (enqueue 2 (enqueue 1 (empty-queue))) (queue (cons 2 (cons 1 ())) () 2))\n",
        "!(test (dequeue 1 (enqueue 2 (enqueue 1 (empty-queue)))) (queue () (cons 2 ()) 1))\n",
        "!(test (ft-to-list (ft-from-list (1 2 3))) (1 2 3))\n",
        "!(test (ft-front (ft-from-list (1 2 3))) 1)\n",
        "!(test (ft-back (ft-from-list (1 2 3))) 3)\n",
        "!(test (ft-to-list (ft-concat (ft-from-list (1 2)) (ft-from-list (3 4)))) (1 2 3 4))\n",
        "!(test (ft-is-empty (ft-empty)) true)\n",
        "!(test (== &prices (SortedMap ((apple 3) (pear 5) (plum 7)))) true)\n",
        "!(test (let (SortedMap $rows) &prices (pairs-lookup $rows pear)) 5)\n",
        "!(test (pq-merge) (pq-empty))\n",
        "!(test (pq-merge &work) &work)\n",
        "!(test (pq-size (pq-merge &work &work &work)) 9)\n",
        "!(test (pq-size (apply-to pq-merge (quote (&work &work)))) 6)\n",
        "!(test (pq-pairs (pq-from-pairs ((1 a) (1 b) (1 c)))) ((1 a) (1 b) (1 c)))\n",
        "!(test (pq-pairs (pq-insert (pq-from-pairs ((1 a) (1 b))) 1 c)) ((1 a) (1 b) (1 c)))\n",
        "!(test (pq-pairs (pq-remove (pq-from-pairs ((1 a) (1 a) (2 b))) 1 a)) ((1 a) (2 b)))\n",
        "!(test (if-error (catch (map-from-pairs (($x a) ($x b)))) refused fine) refused)\n",
        "!(test (if-error (catch (map-from-pairs ($pair))) refused fine) refused)\n",
        "!(test (let $map (map-from-pairs (($x a) ($y b))) (map-get $map $x)) a)\n",
        "!(test (map-get (map-from-pairs (quote (((+ 1 2) (Error data code))))) (quote (+ 1 2))) (quote (Error data code)))\n",
        "!(test (if-error (catch (map-size (pq-empty))) refused fine) refused)\n",
        "!(test (if-error (catch (pq-size (map-empty))) refused fine) refused)\n",
        "!(test (collapse (map-get (map-from-pairs (superpose (((a 1)) ((a 2))))) a)) (1 2))\n",
        "!(test (let $source (match &self (= (map-remove $map $key) $body) (quote (|-> ($map $key) $body))) (let $remove (eval $source) (map-pairs ($remove &prices pear)))) ((apple 3) (plum 7)))\n",
        "!(test (let $map &prices (let $source (match &self (= (map-remove $map $key) $body) (quote (|-> ($key) $body))) (let $remove (eval $source) (map-pairs ($remove plum))))) ((apple 3) (pear 5)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "datastructures_lib");
}
