/* Purpose: check datastructures fingertree through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/02-datastructures_fingertree.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_datastructures))\n",
        "!(test (ft-to-list (ft-push-front 1 (ft-push-back 3 (ft-push-front 2 (ft-empty))))) (1 2 3))\n",
        "!(test (ft-to-list (ft-from-list (a b c d e f g h i j))) (a b c d e f g h i j))\n",
        "!(test (ft-front (ft-from-list (a b c))) a)\n",
        "!(test (ft-back (ft-from-list (a b c))) c)\n",
        "!(test (let ($x $rest) (ft-pop-front (ft-from-list (a b c))) ($x (ft-to-list $rest))) (a (b c)))\n",
        "!(test (let ($x $rest) (ft-pop-back (ft-from-list (a b c))) ($x (ft-to-list $rest))) (c (a b)))\n",
        "!(test (ft-to-list (ft-from-list (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15))) (1 2 3 4 5 6 7 8 9 10 11 12 13 14 15))\n",
        "!(test (ft-to-list (ft-push-back 9 (ft-push-front 0 (ft-from-list (4 5 6))))) (0 4 5 6 9))\n",
        "!(test (ft-to-list (ft-concat (ft-from-list (1 2 3 4 5)) (ft-from-list (6 7 8 9 10)))) (1 2 3 4 5 6 7 8 9 10))\n",
        "!(test (ft-to-list (ft-concat (ft-empty) (ft-from-list (x y)))) (x y))\n",
        "!(test (ft-to-list (ft-concat (ft-from-list (x y)) (ft-empty))) (x y))\n",
        "!(test (ft-to-list (ft-concat (ft-push-front a (ft-empty)) (ft-from-list (b c d e f g h)))) (a b c d e f g h))\n",
        "!(test (ft-is-empty (ft-empty)) true)\n",
        "!(test (ft-is-empty (ft-push-front 1 (ft-empty))) false)\n",
        "!(test (ft-front (ft-from-list ((nested pair) plain))) (nested pair))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "datastructures_fingertree");
}
