/* Purpose: check decons and substitution through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/19-decons_and_substitution.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (decons-atom (a b c)) (a (b c)))\n",
        "!(test (decons-atom (a)) (a ()))\n",
        "!(test (let ($head $tail) (decons-atom (1 2 3)) (+ $head (car-atom $tail))) 3)\n",
        "!(test (decons (a b c)) (a (b c)))\n",
        "!(test (== (decons (a b c)) (decons-atom (a b c))) true)\n",
        "!(test (let ($head $tail) (decons (a b c)) (cons $head $tail)) (a b c))\n",
        "!(test (decons ((f 1) b)) ((f 1) (b)))\n",
        "!(test (atom-subst 1 $x (foo $x $x)) (foo 1 1))\n",
        "!(test (atom-subst (g 2) $x (foo $x (bar $x))) (foo (g 2) (bar (g 2))))\n",
        "!(test (=alpha (atom-subst 1 $y (foo $x $y)) (foo $a 1)) true)\n",
        "!(test (atom-subst 1 (car-atom ($x)) (foo $x)) (Error (atom-subst 1 (car-atom ($x)) (foo $x)) NoReturn))\n",
        "!(test (atom-subst 1 $x (foo bar)) (foo bar))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "decons_and_substitution");
}
