/* Purpose: check dict lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/12-dict_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_dict))\n",
        "!(bind! &prices (dict-space ((apple 3) (pear 5))))\n",
        "!(test (dict-size &prices) 2)\n",
        "!(test (dict-has &prices apple) true)\n",
        "!(test (dict-has &prices durian) false)\n",
        "!(test (sort-atom (collapse (dict-values &prices))) (3 5))\n",
        "!(test (sort-atom (dict-pairs &prices)) ((apple 3) (pear 5)))\n",
        "!(test (dict-size (dict-put &prices plum 7)) 3)\n",
        "!(test (dict-size &prices) 3)\n",
        "!(test (collapse (match &prices (plum $v) $v)) (7))\n",
        "!(test (dict-size (dict-put &prices apple 9)) 3)\n",
        "!(test (collapse (match &prices (apple $v) $v)) (9))\n",
        "!(test (dict-size (dict-remove &prices pear)) 2)\n",
        "!(test (dict-has &prices pear) false)\n",
        "!(test (dict-size (dict-remove &prices durian)) 2)\n",
        "!(test (collapse (dict-remove-pair &prices apple)) (true))\n",
        "!(test (dict-has &prices apple) false)\n",
        "!(test (collapse (dict-remove-pair &prices apple)) ())\n",
        "!(bind! &stock (dict-space ((apple 12) (pear 12) (plum 4))))\n",
        "!(test (sort-atom (collapse (match &stock ($k 12) $k))) (apple pear))\n",
        "!(test (dict-get &stock apple 0) 12)\n",
        "!(test (dict-get &stock durian 0) 0)\n",
        "!(test (dict-get (dict-update &stock plum (|-> ($v) (+ $v 6))) plum 0) 10)\n",
        "!(test (dict-get (dict-update &stock durian (|-> ($v) (+ $v 6))) durian absent) absent)\n",
        "!(bind! &delivery (dict-space ((pear 20) (fig 2))))\n",
        "!(test (sort-atom (dict-pairs (dict-merge &stock &delivery))) ((apple 12) (fig 2) (pear 20) (plum 10)))\n",
        "!(test (dict-pop &stock fig) 2)\n",
        "!(test (dict-has &stock fig) false)\n",
        "!(test (collapse (dict-pop &stock fig)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "dict_lib");
}
