/* Purpose: check dispatch policies through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-02-changing-the-equations/01-dispatch_policies.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (only-a A) hit)\n",
        "!(test (collapse (only-a B)) ())\n",
        "!(add-atom &metta (dispatch-policy only-a NoMatchEnum NoMatchOriginal))\n",
        "!(test (only-a B) (only-a B))\n",
        "!(remove-atom &metta (dispatch-policy only-a NoMatchEnum NoMatchOriginal))\n",
        "!(test (collapse (only-a B)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "dispatch_policies");
}
