/* Purpose: check doc lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/08-doc_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_doc))\n",
        "(@doc greet (@desc \"Greets somebody by name\"))\n",
        "(= (greet $who) $who)\n",
        "(@doc add-two (@desc \"Adds two numbers\") (@params ((@param \"the first\") (@param \"the second\"))) (@return \"their sum\"))\n",
        "(= (add-two $a $b) (+ $a $b))\n",
        "!(test (get-doc greet) (@doc greet (@desc \"Greets somebody by name\")))\n",
        "!(test (get-doc add-two) (@doc add-two (@desc \"Adds two numbers\") (@params ((@param \"the first\") (@param \"the second\"))) (@return \"their sum\")))\n",
        "!(test (collapse (get-doc greet-nobody)) ())\n",
        "!(test (collapse (get-doc missing)) ())\n",
        "!(test (collapse (undocumented)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "doc_lib");
}
