/* Purpose: check documentation as data through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/10-documentation_as_data.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(@doc twice (@desc \"Doubles a number\") (@params ((@param \"the number\"))) (@return \"twice it\"))\n",
        "(: twice (-> Number Number))\n",
        "(= (twice $x) (* 2 $x))\n",
        "(= (undocumented-here $x) $x)\n",
        "!(test (let $names (collapse (defined-name)) (repr (sort-atom $names))) \"(twice undocumented-here)\")\n",
        "!(test (let $names (collapse (documented)) (repr $names)) \"(twice)\")\n",
        "!(test (let $names (collapse (undocumented-space &self)) (repr $names)) \"(undocumented-here)\")\n",
        "!(test (let $names (collapse (documented-space &self)) (repr $names)) \"(twice)\")\n",
        "!(add-atom &empty (= (f $x) $x))\n",
        "!(test (let $names (collapse (documented-space &empty)) (repr $names)) \"()\")\n",
        "!(test (let $names (collapse (undocumented-space &empty)) (repr $names)) \"(f)\")\n",
        "!(test (get-doc-space &self twice) (@doc twice (@desc \"Doubles a number\") (@params ((@param \"the number\"))) (@return \"twice it\")))\n",
        "!(test (get-doc-atom &self twice) (@doc-formal (@item twice) (@kind function) (@type %Undefined%) (@desc \"Doubles a number\") (@params ((@param (@type %Undefined%) (@desc \"the number\")))) (@return (@type %Undefined%) (@desc \"twice it\"))))\n",
        "!(test (get-doc-single-atom &self twice) (@doc-formal (@item twice) (@kind function) (@type (-> Number Number)) (@desc \"Doubles a number\") (@params ((@param (@type Number) (@desc \"the number\")))) (@return (@type Number) (@desc \"twice it\"))))\n",
        "!(test (== (get-doc-function &self twice (-> Number Number)) (get-doc-single-atom &self twice)) true)\n",
        "!(test (get-doc-function &self twice (-> String String)) (@doc-formal (@item twice) (@kind function) (@type (-> String String)) (@desc \"Doubles a number\") (@params ((@param (@type String) (@desc \"the number\")))) (@return (@type String) (@desc \"twice it\"))))\n",
        "!(test (get-doc-params ((@param \"the number\")) (@return \"twice it\") (Number Number)) (((@param (@type Number) (@desc \"the number\"))) (@return (@type Number) (@desc \"twice it\"))))\n",
        "!(test (get-doc-params () (@return \"nothing to say\") (Bool)) (() (@return (@type Bool) (@desc \"nothing to say\"))))\n",
        "!(test (help! twice) ())\n",
        "!(test (help! undocumented-here) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "documentation_as_data");
}
