/* Purpose: check encoding lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/30-encoding_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_encoding))\n",
        "!(import! &self (library lib_string))\n",
        "!(test (utf8-encode \"hi\") (104 105))\n",
        "!(test (utf8-decode (104 105)) \"hi\")\n",
        "!(test (utf8-encode \"\") ())\n",
        "!(test (utf8-decode ()) \"\")\n",
        "!(test (utf8-encode \"é\") (195 169))\n",
        "!(test (string-length \"é\") 1)\n",
        "!(test (size-atom (utf8-encode \"é\")) 2)\n",
        "!(test (size-atom (utf8-encode \"🙂\")) 4)\n",
        "!(test (string-length \"🙂\") 1)\n",
        "!(test (utf8-decode (utf8-encode \"héllo 🙂\")) \"héllo 🙂\")\n",
        "!(test (hex-encode (255 16 0)) \"ff1000\")\n",
        "!(test (hex-decode \"ff1000\") (255 16 0))\n",
        "!(test (hex-decode \"FF1000\") (255 16 0))\n",
        "!(test (hex-encode ()) \"\")\n",
        "!(test (hex-decode \"\") ())\n",
        "!(test (hex-encode (utf8-encode \"hi\")) \"6869\")\n",
        "!(test (base64-encode standard (104 105)) \"aGk=\")\n",
        "!(test (base64-decode standard \"aGk=\") (104 105))\n",
        "!(test (base64-encode standard (255 254)) \"//4=\")\n",
        "!(test (base64-encode url (255 254)) \"__4\")\n",
        "!(test (base64-decode url (base64-encode url (255 254))) (255 254))\n",
        "!(test (base64-encode standard ()) \"\")\n",
        "!(test (base64-decode standard \"\") ())\n",
        "!(test (base64-decode standard \"//79\") (255 254 253))\n",
        "!(test (base64-decode url \"__79\") (255 254 253))\n",
        "!(test (utf8-decode (base64-decode url (base64-encode url (utf8-encode \"héllo\")))) \"héllo\")\n",
        "!(test (base64-encode standard (hex-decode \"6869\")) \"aGk=\")\n",
        "!(test (if-error (catch (hex-decode \"abc\")) refused fine) refused)\n",
        "!(test (if-error (catch (hex-decode \"zz\")) refused fine) refused)\n",
        "!(test (if-error (catch (utf8-decode (255))) refused fine) refused)\n",
        "!(test (if-error (catch (utf8-decode (195))) refused fine) refused)\n",
        "!(test (if-error (catch (base64-decode standard \"not base64!\")) refused fine) refused)\n",
        "!(test (if-error (catch (base64-encode nosuch (1))) refused fine) refused)\n",
        "!(test (if-error (catch (hex-encode (256))) refused fine) refused)\n",
        "!(test (if-error (catch (base64-encode standard (string-codes \"🙂\"))) refused fine) refused)\n",
        "!(test (hex-encode (string-codes \"é\")) \"e9\")\n",
        "!(test (hex-encode (utf8-encode \"é\")) \"c3a9\")\n",
        "!(test (if-error (catch (utf8-decode (1 two))) refused fine) refused)\n",
        "!(test (if-error (catch (hex-decode 7)) refused fine) refused)\n",
        "!(test (let $recipe (match &self (= (hex-encode $bytes) $body) (quote (|-> ($bytes) $body))) (let $format (eval $recipe) ($format (0 255)))) \"00ff\")\n",
        "!(test (collapse (hex-encode (superpose (() (0 255))))) (\"\" \"00ff\"))\n",
        "!(test (hex-encode (utf8-encode (string-from-codes (97 0 98)))) \"610062\")\n",
        "!(test (if-error (catch (hex-decode \"𝟢0\")) refused fine) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "encoding_lib");
}
