/* Purpose: check engine surface through the embedded source interface.
 * Source: examples/ch09-types/15-engine_surface.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (get-type if) (-> Bool Atom Atom $t))\n",
        "!(test (get-type let) (-> Atom %Undefined% Atom %Undefined%))\n",
        "!(test (get-type chain) (-> Atom Variable Atom %Undefined%))\n",
        "!(test (get-type quote) (-> Atom Atom))\n",
        "!(test (get-type collapse) (-> Atom Atom))\n",
        "!(test (get-type superpose) (-> Expression %Undefined%))\n",
        "!(test (get-type match) (-> SpaceType Atom Atom %Undefined%))\n",
        "!(test (collapse (get-type map-atom)) ((-> Expression Variable Atom Expression) (-> Expression Expression Expression)))\n",
        "!(test (get-type car-atom) (-> Expression %Undefined%))\n",
        "!(test (get-type cdr-atom) (-> Expression Expression))\n",
        "!(test (get-type cons-atom) (-> %Undefined% %Undefined% Atom))\n",
        "!(test (get-type size-atom) (-> Expression Number))\n",
        "!(test (get-type index-atom) (-> %Undefined% Number Atom))\n",
        "!(test (get-type sort-atom) (-> %Undefined% Expression))\n",
        "!(test (get-type is-var) (-> Atom Bool))\n",
        "!(test (get-type repr) (-> %Undefined% String))\n",
        "!(test (get-type current-time) (-> Number))\n",
        "!(test (get-type new-state) (-> $t (StateMonad $t)))\n",
        "!(test (get-type change-state!) (-> (StateMonad $t) $t Bool))\n",
        "!(test (get-type get-state) (-> (StateMonad $t) $t))\n",
        "!(test (get-type (new-state 5)) (StateMonad Number))\n",
        "!(test (get-type (new-state \"hi\")) (StateMonad String))\n",
        "(: program-own-type MyType)\n",
        "!(test (collapse (match &self (: $n $t) $n)) (program-own-type))\n",
        "(: car-atom MyOverride)\n",
        "!(test (car-atom (a b)) a)\n",
        "!(test (collapse (get-type car-atom)) (MyOverride (-> Expression %Undefined%)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "engine_surface");
}
