/* Purpose: check evalc through the embedded source interface.
 * Source: examples/ch19-spaces-backed-by-anything/19-01-spaces-of-your-own/05-evalc.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(bind! &metric (new-space))\n",
        "!(add-atom &metric (= (distance $x) (* $x 1000)))\n",
        "(= (distance $x) (* $x 5280))\n",
        "!(test (distance 2) 10560)\n",
        "!(test (evalc (distance 2) &metric) 2000)\n",
        "!(test (evalc (+ 5 5) &self) 10)\n",
        "!(test (eval (+ 5 5)) 10)\n",
        "!(test (evalc (distance (+ 1 1)) &metric) 2000)\n",
        "!(test (context-space) &self)\n",
        "!(test (evalc (context-space) &metric) &metric)\n",
        "(= (preferred-space) &metric)\n",
        "!(test (evalc (distance 2) (preferred-space)) 2000)\n",
        "!(test (repr (catch (evalc (distance 2) 7))) \"(Error (type_error SpaceType 7) (context evalc invalid MeTTa operation argument))\")\n",
        "!(remove-atom &metric (= (distance $x) (* $x 1000)))\n",
        "!(test (evalc (distance 2) &metric) 10560)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "evalc");
}
