/* Purpose: check event catalog through the embedded source interface.
 * Source: examples/ch16-events-and-standing-queries/01-event_catalog.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (match &metta (vocabulary delivery $a $b $c) ($a $b $c)) (at-most-once at-least-once per-write-exactly))\n",
        "!(test (match &metta (vocabulary event-order $a $b) ($a $b)) (ordered unordered))\n",
        "!(test (match &metta (kind events $ctx $delivery $order) $delivery) (one-of delivery))\n",
        "!(test (if-error (catch (add-atom &metta (events &feed eventually))) refused admitted) refused)\n",
        "!(add-atom &native-events (reading 1))\n",
        "!(test (collapse (match &metta (events &native-events $d $o) declared)) ())\n",
        "!(test (match &metta (vocabulary agenda-policy $a $b $c $d $e) ($a $b $c $d $e)) (declaration recency specificity priority user))\n",
        "!(test (match &metta (policy reaction-order $knob $default) ($knob $default)) (agenda declaration))\n",
        "!(test (match &metta (kind agenda $ctx $policy $fn) $policy) (one-of agenda-policy))\n",
        "!(test (match &metta (kind on $ctx $pattern $op $priority) $priority) (optional integer))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "event_catalog");
}
