/* Purpose: check exp and seeded randomness through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-03-the-number-library/03-exp_and_seeded_randomness.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (exp 0) 1.0)\n",
        "!(test (exp 1) 2.718281828459045)\n",
        "!(test (== (exp 2) (exp-math 2)) true)\n",
        "!(test (== (with-seed 42 (random-int 0 100)) (with-seed 42 (random-int 0 100))) true)\n",
        "!(test (== (with-seed 7 (collapse (superpose ((random-int 0 100) (random-int 0 100))))) (with-seed 7 (collapse (superpose ((random-int 0 100) (random-int 0 100)))))) true)\n",
        "!(test (== (with-seed 42 (random-int 0 100)) (with-seed 43 (random-int 0 100))) false)\n",
        "!(test (== (with-seed 5 (random-float 0.0 1.0)) (with-seed 5 (random-float 0.0 1.0))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "exp_and_seeded_randomness");
}
