/* Purpose: check factorial through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/01-factorial.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (facF $n) (if (== $n 0) 1 (* $n (facF (- $n 1)))))\n",
        "!(test (facF 10) 3628800)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "factorial");
}
