/* Purpose: check fib through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/02-fib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (fib $N) (if (< $N 2) $N (+ (fib (- $N 1)) (fib (- $N 2)))))\n",
        "!(test (with-pragma! ((max-stack-depth 100000000)) (fib 30)) 832040)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "fib");
}
