/* Purpose: check fibsmart through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/03-fibsmart.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (fib-tr $n $a $b) (if (== $n 0) $a (fib-tr (- $n 1) $b (+ $a $b))))\n",
        "(= (fib $n) (fib-tr $n 0 1))\n",
        "!(test (fib 100) 354224848179261915075)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "fibsmart");
}
