/* Purpose: check fibsmartimport through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/04-fibsmartimport.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self fixtures/performance/fibsmart)\n",
        "!(test (fib 100) 354224848179261915075)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "fibsmartimport");
}
