/* Purpose: check fingertree internals through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/15-fingertree_internals.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_datastructures))\n",
        "!(test (ft-to-list (FTSingle 1)) (1))\n",
        "!(test (ft-to-list (FTDeep (1 2) FTEmpty (3 4))) (1 2 3 4))\n",
        "!(test (ft-is-empty FTEmpty) true)\n",
        "!(test (ft-is-empty (FTSingle 1)) false)\n",
        "!(test (ft-node-digit (FTNode2 a b)) (a b))\n",
        "!(test (ft-node-digit (FTNode3 a b c)) (a b c))\n",
        "!(test (ft-borrow-l FTEmpty (a)) (FTSingle a))\n",
        "!(test (ft-borrow-l FTEmpty (a b)) (FTDeep (a) FTEmpty (b)))\n",
        "!(test (ft-borrow-l FTEmpty (a b c d)) (FTDeep (a b) FTEmpty (c d)))\n",
        "!(test (ft-borrow-l (FTSingle (FTNode2 a b)) (c)) (FTDeep (a b) FTEmpty (c)))\n",
        "!(test (ft-borrow-r (a) FTEmpty) (FTSingle a))\n",
        "!(test (ft-borrow-r (a b) FTEmpty) (FTDeep (a) FTEmpty (b)))\n",
        "!(test (ft-borrow-r (a) (FTSingle (FTNode2 b c))) (FTDeep (a) FTEmpty (b c)))\n",
        "!(test (ft-to-list (ft-borrow-l (FTSingle (FTNode3 a b c)) (d))) (a b c d))\n",
        "!(test (ft-nodes (1 2)) ((FTNode2 1 2)))\n",
        "!(test (ft-nodes (1 2 3)) ((FTNode3 1 2 3)))\n",
        "!(test (ft-nodes (1 2 3 4)) ((FTNode2 1 2) (FTNode2 3 4)))\n",
        "!(test (ft-nodes (1 2 3 4 5)) ((FTNode3 1 2 3) (FTNode2 4 5)))\n",
        "!(test (ft-nodes (1 2 3 4 5 6)) ((FTNode3 1 2 3) (FTNode3 4 5 6)))\n",
        "!(test (ft-to-list (ft-push-list-front (1 2) (ft-from-list (3 4)))) (1 2 3 4))\n",
        "!(test (ft-to-list (ft-push-list-back (1 2) (ft-from-list (3 4)))) (3 4 1 2))\n",
        "!(test (ft-to-list (ft-push-list-front () (ft-from-list (3 4)))) (3 4))\n",
        "!(test (ft-to-list (ft-push-list-back () (ft-from-list (3 4)))) (3 4))\n",
        "!(test (ft-to-list (ft-app3 (ft-from-list (1 2)) (7 8) (ft-from-list (3 4)))) (1 2 7 8 3 4))\n",
        "!(test (ft-to-list (ft-app3 FTEmpty (7 8) (ft-from-list (3 4)))) (7 8 3 4))\n",
        "!(test (ft-to-list (ft-app3 (ft-from-list (1 2)) () FTEmpty)) (1 2))\n",
        "!(test (ft-to-list (ft-app3 FTEmpty () FTEmpty)) ())\n",
        "!(test (== (ft-to-list (ft-concat (ft-from-list (1 2)) (ft-from-list (3 4)))) (ft-to-list (ft-app3 (ft-from-list (1 2)) () (ft-from-list (3 4))))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "fingertree_internals");
}
