/* Purpose: check foldall through the embedded source interface.
 * Source: examples/ch07-control-flow/07-04-bounded-and-committed-searches/05-foldall.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f) 2)\n",
        "(= (f) 3)\n",
        "(= (g 1) 2)\n",
        "(= (g 2) 3)\n",
        "(= (merge $A $B) (+ $A $B))\n",
        "!(test (foldall merge (f) 0) 5)\n",
        "!(test (foldall merge (g $x) 0) 5)\n",
        "!(test (let $agglambda (|-> ($x $y) (+ $x $y)) (foldall $agglambda (f) 0)) 5)\n",
        "!(test (let $agglambda (|-> ($x $y) (+ $x $y)) (foldall $agglambda (g $z) 0)) 5)\n",
        "!(test (let $agglambda (|-> ($x $y) (+ $x $y)) (foldall $agglambda (g $z) 0)) 5)\n",
        "!(test (let* (($agglambda (|-> ($x $y) (+ $x $y))) ($genlambda (|-> ($z) (f)))) (foldall $agglambda ($genlambda $x) 0)) 5)\n",
        "!(test (let* (($agglambda (|-> ($x $y) (+ $x $y))) ($genlambda (|-> ($z) (g $z)))) (foldall $agglambda ($genlambda $x) 0)) 5)\n",
        "!(test (foldall (|-> ($x $y) (+ $x $y)) ((|-> ($z) (g $z)) $w) 0) 5)\n",
        "!(test (foldall (if true (let $f (|-> ($x $y) (+ $x $y)) $f) (empty)) ((|-> ($z) (g $z)) $w) 0) 5)\n",
        "!(test (foldall (if true (let $f (|-> ($x $y) (+ $x $y)) $f) (empty)) ((|-> ($z) (* 2 (g $z))) $w) 0) 10)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "foldall");
}
