/* Purpose: check foldallmatch through the embedded source interface.
 * Source: examples/ch07-control-flow/07-04-bounded-and-committed-searches/06-foldallmatch.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(kb 1)\n",
        "(kb 2)\n",
        "!(test (foldall + (match &self (kb $n) (+ $n 1)) 0) 5)\n",
        "(= (f) 1)\n",
        "(= (f) 2)\n",
        "!(test (foldall + (let $x (f) (+ 1 $x)) 0) 5)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "foldallmatch");
}
