/* Purpose: check forall through the embedded source interface.
 * Source: examples/ch07-control-flow/07-04-bounded-and-committed-searches/01-forall.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f) 1)\n",
        "(= (f) 2)\n",
        "(= (g 1) 1)\n",
        "(= (g 2) 2)\n",
        "(= (P $X) (< $X 2))\n",
        "!(test (forall (f) P) false)\n",
        "!(test (forall (g $x) P) false)\n",
        "!(test (let $genlambda (|-> ($x) (g $x)) (forall ($genlambda $z) P)) false)\n",
        "!(test (let $checklambda (|-> ($v) (< $v 2)) (forall (g 2) $checklambda)) false)\n",
        "!(test (let $checklambda (|-> ($v) (< $v 2)) (forall (g 1) $checklambda)) true)\n",
        "!(test (let $checklambda (|-> ($v) (< $v 2)) (forall (g 2) $checklambda)) false)\n",
        "!(test (let* (($checklambda (|-> ($v) (< $v 2))) ($genlambda (|-> ($x) (g $x)))) (forall ($genlambda $z) $checklambda)) false)\n",
        "!(test (forall ((|-> ($x) (g $x)) $z) (|-> ($v) (< $v 2))) false)\n",
        "!(test (forall ((|-> ($x) (g $x)) $z) (|-> ($v) (< $v 20))) true)\n",
        "!(test (forall ((|-> ($x) (g $x)) $z) (if true (|-> ($v) (< $v 2)) 42)) false)\n",
        "!(test (forall ((|-> ($x) (g $x)) $z) (if true (|-> ($v) (< $v 20)) 42)) true)\n",
        "!(test (forall ((|-> ($x) (* 100 (g $x))) $z) (if true (|-> ($v) (< $v 20)) 42)) false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "forall");
}
