/* Purpose: check foreign rules through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-03-prolog-underneath/03-foreign_rules.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_import))\n",
        "!(import_prolog_functions_from_file \"./fixtures/prolog/rule_provider.pl\" ())\n",
        "!(add-atom &rule_demo (= (fdouble $x) (* 2 $x)))\n",
        "!(test (metta (fdouble 21) %Undefined% &rule_demo) 42)\n",
        "!(add-atom &rule_demo (= (fpick) one))\n",
        "!(add-atom &rule_demo (= (fpick) two))\n",
        "!(test (sort-atom (collapse (metta (fpick) %Undefined% &rule_demo))) (one two))\n",
        "!(add-atom &rule_demo (= (fplain) settled))\n",
        "!(test (metta (fplain) %Undefined% &rule_demo) settled)\n",
        "!(add-atom &rule_demo (= (fnest) (+ 1 (* 2 3))))\n",
        "!(test (metta (fnest) %Undefined% &rule_demo) 7)\n",
        "!(add-atom &rule_demo (= (ffact $x) (if (> $x 0) (* $x (ffact (- $x 1))) 1)))\n",
        "!(test (metta (ffact 5) %Undefined% &rule_demo) 120)\n",
        "!(add-atom &rule_demo (edge a b))\n",
        "!(test (collapse (match &rule_demo (edge $x $y) ($x $y))) ((a b)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "foreign_rules");
}
