/* Purpose: check functiontypes through the embedded source interface.
 * Source: examples/ch09-types/03-functiontypes.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: wu1 (-> Number Atom %Undefined%))\n",
        "(= (wu1 $a $b) (42 $a $b))\n",
        "(: wu2 (-> Number Number Number))\n",
        "(= (wu2 $a $b) (+ $a $b))\n",
        "(: wu3 (-> Number Number %Undefined%))\n",
        "(= (wu3 $a $b) (if (< $a 10) (+ $a $b) (a list not a number)))\n",
        "!(test (wu1 (+ 2 4) (+ 4 2)) (noeval (42 6 (+ 4 2))))\n",
        "(: wu1b (-> Number Atom Atom))\n",
        "(= (wu1b $a $b) (42 $a $b))\n",
        "!(test (wu1b (+ 2 4) (+ 4 2)) (noeval (42 6 (+ 4 2))))\n",
        "!(test (wu2 (+ 2 4) (+ 4 2)) 12)\n",
        "!(test (wu3 42 0) (a list not a number))\n",
        "!(test (wu3 2 0) 2)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "functiontypes");
}
