/* Purpose: check functionhead2 through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/07-functionhead2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &metta (dispatch-policy small NoMatchEnum NoMatchFail))\n",
        "(= (living garfield) true)\n",
        "(= (being garfield) true)\n",
        "(= (small garfield) true)\n",
        "(= (living snoopy) true)\n",
        "(= (being snoopy) true)\n",
        "(= (being roomba) true)\n",
        "(= (small roomba) true)\n",
        "(= (living cat42) true)\n",
        "(= (being cat42) true)\n",
        "(= (small cat42) true)\n",
        "(= (only $C $X) (let $constraint $C $X))\n",
        "(= (animal $X) (only ((living $X) (being $X)) $X))\n",
        "(= (cat $A) (let $A (animal $X) (only (small $X) $X)))\n",
        "!(test (msort (collapse (cat $X))) (cat42 garfield))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "functionhead2");
}
