/* Purpose: check functionremovalspec through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-02-changing-the-equations/03-functionremovalspec.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (g $x) (+ $x 1))\n",
        "(= (f $g) ($g 1))\n",
        "(= (f $g) ($g 2))\n",
        "!(test (collapse (f g)) (2 3))\n",
        "!(remove-atom &self (= (f $g) ($g 1)))\n",
        "!(test (f g) 3)\n",
        "!(add-atom &self (= (f $g) ($g 1)))\n",
        "!(test (f g) (3 2))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "functionremovalspec");
}
