/* Purpose: check functionhead through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/06-functionhead.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (myfunc $A $B) (append (append (42) $A) $B))\n",
        "(= (h_old $A $C) (if (= $A (myfunc (10) $B)) ($B $C) (empty)))\n",
        "(= (h $A $C) (let $A (myfunc (10) $B) ($B $C)))\n",
        "!(test (h (42 10 40) 42000) ((40) 42000))\n",
        "!(test (h_old (42 10 40) 42000) ((40) 42000))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "functionhead");
}
