/* Purpose: check functionhead3 through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/08-functionhead3.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (in $x $L) (let true (is-member $x $L) $x))\n",
        "(= (myplus $A $B) (let $A (in $X (1 2 3)) (let $B (in $Y (2 3)) (in (+ $X $Y) (3 4 5)))))\n",
        "!(test (collapse (myplus 1 3)) (4))\n",
        "!(test (collapse (myplus 3 3)) ())\n",
        "!(test (collapse (myplus 3 4)) ())\n",
        "!(test (collapse (myplus $x 3)) (4 5))\n",
        "!(test (collapse (myplus $x $y)) (3 4 4 5 5))\n",
        "!(test (collapse (let true (> (myplus $x 2) 3) $x)) (2 3))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "functionhead3");
}
