/* Purpose: check git import through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/06-git_import.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_import))\n",
        "!(import_prolog_functions_from_file \"./fixtures/modules/git_fixture.pl\" (git_fixture_url))\n",
        "!(git-import! (git_fixture_url \"./ai-tmp/repos\") \"\" \"./ai-tmp/repos\")\n",
        "!(import! &self (library metta_fixture_lib fixture))\n",
        "!(test (fixture-answer 14) 42)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "git_import");
}
