/* Purpose: check he atomspace through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/08-he_atomspace.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "!(add-atom &self (= (addnormal) (+ 1 3)))\n",
        "!(add-reduct &self (= (addreduct) (+ 1 3)))\n",
        "!(test (repr (match &self (= (addnormal) $X) $X)) \"(+ 1 3)\")\n",
        "!(test (repr (match &self (= (addreduct) $X) $X)) \"(4)\")\n",
        "!(get-type 1)\n",
        "(: a A)\n",
        "!(test (get-type-space &self a) A)\n",
        "(hello world)\n",
        "!(test (unify &self (hello world) Yes No) Yes)\n",
        "!(test (unify &self (hello dream) Yes No) No)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_atomspace");
}
