/* Purpose: check he assert through the embedded source interface.
 * Source: examples/ch12-testing/01-he_assert.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "!(test (assertEqual (+ 1 2) (- 6 3)) true)\n",
        "!(test (assertAlphaEqual (h $x $y) (h $a $b)) true)\n",
        "!(test (assertAlphaEqual (quote (+ $x $y)) (quote (+ $a $b))) true)\n",
        "!(test (assertEqualToResult (+ 1 2) 3) true)\n",
        "!(test (collapse (assertEqualToResult (superpose (1 1)) 1)) (true true))\n",
        "(= (adder) ($x))\n",
        "!(test (assertAlphaEqualToResult (adder) ($y)) true)\n",
        "!(test (assertIncludes (superpose (1 2 3)) (2)) true)\n",
        "!(test (assertIncludes (superpose (1 2 3)) (2 3)) true)\n",
        "!(test (assertEqualMsg (+ 1 2) (- 6 3) \"sums differ\") true)\n",
        "!(test (assertAlphaEqualMsg (h $x $y) (h $a $b) \"not alpha equal\") true)\n",
        "!(test (assertEqualToResultMsg (+ 1 2) (3) \"not the expected result\") true)\n",
        "!(test (assertAlphaEqualToResultMsg (adder) (($y)) \"not alpha equal\") true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_assert");
}
