/* Purpose: check he error through the embedded source interface.
 * Source: examples/ch10-errors-and-refusals/01-he_error.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "!(test (let $result (catch (+ 40 2)) (if-error $result Error $result)) 42)\n",
        "(: a String)\n",
        "!(test (if-error (+ 40 a) Error fine) Error)\n",
        "!(test (if-error (+ 40 undeclared-operand) Error fine) Error)\n",
        "!(test (let $result (catch (+ $left $right)) (if-error $result Error $result)) Error)\n",
        "!(test (if-error (/ 40 0) Error fine) Error)\n",
        "!(test (if-error (Error 5 BadType) \"Error!\" \"No error\") \"Error!\")\n",
        "!(test (return-on-error (Error 5 BadType) 6) (Error 5 BadType))\n",
        "!(test (return-on-error 5 6) 6)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_error");
}
