/* Purpose: check he equalreduct through the embedded source interface.
 * Source: examples/ch12-testing/02-he_equalreduct.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "(= (add 1 2) 3)\n",
        "!(test (id 5) 5)\n",
        "!(test (=alpha (Father $X) (Father $Y)) true)\n",
        "!(test (=alpha (Father $X) (Son $X)) false)\n",
        "!(test (if-equal 1 1 \"Equal\" \"Not Equal\") \"Equal\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_equalreduct");
}
