/* Purpose: check he math through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/10-he_math.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (pow-math 2 3) 8)\n",
        "!(test (isnan-math (sqrt-math -1)) true)\n",
        "!(test (isinf-math (pow-math 0.0 -1.0)) true)\n",
        "!(test (pow-math 1 2147483648.0) 1)\n",
        "!(test (sqrt-math 9) 3.0)\n",
        "!(test (abs-math -5) 5)\n",
        "!(test (log-math 10 100) 2.0)\n",
        "!(test (trunc-math 5.6) 5)\n",
        "!(test (ceil-math 5.2) 6)\n",
        "!(test (floor-math 5.8) 5)\n",
        "!(test (round-math 5.4) 5)\n",
        "!(test (round-math 5.6) 6)\n",
        "!(test (sin-math 0) 0.0)\n",
        "!(test (asin-math 0) 0.0)\n",
        "!(test (cos-math 0) 1.0)\n",
        "!(test (acos-math 1) 0.0)\n",
        "!(test (tan-math 0) 0.0)\n",
        "!(test (atan-math 0) 0.0)\n",
        "!(test (isnan-math 0.0) false)\n",
        "!(test (isinf-math 0.0) false)\n",
        "!(test (min-atom (2 6 7 4 9 3)) 2)\n",
        "!(test (max-atom (2 6 7 4 9 3)) 9)\n",
        "!(test (isinf-math inf) true)\n",
        "!(test (isnan-math nan) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_math");
}
