/* Purpose: check he minimalmetta through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/05-he_minimalmetta.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "(= (div $x $y $accum) (chain (eval (- $x $y)) $r1 (chain (eval (< $r1 0)) $r2 (chain (unify $r2 true $accum (chain (eval (+ 1 $accum)) $inc (chain (eval (div $r1 $y $inc)) $r4 $r4))) $r3 $r3))))\n",
        "!(test (with-pragma! ((max-stack-depth 1000000)) (chain (eval (div 350000 5 0)) $rr $rr)) 70000)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_minimalmetta");
}
