/* Purpose: check he quoting through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/07-he_quoting.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "!(test (quote (+ 1 2)) (quote (+ 1 2)))\n",
        "!(test (eval (+ 1 2)) 3)\n",
        "!(test (unquote (quote (+ 1 2))) 3)\n",
        "!(test (repr (unquote 42)) \"(unquote 42)\")\n",
        "!(test (noreduce-eq (+ 1 2) (+ 1 2)) true)\n",
        "!(test (noreduce-eq (+ 1 2) 3) false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_quoting");
}
