/* Purpose: check he types through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/09-he_types.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "!(test (is-function (-> Atom Atom)) true)\n",
        "!(test (is-function Atom) false)\n",
        "(: type1 Type)\n",
        "(: A type1)\n",
        "!(test (type-cast A type1 &self) A)\n",
        "!(test (type-cast 1 type1 &self) (Error 1 BadType))\n",
        "!(test (type-cast A Symbol &self) A)\n",
        "!(test (type-cast 1 Number &self) 1)\n",
        "!(test (type-cast B type1 &self) (Error B BadType))\n",
        "!(test (match-types Atom Atom \"Matched!\" \"Didn't match\") \"Matched!\")\n",
        "!(test (match-types Atom Number \"Matched!\" \"Didn't match\") \"Didn't match\")\n",
        "!(test (match-types Bool Number \"Matched!\" \"Didn't match\") \"Didn't match\")\n",
        "!(test (match-types (List $x) (List Number) \"Matched!\" \"Didn't match\") \"Didn't match\")\n",
        "!(test (first-from-pair (A B)) A)\n",
        "!(test (second-from-pair (A B)) B)\n",
        "!(test (match-type-or true Number Bool) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "he_types");
}
