/* Purpose: check holfunctions through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/02-holfunctions.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f1a) (foldl-atom (1 2 3 4) 0 $acc $x (+ $acc $x)))\n",
        "(= (f2a) (map-atom (1 2 3) $x (+ $x 1)))\n",
        "(= (f3a) (filter-atom (1 2 3 4 5) $x (> $x 3)))\n",
        "(= (foldfun $a $b) (+ $a $b))\n",
        "(= (mapfun $a) (+ $a 1))\n",
        "(= (filterfun $x) (> $x 3))\n",
        "(= (f1b) (foldl-atom (1 2 3 4) 0 foldfun))\n",
        "(= (f2b) (map-atom (1 2 3) mapfun))\n",
        "(= (f3b) (filter-atom (1 2 3 4 5) filterfun))\n",
        "!(test (f1a) 10)\n",
        "!(test (f2a) (2 3 4))\n",
        "!(test (f3a) (4 5))\n",
        "!(test (f1b) 10)\n",
        "!(test (f2b) (2 3 4))\n",
        "!(test (f3b) (4 5))\n",
        "(= (foldfun2 $a $b) (append $a $b))\n",
        "!(foldl-atom ((1 2) (3 4) (5 6)) () $acc $x (append $acc $x))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "holfunctions");
}
