/* Purpose: check holfunctions intrinsicop through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/03-holfunctions_intrinsicop.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (mymap $f ()) ())\n",
        "(= (mymap $f (cons $x $xs)) (let $head ($f $x) (let $rest (mymap $f $xs) (cons $head $rest))))\n",
        "(= (eq $a $b) (== $a $b))\n",
        "!(test (mymap (== 1) (1 2 3)) (mymap (eq 1) (1 2 3)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "holfunctions_intrinsicop");
}
