/* Purpose: check http lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/38-http_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_http))\n",
        "!(import! &self (library lib_encoding))\n",
        "(: library-http (-> Expression Expression))\n",
        "(= (library-http (http-request $method \"/\" $target $fields $body)) (http-response 200 ((\"X-Reply\" \"one\") (\"X-Reply\" \"two\")) (0 128 255)))\n",
        "(= (library-http (http-request $method \"/echo\" $target $fields $body)) (http-response 201 ((\"Content-Type\" \"text/plain; charset=UTF-8\") (\"X-Method\" (repr $method)) (\"X-Target\" $target)) $body))\n",
        "(= (library-http (http-request $method \"/absent\" $target $fields $body)) (http-response 404 () ()))\n",
        "(= (library-http (http-request $method \"/redirect\" $target $fields $body)) (http-response 307 ((\"Location\" \"/\")) ()))\n",
        "(= (library-http (http-request $method \"/empty\" $target $fields $body)) (empty))\n",
        "(= (library-http (http-request $method \"/broken\" $target $fields $body)) (broken-response 7))\n",
        "(: read-http (-> Expression Expression))\n",
        "(= (read-http (http-response $status $fields $handle)) (file-read-bytes! $handle))\n",
        "(: ping-http (-> Expression Expression))\n",
        "(= (ping-http $server) (http-request! get (http-server-url $server) ()))\n",
        "!(test (http-methods) (delete get head post put patch options))\n",
        "!(bind! &server (http-server-start! \"127.0.0.1\" 0 library-http ((workers 2))))\n",
        "!(bind! &url (http-server-url &server))\n",
        "!(bind! &echo (string-join \"\" (&url \"echo?q=one%20two\")))\n",
        "!(bind! &response (http-request! get &url ((timeout 5))))\n",
        "!(test (let (http-response $code $fields $bytes) &response $code) 200)\n",
        "!(test (let (http-response $code $fields $bytes) &response $bytes) (0 128 255))\n",
        "!(test (let (http-response $code $fields $bytes) &response (http-header $fields \"Content-Type\")) \"application/octet-stream\")\n",
        "!(test (let (http-response $code $fields $bytes) &response (http-header $fields \"CONTENT-LENGTH\")) 3)\n",
        "!(test (let (http-response $code $fields $bytes) &response (collapse (http-header $fields \"x-reply\"))) (\"one\" \"two\"))\n",
        "!(test (let (http-response $code $fields $bytes) &response (collapse (http-header $fields \"missing\"))) ())\n",
        "!(bind! &head (http-request! head &url ()))\n",
        "!(test (let (http-response $code $fields $bytes) &head $code) 200)\n",
        "!(test (let (http-response $code $fields $bytes) &head $bytes) ())\n",
        "!(test (let (http-response $code $fields $bytes) &head (http-header $fields \"content-length\")) 3)\n",
        "!(bind! &posted (http-request! post &echo ((body \"text/plain; charset=UTF-8\" (utf8-encode \"aπ🙂\")) (header \"X-Input\" \"one\") (header \"X-Input\" \"two\"))))\n",
        "!(test (let (http-response $code $fields $bytes) &posted $code) 201)\n",
        "!(test (let (http-response $code $fields $bytes) &posted (utf8-decode $bytes)) \"aπ🙂\")\n",
        "!(test (let (http-response $code $fields $bytes) &posted (http-header $fields \"x-method\")) \"post\")\n",
        "!(test (let (http-response $code $fields $bytes) &posted (http-header $fields \"x-target\")) \"/echo?q=one%20two\")\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! put &echo ()) (http-header $fields \"x-method\")) \"put\")\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! patch &echo ()) (http-header $fields \"x-method\")) \"patch\")\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! delete &echo ()) (http-header $fields \"x-method\")) \"delete\")\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! options &echo ()) (http-header $fields \"x-method\")) \"options\")\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! get (string-join \"\" (&url \"absent\")) ()) $code) 404)\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! get (string-join \"\" (&url \"empty\")) ()) $code) 404)\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! get (string-join \"\" (&url \"broken\")) ()) $code) 500)\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! get (string-join \"\" (&url \"redirect\")) ()) $code) 307)\n",
        "!(test (let (http-response $code $fields $bytes) (http-request! get (string-join \"\" (&url \"redirect\")) ((redirect true))) $bytes) (0 128 255))\n",
        "!(bind! &stream (http-open! get &url ()))\n",
        "!(bind! &handle (let (http-response $code $fields $handle) &stream $handle))\n",
        "!(test (file-read-bytes! &handle 2) (0 128))\n",
        "!(test (file-read-bytes! &handle) (255))\n",
        "!(test (file-close! &handle) true)\n",
        "!(test (file-close! &handle) true)\n",
        "!(test (with-http get &url () read-http) (0 128 255))\n",
        "!(test (let (http-response $status $fields $body) (with-http-server \"127.0.0.1\" 0 library-http ((workers 1)) ping-http) $status) 200)\n",
        "!(test (if-error (catch (http-request! invented &url ())) refused fine) refused)\n",
        "!(test (if-error (catch (http-request! get \"file:///etc/passwd\" ())) refused fine) refused)\n",
        "!(test (if-error (catch (http-request! get &url ((header \"bad:name\" \"x\")))) refused fine) refused)\n",
        "!(test (if-error (catch (http-request! get &url ((header \"X-Input\" \"a\\nb\")))) refused fine) refused)\n",
        "!(test (if-error (catch (http-request! post &url ((body \"application/octet-stream\" (256))))) refused fine) refused)\n",
        "!(test (if-error (catch (http-request! get &url ((timeout 1) (timeout 2)))) refused fine) refused)\n",
        "!(test (if-error (catch (http-request! get &url ((header \"Content-Length\" \"3\")))) refused fine) refused)\n",
        "!(test (if-error (catch (http-server-start! \"127.0.0.1\" 0 library-http ((workers 0)))) refused fine) refused)\n",
        "!(test (if-error (catch (transaction (http-server-start! \"127.0.0.1\" 0 library-http ()))) refused fine) refused)\n",
        "!(test (if-error (catch (transaction (http-server-stop! &server))) refused fine) refused)\n",
        "!(test (http-server-stop! &server) true)\n",
        "!(test (http-server-stop! &server) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "http_lib");
}
