/* Purpose: check hyperpose primes through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/03-hyperpose_primes.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (find-divisor $n $test-divisor) (if (> (* $test-divisor $test-divisor) $n) $n (if (== 0 (% $n $test-divisor)) $test-divisor (find-divisor $n (+ $test-divisor 1)))))\n",
        "(= (prime? $n) (== $n (find-divisor $n 2)))\n",
        "!(test (msort (collapse (let $xs (3 1 2) (hyperpose $xs)))) (1 2 3))\n",
        "!(test (collapse (hyperpose ((prime? 5353725700019) (prime? 5378181100003) (prime? 5421844300001) (prime? 5473443100001)))) (true true true true))\n",
        "!(test (once (hyperpose ((prime? 535372570000000063) (prime? 537818110000000001) (prime? 5421844300001) (prime? 547344310000000013)))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "hyperpose_primes");
}
