/* Purpose: check if2 through the embedded source interface.
 * Source: examples/ch07-control-flow/07-01-if-and-booleans/03-if2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (if (is-var a) (() (+ 1 1)) (+ 2 2)) 4)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "if2");
}
