/* Purpose: check if4 through the embedded source interface.
 * Source: examples/ch07-control-flow/07-01-if-and-booleans/05-if4.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (if (if (== 42 42) true false) (if true 42 lol) (+ 2 2)) 42)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "if4");
}
