/* Purpose: check if branch binding through the embedded source interface.
 * Source: examples/ch07-control-flow/07-01-if-and-booleans/06-if_branch_binding.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (pick-else $a $b) (if (< $a $a) (let* (($c $a)) $a) $b))\n",
        "!(test (pick-else 1 2) 2)\n",
        "(= (pick-then $a $b) (if (> $a 0) (let* (($c $a)) $a) $b))\n",
        "!(test (pick-then 1 2) 1)\n",
        "(= (case-else $a $b) (case (< $a $a) ((true (let* (($c $a)) $a)) (false $b))))\n",
        "!(test (case-else 3 4) 4)\n",
        "(= (both $a $b) (if (> $a $b) (let* (($c 1)) $a) (let* (($d 1)) $b)))\n",
        "!(test (both 5 2) 5)\n",
        "!(test (both 2 5) 5)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "if_branch_binding");
}
