/* Purpose: check if decons expr through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/16-if_decons_expr.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (if-decons-expr (a b c) $h $t (pair $h $t) fallback) (pair a (b c)))\n",
        "!(test (if-decons-expr () $h $t (pair $h $t) fallback) fallback)\n",
        "!(test (if-decons-expr $unknown $h $t (pair $h $t) fallback) fallback)\n",
        "!(test (if-decons-expr (+ 1 2) $h $t $t fallback) (1 2))\n",
        "!(test (if-decons-expr (1 2) $h $t (+ $h 10) (/ 1 0)) 11)\n",
        "!(test (if-decons-expr (a b) a (b) matched fallback) matched)\n",
        "!(test (if-decons-expr (a b) wrong (b) matched fallback) fallback)\n",
        "!(test (if-decons-expr (a b) a () matched fallback) fallback)\n",
        "!(test (collapse (if-decons-expr (a b) $h $t (superpose (1 2 2)) fallback)) (1 2 2))\n",
        "!(test (if-error (if-decons-expr 42 $h $t yes fallback) refused answered) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "if_decons_expr");
}
