/* Purpose: check ifcasenondet through the embedded source interface.
 * Source: examples/ch07-control-flow/07-02-case/06-ifcasenondet.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (if-nondet $y) (if (superpose $y) a b))\n",
        "(= (case-nondet $y) (case (superpose $y) ((true a) (false b))))\n",
        "!(test (collapse (if-nondet (true false true))) (a b a))\n",
        "!(test (collapse (case-nondet (true false true))) (a b a))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "ifcasenondet");
}
