/* Purpose: check implication and unifiability through the embedded source interface.
 * Source: examples/ch07-control-flow/07-01-if-and-booleans/12-implication_and_unifiability.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (implies false false) true)\n",
        "!(test (implies false true) true)\n",
        "!(test (implies true true) true)\n",
        "!(test (implies true false) false)\n",
        "(= (adult? $p) (> (age $p) 17))\n",
        "(= (age ann) 30)\n",
        "(= (age bo) 12)\n",
        "(= (may-vote? $p) (implies (registered? $p) (adult? $p)))\n",
        "(= (registered? ann) true)\n",
        "(= (registered? bo) true)\n",
        "!(test (may-vote? ann) true)\n",
        "!(test (may-vote? bo) false)\n",
        "!(test (=? (f $x) (f 1)) true)\n",
        "!(test (=? (f 2) (f 1)) false)\n",
        "!(test (=? $a $b) true)\n",
        "!(test (=? (f $x) (g $x)) false)\n",
        "!(test (and (=? (f $x) (f 1)) (=? (f $x) (f 2))) true)\n",
        "!(test (if-equal2 (f $x) (f $x) same different) same)\n",
        "!(test (if-equal2 (f $x) (f $y) renamed different) different)\n",
        "!(test (if-equal2 (f $x) (f 1) renamed different) different)\n",
        "!(test (if-equal2 (f $x $x) (f $y $z) renamed different) different)\n",
        "!(test (=? (f $x) (f 1)) true)\n",
        "!(test (if-equal2 (f $x) (f 1) renamed different) different)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "implication_and_unifiability");
}
