/* Purpose: check import relative nested through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/02-import_relative_nested.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self fixtures/modules/imports/relative/root)\n",
        "!(test (from-sibling) 42)\n",
        "!(test (from-second) 7)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "import_relative_nested");
}
