/* Purpose: check import error surface through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/04-import_error_surface.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_he))\n",
        "!(test (if-error (catch (import! &self fixtures/modules/imports/import_error_broken)) Error NoError) Error)\n",
        "!(test (if-error (catch (import! &self fixtures/modules/imports/definitely_missing_import)) Error NoError) Error)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "import_error_surface");
}
