/* Purpose: check import order independence through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/01-import_order_independence.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self fixtures/modules/imports/import_order/index)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "import_order_independence");
}
