/* Purpose: check import space identity through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/05-import_space_identity.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_import))\n",
        "!(bind! &import-space-a (new-space))\n",
        "!(bind! &import-space-b (new-space))\n",
        "!(import! &import-space-a fixtures/modules/imports/overhaul/space_payload)\n",
        "!(import! &import-space-b fixtures/modules/imports/overhaul/space_payload)\n",
        "!(test (collapse (match &import-space-a (import-space-marker) present)) (present))\n",
        "!(test (collapse (match &import-space-b (import-space-marker) present)) (present))\n",
        "!(test (collapse (metta (import-space-function) %Undefined% &import-space-a)) (one-result))\n",
        "!(test (collapse (metta (import-space-function) %Undefined% &import-space-b)) (one-result))\n",
        "!(test (collapse (import-space-function)) ((import-space-function)))\n",
        "!(test (collapse (match (imports &import-space-a) (import $path) imported)) (imported))\n",
        "!(add-atom &import-space-a (import-space-marker))\n",
        "!(unimport! &import-space-a fixtures/modules/imports/overhaul/space_payload)\n",
        "!(test (collapse (match &import-space-a (import-space-marker) present)) (present))\n",
        "!(test (collapse (match (imports &import-space-a) (import $path) $path)) ())\n",
        "!(unimport! &import-space-a fixtures/modules/imports/overhaul/space_payload)\n",
        "!(test (collapse (metta (import-space-function) %Undefined% &import-space-b)) (one-result))\n",
        "!(test (collapse (metta (import-space-function) %Undefined% &import-space-a)) ((import-space-function)))\n",
        "!(import! &import-space-a fixtures/modules/imports/overhaul/space_payload)\n",
        "!(test (collapse (match &import-space-a (import-space-marker) present)) (present present))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "import_space_identity");
}
