/* Purpose: check import duplicate cycle through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/03-import_duplicate_cycle.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self fixtures/modules/imports/overhaul/duplicate)\n",
        "!(import! &self ./fixtures/modules/imports/overhaul/./duplicate.metta)\n",
        "!(import! &self fixtures/modules/imports/overhaul/cycle_a)\n",
        "!(test (collapse (duplicate-import-result)) (loaded-once))\n",
        "!(test (cycle-a) a)\n",
        "!(test (cycle-b) b)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "import_duplicate_cycle");
}
