/* Purpose: check in an equation head through the embedded source interface.
 * Source: examples/ch08-data/08-02-sequence-variables/02-in-an-equation-head.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (allof (:seg $xs)) (kept $xs))\n",
        "!(test (allof) (kept ()))\n",
        "!(test (allof a) (kept (a)))\n",
        "!(test (allof a b c) (kept (a b c)))\n",
        "(= (middle (row start (:seg $mid) end)) $mid)\n",
        "!(test (middle (row start a b end)) (a b))\n",
        "!(test (middle (row start end)) ())\n",
        "(= (split (row (:seg $before) SEP (:seg $after))) (pair $before $after))\n",
        "!(test (collapse (split (row a SEP b SEP c))) ((pair (a) (b SEP c)) (pair (a SEP b) (c))))\n",
        "(= (project (head (:seg $xs) tail)) (rebuilt before $xs after))\n",
        "(= (splice (head (:seg $xs) tail)) (rebuilt before (:seg $xs) after))\n",
        "!(test (project (head a b tail)) (rebuilt before (a b) after))\n",
        "!(test (splice (head a b tail)) (rebuilt before a b after))\n",
        "(= (echoes ((:seg $xs) tag $xs)) yes)\n",
        "!(test (echoes (a b tag (a b))) yes)\n",
        "!(test (echoes (tag ())) yes)\n",
        "!(test (collapse (echoes (a b tag (a c)))) ())\n",
        "(= (kind (row ...)) row-shaped)\n",
        "(= (kind $other) anything)\n",
        "!(test (collapse (kind (row a b))) (row-shaped anything))\n",
        "!(test (collapse (kind 7)) (anything))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "in_an_equation_head");
}
