/* Purpose: check include through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/10-include.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (include fixtures/modules/included/rows) 42)\n",
        "!(test (included-double 5) 10)\n",
        "!(test (collapse (match &self (included-fact $x) $x)) (carried))\n",
        "!(test (import! &self fixtures/modules/included/rows) true)\n",
        "!(test (collapse (include fixtures/modules/included/silent)) ())\n",
        "!(test (collapse (match &self (silent-fact $x) $x)) (here))\n",
        "!(test (collapse (catch (include nosuchmodule))) ((Error (include nosuchmodule) \"no module named nosuchmodule is available\")))\n",
        "!(test (collapse (catch (include self))) ((Error (include self) \"include: the running context is not a module\")))\n",
        "!(test (collapse (catch (include top))) ((Error (include top) \"include: the running context is not a module\")))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "include");
}
