/* Purpose: check independent supports through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/15-independent_supports.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_pln2))\n",
        "!(test (pln2-require-independent-supports ((sensor-a) (sensor-b))) true)\n",
        "!(test (pln2-require-independent-supports ((sensor-a sensor-b) (sensor-c))) true)\n",
        "!(test (pln2-require-independent-supports ()) true)\n",
        "!(test (pln2-require-independent-supports ((sensor-a))) true)\n",
        "!(test (pln2-require-independent-supports ((sensor-a) ())) true)\n",
        "!(test (let $reported (catch (pln2-require-independent-supports ((sensor-a) (sensor-a)))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(pln2_dependent_supports sensor-a)\")\n",
        "!(test (let $reported (catch (pln2-require-independent-supports ((sensor-a sensor-b) (sensor-b)))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(pln2_dependent_supports sensor-b)\")\n",
        "!(test (let $reported (catch (pln2-require-independent-supports ((s) (s)))) (unify $reported (Error $ball $context) (index-atom $context 2) no-error)) \"factor shared support in an owned reasoner with stable signed evidence IDs, then combine only disjoint residual supports\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "independent_supports");
}
