/* Purpose: check inherited spaces through the embedded source interface.
 * Source: examples/ch19-spaces-backed-by-anything/19-01-spaces-of-your-own/01-inherited_spaces.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &family-parent (edge a b))\n",
        "!(add-atom &family-parent (parent-only kept))\n",
        "!(add-atom &family-parent (layer parent))\n",
        "!(new-space &family-child (inherits &family-parent))\n",
        "!(add-atom &family-child (edge b c))\n",
        "!(add-atom &family-child (child-only local))\n",
        "!(add-atom &family-child (layer child))\n",
        "!(test (collapse (match &family-child (, (edge $x $y) (edge $y $z)) ($x $z))) ((a c)))\n",
        "!(test (collapse (match &family-child (layer $x) $x)) (child parent))\n",
        "!(test (space-atom-count &family-child) 3)\n",
        "!(test (collapse (match &family-parent (parent-only $x) $x)) (kept))\n",
        "!(test (collapse (match &family-child (parent-only $x) $x)) (kept))\n",
        "!(test (collapse (match &family-parent (child-only $x) $x)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "inherited_spaces");
}
