/* Purpose: check interpret and metta thread through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/12-interpret_and_metta_thread.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: twice (-> Number Number))\n",
        "(= (twice $x) (* 2 $x))\n",
        "!(test (metta (twice 5) %Undefined% &self) 10)\n",
        "!(test (interpret (twice 5) %Undefined% &self) 10)\n",
        "!(test (metta-thread (twice 5) %Undefined% &self) 10)\n",
        "!(test (interpret (+ 1 2) Number &self) 3)\n",
        "(= (gen) (superpose (1 2)))\n",
        "!(test (collapse (interpret (gen) %Undefined% &self)) (1 2))\n",
        "!(test (collapse (metta-thread (gen) %Undefined% &self)) (1 2))\n",
        "(= (held) (noeval (+ 1 2)))\n",
        "!(test (let $r (interpret (held) %Undefined% &self) (repr $r)) \"(+ 1 2)\")\n",
        "!(test (let $r (metta (held) %Undefined% &self) (repr $r)) \"(+ 1 2)\")\n",
        "!(test (metta-thread (held) %Undefined% &self) 3)\n",
        "(= (framed) (function (return (+ 1 2))))\n",
        "!(test (let $r (interpret (framed) %Undefined% &self) (repr $r)) \"(+ 1 2)\")\n",
        "!(test (metta-thread (framed) %Undefined% &self) 3)\n",
        "!(test (interpret nosuchhead %Undefined% &self) nosuchhead)\n",
        "!(test (metta-thread nosuchhead %Undefined% &self) nosuchhead)\n",
        "!(test (get-type interpret) (-> Atom Type SpaceType Atom))\n",
        "!(test (get-type metta) (-> Atom Type SpaceType Atom))\n",
        "!(test (get-type metta-thread) %Undefined%)\n",
        "!(add-atom &elsewhere (= (twice $x) (+ 1000 $x)))\n",
        "!(test (interpret (twice 5) %Undefined% &elsewhere) 1005)\n",
        "!(test (metta-thread (twice 5) %Undefined% &elsewhere) 1005)\n",
        "!(test (interpret (twice 5) %Undefined% &self) 10)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "interpret_and_metta_thread");
}
