/* Purpose: check invertfunction through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/06-invertfunction.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f $X $Y) (append ($X) $Y))\n",
        "(= (g $X $Y $Z) (append ((#+ $X $Z)) $Y))\n",
        "!(test (let (cons $Head $Tail) (1 2 3 4 5 6) ($Head $Tail)) (1 (2 3 4 5 6)))\n",
        "!(test (let (f $Head $Tail) (1 2 3 4 5 6) ($Head $Tail)) (1 (2 3 4 5 6)))\n",
        "!(test (let (g $X $Y 35) (42 2 3) ($X $Y 40)) (7 (2 3) 40))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "invertfunction");
}
