/* Purpose: check invertpeanoplus through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/07-invertpeanoplus.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (plus Z $y) $y)\n",
        "(= (plus (S $x) $y) (S (plus $x $y)))\n",
        "!(test (plus (S (S Z)) (S Z)) (S (S (S Z))))\n",
        "!(test (let (plus $A (S Z)) (S (S (S (S Z)))) $A) (S (S (S Z))))\n",
        "!(test (let (plus (S Z) $B) (S (S (S (S Z)))) $B) (S (S (S Z))))\n",
        "!(test (collapse (let (plus $A $B) (S (S (S (S Z)))) ($A $B))) ((Z (S (S (S (S Z))))) ((S Z) (S (S (S Z)))) ((S (S Z)) (S (S Z))) ((S (S (S Z))) (S Z)) ((S (S (S (S Z)))) Z)))\n",
        "!(test (once (let (plus $A $B) (S (S (S (S Z)))) ($A $B))) (Z (S (S (S (S Z))))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "invertpeanoplus");
}
