/* Purpose: check iter through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/05-iter.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (make-nat-iter) 0)\n",
        "(= (iter-next $N) (let* (($X $N) ($Next (+ $N 1))) ($X $Next)))\n",
        "!(test (let* (($it (make-nat-iter)) (($x1 $it1) (iter-next $it)) (($x2 $it2) (iter-next $it1)) (($x3 $it3) (iter-next $it2))) ($x1 $x2 $x3)) (0 1 2))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "iter");
}
