/* Purpose: check json lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/05-json_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_json))\n",
        "!(test (let $d (json-decode \"{\\\"a\\\":1,\\\"b\\\":2}\") (collapse (get-keys $d))) (a b))\n",
        "!(test (let $d (json-decode \"{\\\"a\\\":1,\\\"b\\\":2}\") (get-value $d a)) 1)\n",
        "!(test (let $d (json-decode \"{\\\"a\\\":1}\") (collapse (get-value $d missing))) ())\n",
        "!(test (json-decode \"[1,2,3]\") (1 2 3))\n",
        "!(test (json-decode \"\\\"plain\\\"\") \"plain\")\n",
        "!(test (json-decode \"42\") 42)\n",
        "!(test (json-decode \"true\") true)\n",
        "!(test (json-decode \"null\") Null)\n",
        "!(test (let $outer (json-decode \"{\\\"c\\\":{\\\"d\\\":2}}\") (let $inner (get-value $outer c) (get-value $inner d))) 2)\n",
        "!(test (json-decode (json-encode (1 2 3))) (1 2 3))\n",
        "!(test (json-decode (json-encode \"text\")) \"text\")\n",
        "!(test (let $d (json-decode (json-encode (dict-space ((k 1))))) (get-value $d k)) 1)\n",
        "!(test (let $d (dict-space ((name \"ann\") (age 3))) (get-value $d name)) \"ann\")\n",
        "!(test (json-at (json-decode \"{\\\"rows\\\":[{\\\"name\\\":\\\"ann\\\"}]}\") (rows 0 name)) \"ann\")\n",
        "!(test (collapse (json-at (json-decode \"{\\\"a\\\":[1],\\\"a\\\":[2]}\") (a 0))) (1 2))\n",
        "!(test (collapse (json-at (json-decode \"{}\") (missing))) ())\n",
        "!(test (json-at 42 ()) 42)\n",
        "!(test (json-encode (dict-space ())) \"{}\")\n",
        "!(test (let $d (dict-space ((from 1) (internal 2))) (collapse (get-keys $d))) (quote (from internal)))\n",
        "!(test (json-pretty (1 2)) \"[1, 2 ]\")\n",
        "!(test (json-pretty (1 2) 1) \"[\\n  1,\\n  2\\n]\")\n",
        "!(test (json-decode (json-pretty (1 2) 0)) (1 2))\n",
        "!(test (collapse (json-lines-decode \"1\\r\\ntrue\\nnull\\n\")) (1 true Null))\n",
        "!(test (json-lines-encode (1 true \"é\")) \"1\\ntrue\\n\\\"é\\\"\\n\")\n",
        "!(test (collapse (json-lines-decode \"\")) ())\n",
        "!(test (json-lines-encode ()) \"\")\n",
        "!(import! &self (library lib_file))\n",
        "!(test (let* (($path (temp-path! \"json-document\")) ($written (json-write! $path (7 8))) ($value (json-read! $path))) (chain (delete-file! $path) $_3 ($written $value))) (true (7 8)))\n",
        "!(test (let* (($path (temp-path! \"json-lines\")) ($written (json-lines-write! $path (1 true \"é\"))) ($values (collapse (json-lines-read! $path)))) (chain (delete-file! $path) $_3 ($written $values))) (true (1 true \"é\")))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "json_lib");
}
