/* Purpose: check lambda through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/05-lambda.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: apply (-> Atom %Undefined% %Undefined%))\n",
        "(= (apply (lambda $var $body) $arg) (eval (let $var $arg $body)))\n",
        "(= (applyL1) (apply (lambda $x (+ $x 1)) 2))\n",
        "(= (applyL2) (apply (lambda ($x $y) (+ $x $y)) (2 7)))\n",
        "!(test (applyL1) 3)\n",
        "!(test (applyL2) 9)\n",
        "!(test (maplist (|-> ($a) (+ 1 $a)) (1 2 3)) (2 3 4))\n",
        "!(test ((|-> ($acc $e) (or (== 1 $e) $acc)) false 1) true)\n",
        "(= (myfunc $a $b) (cons $a $b))\n",
        "!(test (let $f (myfunc 42) ((|-> ($x) ($f ($x 2 3))) 43)) (42 43 2 3))\n",
        "!(test (((|-> ($x $y) (42 $x $y)) 43) 44) (42 43 44))\n",
        "(= (myfunc2 $mylambda) ($mylambda 43 44))\n",
        "!(test (let* (($k 45) ($lambda (|-> ($x $y) (42 $x $y $k)))) (myfunc2 $lambda)) (42 43 44 45))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "lambda");
}
