/* Purpose: check letext through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/03-letext.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (let ($x (42 (if (== $x 2) 43 44))) (3 (42 $z)) (+ $x $z)) 47)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "letext");
}
