/* Purpose: check letstar through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/01-letstar.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (let* (($x 1) ($y 2)) (+ $x $y)) 3)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "letstar");
}
