/* Purpose: check letstarcomputed through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/04-letstarcomputed.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: mylet (-> Atom Atom %Undefined%))\n",
        "(= (mylet $bindings $body) (let* $bindings $body))\n",
        "!(test (mylet (($x 1) ($y 2)) (+ $x $y)) 3)\n",
        "!(test (let* (($x 1) ($y 2)) (+ $x $y)) 3)\n",
        "!(test (mylet ((($a $b) (1 2))) $b) 2)\n",
        "!(test (mylet ((5 5)) matched) matched)\n",
        "!(test (collapse (mylet ((5 6)) matched)) ())\n",
        "(= (mylet-evaluating $bindings $body) (let* $bindings $body))\n",
        "!(test (mylet-evaluating (noeval (($x 1))) $x) 1)\n",
        "!(test (let $refusal (catch (mylet-evaluating (noeval ((1 2 3))) done)) (car-atom $refusal)) Error)\n",
        "!(test (repr (let* foo ok)) \"(partial let* (foo ok))\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "letstarcomputed");
}
