/* Purpose: check lib roman pair helpers through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/14-lib_roman_pair_helpers.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_roman))\n",
        "(= (inc $x) (+ $x 1))\n",
        "!(test (first inc (1 9)) (2 9))\n",
        "!(test (second inc (1 9)) (1 10))\n",
        "!(test (flip (left right)) (right left))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "lib_roman_pair_helpers");
}
