/* Purpose: check library through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/01-library.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_roman))\n",
        "!(test (map-flat (+ 1) (1 2 3)) (2 3 4))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "library");
}
