/* Purpose: check listhead through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-02-patterns-and-bindings/06-listhead.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (len ()) 0)\n",
        "(= (len (cons $Head $Tail)) (let $N0 (len $Tail) (+ $N0 1)))\n",
        "!(test (let (cons $Head $Tail) (1 2 3 4 5 6) ($Head $Tail)) (1 (2 3 4 5 6)))\n",
        "!(test (len (1 2 3)) 3)\n",
        "!(test (cons 42 ()) (42))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "listhead");
}
