/* Purpose: check logging lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/34-logging_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_logging))\n",
        "(: record-log (-> String Expression Bool))\n",
        "(= (record-log $label $event) (add-atom &log-records (captured $label $event)))\n",
        "!(test (log-levels) (debug informational warning error))\n",
        "!(test (log-enabled \"library-example\") false)\n",
        "!(test (log-topics) ())\n",
        "!(test (log-to! missing-handler \"library-example\" error (+ 1 2)) ())\n",
        "!(test (log-format \"library-example\" debug (+ 1 2)) \"library-example [debug] (+ 1 2)\")\n",
        "!(test (log-topic! \"library-example\" true) ())\n",
        "!(test (log-enabled \"library-example\") true)\n",
        "!(test (log-topics) ((log-topic \"library-example\" true)))\n",
        "!(test (log! \"library-example\" informational \"hello\") ())\n",
        "!(test (log-to! (record-log \"first\") \"library-example\" debug (+ 1 2)) ())\n",
        "!(test (match &log-records (captured \"first\" (log-event $topic $level $payload)) (size-atom $payload)) 3)\n",
        "!(test (match &log-records (captured \"first\" (log-event $topic $level $payload)) (== (quote $payload) (quote (+ 1 2)))) true)\n",
        "!(test (log-to! (record-log \"second\") \"library-example\" informational (loaded \"data.csv\")) ())\n",
        "!(test (log-to! (|-> ($event) true) \"library-example\" warning (retry 2)) ())\n",
        "!(test (log-to! (|-> ($event) true) \"library-example\" error (failed \"input\")) ())\n",
        "!(test (size-atom (collapse (get-atoms &log-records))) 2)\n",
        "!(test (log-to! (|-> ($event) false) \"library-example\" informational \"visible\") ())\n",
        "!(test (if-error (catch (log-to! (|-> ($event) 7) \"library-example\" debug x)) refused fine) refused)\n",
        "!(test (if-error (catch (log-to! (|-> ($event) (empty)) \"library-example\" debug x)) refused fine) refused)\n",
        "!(test (if-error (catch (log-to! missing-handler \"library-example\" debug x)) refused fine) refused)\n",
        "!(test (if-error (catch (log! \"library-example\" fatal x)) refused fine) refused)\n",
        "!(test (if-error (catch (log-format \"library-example\" fatal x)) refused fine) refused)\n",
        "!(test (log-topic! \"library-example\" false) ())\n",
        "!(test (log-enabled \"library-example\") false)\n",
        "!(test (log-to! missing-handler \"library-example\" error x) ())\n",
        "!(test (log-topics) ((log-topic \"library-example\" false)))\n",
        "!(test (if-error (catch (log! \"library-example\" fatal x)) refused fine) refused)\n",
        "!(test (log-enabled \"library-example.child\") false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "logging_lib");
}
