/* Purpose: check logicprogset through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-01-logic-programs/02-logicprogset.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (myf $M) (and (and (member a $M) (member b $M)) (== (size-atom $M) 2)))\n",
        "!(test (if (once (myf $M)) $M) (a b))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "logicprogset");
}
