/* Purpose: check markup lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/29-markup_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_markup))\n",
        "!(bind! &doc (markup-parse-xml \"<order id='7'><item sku='a'>apple</item><item sku='b'>pear</item><note/></order>\"))\n",
        "!(test &doc (element order ((attr id \"7\")) ((element item ((attr sku \"a\")) (\"apple\")) (element item ((attr sku \"b\")) (\"pear\")) (element note () ()))))\n",
        "!(test (collapse (let $children (index-atom &doc 3) (let (element item ((attr sku $sku)) ($text)) (superpose $children) ($sku $text)))) ((\"a\" \"apple\") (\"b\" \"pear\")))\n",
        "!(test (markup-text &doc) \"applepear\")\n",
        "!(test (markup-attribute &doc id) \"7\")\n",
        "!(test (collapse (markup-attribute &doc missing)) ())\n",
        "!(test (markup-text (element p () ())) \"\")\n",
        "!(test (collapse (markup-select &doc ((descendant item) (text)))) (\"apple\" \"pear\"))\n",
        "!(test (collapse (markup-select &doc ((descendant item) (attribute sku)))) (\"a\" \"b\"))\n",
        "!(test (markup-select &doc ((descendant item) (index 2) (text))) \"pear\")\n",
        "!(test (collapse (markup-select &doc (child item))) ((element item ((attr sku \"a\")) (\"apple\")) (element item ((attr sku \"b\")) (\"pear\"))))\n",
        "!(test (collapse (markup-select &doc (self order))) (&doc))\n",
        "!(test (collapse (markup-select &doc (descendant missing))) ())\n",
        "!(bind! &nested (markup-parse-xml \"<a><b><c>deep</c></b><c>shallow</c></a>\"))\n",
        "!(test (collapse (markup-select &nested ((child b) (child c) (text)))) (\"deep\"))\n",
        "!(test (collapse (markup-select &nested ((descendant c) (text)))) (\"shallow\" \"deep\"))\n",
        "!(test (markup-write (element item ((attr sku \"a\")) (\"apple\"))) \"<item sku=\\\"a\\\">apple</item>\")\n",
        "!(test (markup-parse-xml (markup-write &doc)) &doc)\n",
        "!(test (markup-write (element empty () ())) \"<empty/>\")\n",
        "!(test (markup-write (element a ((attr n 1) (attr k sym)) ())) \"<a n=\\\"1\\\" k=\\\"sym\\\"/>\")\n",
        "!(test (markup-parse-html \"<p>one<p>two\") (element p () (\"one\" (element p () (\"two\")))))\n",
        "!(test (markup-text (markup-parse-html \"<p>a<b>c</b></p>\")) \"ac\")\n",
        "!(test (if-error (catch (markup-parse-xml \"<a><b></a>\")) refused fine) refused)\n",
        "!(test (if-error (catch (markup-parse-xml \"<a>\")) refused fine) refused)\n",
        "!(test (if-error (catch (markup-parse-xml \"not markup at all\")) refused fine) refused)\n",
        "!(test (if-error (catch (markup-parse-xml \"\")) refused fine) refused)\n",
        "!(test (if-error (catch (markup-parse-xml \"<!DOCTYPE d [<!ENTITY e SYSTEM '/etc/passwd'>]><d>&e;</d>\")) refused fine) refused)\n",
        "!(test (if-error (catch (markup-select &doc (nosuch item))) refused fine) refused)\n",
        "!(test (if-error (catch (markup-select &doc ((text) (descendant item)))) refused fine) refused)\n",
        "!(test (if-error (catch (markup-select &doc (index 1))) refused fine) refused)\n",
        "!(test (if-error (catch (markup-text 7)) refused fine) refused)\n",
        "!(test (if-error (catch (markup-write (nosuch))) refused fine) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "markup_lib");
}
