/* Purpose: check matchtypes through the embedded source interface.
 * Source: examples/ch09-types/14-matchtypes.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (match-types $A $B $Then $Else) (if (== $A $B) $Then $Else))\n",
        "!(match-types Atom Atom \"Matched!\" \"Didn't match\")\n",
        "!(match-types Atom Number \"Matched!\" \"Didn't match\")\n",
        "(= (match-type-or $value $type1 $type2) (match-types $type1 $type2 true $value))\n",
        "!(test (match-type-or true Number Number) true)\n",
        "!(test (match-type-or false Number Number) true)\n",
        "!(test (match-type-or true Number Bool) true)\n",
        "!(test (match-type-or false Number Bool) false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "matchtypes");
}
