/* Purpose: check matchsingle through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-02-patterns-and-bindings/01-matchsingle.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(a b)\n",
        "(a c)\n",
        "(= (match-single-via-cut $space $pattern $outPattern) (let* (($x (match $space $pattern $outPattern)) ($temp (cut))) $x))\n",
        "(= (match-single-via-once $space $pattern $outPattern) (once (match $space $pattern $outPattern)))\n",
        "!(test (collapse (match-single-via-cut &self (a $x) (a $x))) ((a b)))\n",
        "!(test (collapse (match-single-via-once &self (a $x) (a $x))) ((a b)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "matchsingle");
}
