/* Purpose: check matespace2 through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-03-search/04-matespace2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (add-atom-no-duplicate $Space $Atom) (if (== () (collapse (once (match $Space $Atom $Atom)))) (add-atom $Space $Atom) (empty)))\n",
        "(= (expand) (case (superpose (collapse (match &self (num $t) $t))) (($t ((add-atom-no-duplicate &self (num (M $t))) (add-atom-no-duplicate &self (num (W $t))))))))\n",
        "(= (mate) (case (superpose (collapse (match &self (num (M $t)) $t))) (($t (case (once (match &self (num (W $t)) $t)) (($t (add-atom-no-duplicate &self (num (C $t))))))))))\n",
        "(= (rewriteK $n) (if (== $n 0) done (let* (($temp1 (expand)) ($temp2 (mate))) (rewriteK (- $n 1)))))\n",
        "(= (mate-space-demo $K) (let* (($s (add-atom &self (num Z))) ($g (rewriteK $K))) (match &self (num $1) (num $1))))\n",
        "!(test (length (collapse (mate-space-demo 80))) 1297533)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "matespace2");
}
