/* Purpose: check matespacefast through the embedded source interface.
 * Source: examples/ch18-performance/18-01-larger-workloads/05-matespacefast.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (rewriteK $t $n) (if (== $n 0) done (let* (($_1 (add-atom &self (num (M $t)))) ($_2 (add-atom &self (num (W $t)))) ($_3 (add-atom &self (num (C $t))))) ((rewriteK (M $t) (- $n 1)) (rewriteK (W $t) (- $n 1))))))\n",
        "(= (mate-space-demo $K) (let* (($s (add-atom &self (num Z))) ($g (rewriteK Z $K))) (match &self (num $1) (num $1))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    mt_answers *rows = mt_eval(m, mt_parse("(mate-space-demo 19)"));
    check("open stream", rows != NULL);
    size_t total = 0;
    while (mt_next(rows)) ++total;
    check("streamed result count", mt_ok() && total == 1572862);
    mt_answers_free(rows);
    return done(m, "matespacefast");
}
