/* Purpose: check matespace through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-03-search/03-matespace.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (add-atom-no-duplicate $Space $Atom) (if (== () (collapse (once (match $Space $Atom $Atom)))) (add-atom $Space $Atom) (empty)))\n",
        "(= (expand) (case (match &self (num $t) $t) (($t ((add-atom-no-duplicate &self (num (M $t))) (add-atom-no-duplicate &self (num (W $t))))))))\n",
        "(= (mate) (case (match &self (num (M $t)) $t) (($t (case (once (match &self (num (W $t)) $t)) (($t (add-atom-no-duplicate &self (num (C $t))))))))))\n",
        "(= (expandK $n) (if (== $n 0) done (let $temp1 (expand) (expandK (- $n 1)))))\n",
        "(= (mate-space-demo $K) (let* (($s (add-atom &self (num Z))) ($g (expandK $K)) ($h (mate))) (match &self (num $1) (num $1))))\n",
        "!(test (length (collapse (mate-space-demo 390))) 1063919)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "matespace");
}
