/* Purpose: check math through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-03-the-number-library/01-math.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (== 1 1.0) false)\n",
        "!(test (!= 1.0 1) true)\n",
        "!(test (== 1 \"s\") false)\n",
        "!(test (== true 1) false)\n",
        "!(test (/ 7 0) (Error (/ 7 0) DivisionByZero))\n",
        "!(test (% 7 0) (Error (% 7 0) DivisionByZero))\n",
        "!(test (collapse (/ 7 0)) (noeval ((Error (/ 7 0) DivisionByZero))))\n",
        "(= (math-string) \"s\")\n",
        "!(test (sqrt-math (math-string)) (Error (sqrt-math \"s\") (BadArgType 1 Number String)))\n",
        "!(test (pow-math 2 3) 8)\n",
        "!(test (isnan-math (sqrt-math -1)) true)\n",
        "!(test (pow-math 0 -1) (noeval (Error (pow-math 0 -1) DivisionByZero)))\n",
        "!(test (isinf-math (pow-math 0.0 -1.0)) true)\n",
        "!(test (pow-math 2 2147483648) (noeval (Error (pow-math 2 2147483648) \"power argument is too big, try using float value\")))\n",
        "!(test (pow-math 1 2147483648.0) 1)\n",
        "!(test (sqrt-math 9) 3.0)\n",
        "!(test (abs-math -5) 5)\n",
        "!(test (log-math 10 100) 2.0)\n",
        "!(test (trunc-math 5.6) 5)\n",
        "!(test (ceil-math 5.2) 6)\n",
        "!(test (floor-math 5.8) 5)\n",
        "!(test (round-math 5.4) 5)\n",
        "!(test (round-math 5.6) 6)\n",
        "!(test (sin-math 0) 0.0)\n",
        "!(test (asin-math 0) 0.0)\n",
        "!(test (cos-math 0) 1.0)\n",
        "!(test (acos-math 1) 0.0)\n",
        "!(test (tan-math 0) 0.0)\n",
        "!(test (atan-math 0) 0.0)\n",
        "!(test (isnan-math 0.0) false)\n",
        "!(test (isinf-math 0.0) false)\n",
        "!(test (min-atom (2 6 7 4 9 3)) 2)\n",
        "!(test (max-atom (2 6 7 4 9 3)) 9)\n",
        "!(test (isinf-math inf) true)\n",
        "!(test (isnan-math nan) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "math");
}
