/* Purpose: check math exp random through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-03-the-number-library/02-math_exp_random.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (exp-math 0) 1.0)\n",
        "!(test (exp-math 1.0) 2.718281828459045)\n",
        "!(test (< (abs-math (- (exp-math 2.0) (* 2.718281828459045 2.718281828459045))) 1e-12) true)\n",
        "!(test (< (abs-math (- (log-math 2.718281828459045 (exp-math 3.0)) 3.0)) 1e-12) true)\n",
        "(= (in-range $lo $hi $x) (and (<= $lo $x) (<= $x $hi)))\n",
        "!(test (in-range 1 6 (random-int 1 6)) true)\n",
        "!(test (in-range 0.0 1.0 (random-float 0.0 1.0)) true)\n",
        "!(test (in-range 5 5 (random-int 5 5)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "math_exp_random");
}
