/* Purpose: check measure through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/01-measure.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_measure))\n",
        "!(test (ws-total ((0.5 a) (0.25 b) (0.25 c))) 1.0)\n",
        "!(test (ws-normalize ((2.0 a) (2.0 b))) ((0.5 a) (0.5 b)))\n",
        "!(test (ws-best ((0.2 low) (0.7 high) (0.1 mid))) high)\n",
        "!(test (ws-top ((0.2 low) (0.7 high) (0.1 mid)) 2) ((0.7 high) (0.2 low)))\n",
        "!(test (ws-collapse ((0.3 x) (0.4 y) (0.2 x))) ((0.5 x) (0.4 y)))\n",
        "!(test (ws-expect ((0.5 10) (0.5 20))) 15.0)\n",
        "!(test (ws-filter ((0.9 keep) (0.05 drop)) 0.1) ((0.9 keep)))\n",
        "!(test (ws-flip ((cat 0.9) (dog 0.4))) ((0.9 cat) (0.4 dog)))\n",
        "(= (first-weight $ps) (let $head (car-atom $ps) (index-atom $head 0)))\n",
        "!(test (ws-best (ws-softmax ((1.0 low) (3.0 high)) 0.1)) high)\n",
        "!(test (> (first-weight (ws-softmax ((1.0 a) (3.0 b)) 0.1)) 0.0) true)\n",
        "!(test (< (abs-math (- (first-weight (ws-softmax ((1.0 a) (3.0 b)) 1000.0)) 0.5)) 0.01) true)\n",
        "!(test (< (abs-math (- (ws-total (ws-softmax ((2.0 a) (5.0 b) (1.0 c)) 0.7)) 1.0)) 1e-9) true)\n",
        "(= (both-weights $ps) ((first-weight $ps) (first-weight (cdr-atom $ps))))\n",
        "!(test (both-weights (ws-softmax ((1.0 a) (2.0 b)) 1.0)) (both-weights (ws-softmax ((1000.0 a) (1001.0 b)) 1.0)))\n",
        "!(test (both-weights (ws-softmax ((1.0 a) (2.0 b)) 1.0)) (both-weights (ws-softmax ((-1000.0 a) (-999.0 b)) 1.0)))\n",
        "!(test (ws-peak ((1.0 a) (7.0 b) (3.0 c))) 7.0)\n",
        "!(test (is-member (ws-sample! ((0.5 heads) (0.5 tails))) (heads tails)) true)\n",
        "!(test (ws-sample! ((1.0 sure))) sure)\n",
        "!(test (is-member (ws-sample! ((0.1 a) (0.2 b) (0.7 c))) (a b c)) true)\n",
        "!(test (collapse (ws-choose ((0.6 yes) (0.4 no)))) ((0.6 yes) (0.4 no)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "measure");
}
