/* Purpose: check memo aggregate through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/02-memo_aggregate.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_memo))\n",
        "!(config-memoize (aggregate sum))\n",
        "!(memoize choices)\n",
        "(= (choices $x) $x)\n",
        "(= (choices $x) (+ $x 1))\n",
        "(= (choices $x) (+ $x 2))\n",
        "!(test (choices 5) 18)\n",
        "!(config-memoize (aggregate none))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "memo_aggregate");
}
