/* Purpose: check memo controls through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/17-memo_controls.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_memo))\n",
        "(: sq (-> Number Number))\n",
        "(= (sq $x) (* $x $x))\n",
        "!(memoize-exact sq)\n",
        "!(test (is-memoized sq) true)\n",
        "!(test (sq 9) 81)\n",
        "!(test (sq 9) 81)\n",
        "!(test (size-atom (get-memoize-config)) 6)\n",
        "!(test (index-atom (car-atom (get-memoize-config)) 0) strategy)\n",
        "!(test (size-atom (get-memoize-stats)) 2)\n",
        "!(test (get-memoize-stats sq) ((entries 1) (answers 1)))\n",
        "!(test (sq 4) 16)\n",
        "!(test (get-memoize-stats sq) ((entries 2) (answers 2)))\n",
        "!(clear-memoize-stats)\n",
        "!(test (get-memoize-stats) ())\n",
        "!(test (sq 9) 81)\n",
        "!(test (get-memoize-stats) ((cache_hit 1)))\n",
        "!(test (get-memoize-stats sq) ((entries 2) (answers 2)))\n",
        "!(invalidate-memoize sq)\n",
        "!(test (get-memoize-stats sq) ((entries 0) (answers 0)))\n",
        "!(test (is-memoized sq) true)\n",
        "!(test (sq 9) 81)\n",
        "!(test (get-memoize-stats sq) ((entries 1) (answers 1)))\n",
        "!(clear-memoize)\n",
        "!(test (get-memoize-stats sq) ((entries 0) (answers 0)))\n",
        "!(test (is-memoized sq) true)\n",
        "!(test (sq 9) 81)\n",
        "!(test (get-memoize-stats sq) ((entries 1) (answers 1)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "memo_controls");
}
