/* Purpose: check memo per arity through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/03-memo_per_arity.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_memo))\n",
        "!(memoize add 2)\n",
        "(= (add $x $y) (+ $x $y))\n",
        "(= (add $x $y $z) (+ (+ $x $y) $z))\n",
        "!(test (add 3 4) 7)\n",
        "!(test (add 3 4) 7)\n",
        "!(test (add 1 2 3) 6)\n",
        "!(test (add 5 6) 11)\n",
        "!(test (add 5 6) 11)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "memo_per_arity");
}
