/* Purpose: check memo multi answer through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/01-memo_multi_answer.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_memo))\n",
        "!(memoize choose)\n",
        "(= (choose $x) $x)\n",
        "(= (choose $x) (Pair $x $x))\n",
        "!(test (choose 7) (7 (Pair 7 7)))\n",
        "!(test (choose 7) (7 (Pair 7 7)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "memo_multi_answer");
}
