/* Purpose: check memo variant nonground through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/05-memo_variant_nonground.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_memo))\n",
        "!(memoize shape-kind)\n",
        "(= (shape-kind (Pair $x $y)) pair)\n",
        "!(test (shape-kind (Pair $a 2)) pair)\n",
        "!(test (shape-kind (Pair $b 2)) pair)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "memo_variant_nonground");
}
