/* Purpose: check meta types through the embedded source interface.
 * Source: examples/ch09-types/05-meta_types.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (get-metatype (foo 1 2)) Expression)\n",
        "!(test (get-metatype (a b)) Expression)\n",
        "!(test (get-metatype 1) Grounded)\n",
        "!(test (get-metatype +) Grounded)\n",
        "!(test (get-metatype $x) Variable)\n",
        "!(test (get-metatype a) Symbol)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "meta_types");
}
