/* Purpose: check mettaset through the embedded source interface.
 * Source: examples/ch06-many-answers/10-mettaset.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(let $row (superpose ((1 (superpose (a b c))) (2 (superpose (d e f))) (3 (superpose (a b))))) (let $x (cons set $row) (add-atom &self $x)))\n",
        "!(test (collapse (match &self (set $x $y) (set $x $y))) ((set 1 a) (set 1 b) (set 1 c) (set 2 d) (set 2 e) (set 2 f) (set 3 a) (set 3 b)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "mettaset");
}
