/* Purpose: check metta4 streams through the embedded source interface.
 * Source: examples/ch07-control-flow/07-04-bounded-and-committed-searches/02-metta4_streams.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (range $K $N) (if (< $K $N) (superpose ($K (range (+ $K 1) $N))) (empty)))\n",
        "!(forall (range 1 5) (|-> ($x) (add-atom &s1 (num $x))))\n",
        "!(let $x (once (range 1 5)) (add-atom &s2 (num $x)))\n",
        "!(test (collapse (get-atoms &s1)) ((num 1) (num 2) (num 3) (num 4)))\n",
        "!(test (collapse (get-atoms &s2)) ((num 1)))\n",
        "(= (gen) 1)\n",
        "(= (gen) 2)\n",
        "(= (gen) 3)\n",
        "!(test (foldall (|-> ($x $y) (+ $x $y)) (gen) 0) 6)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "metta4_streams");
}
