/* Purpose: check metta4 prog through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/05-metta4_prog.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (progn (add-atom &self (friend sam tom)) (remove-atom &self (friend sam tom)) (add-atom &self (friend sam tim)) (match &self (friend sam $1) $1)) tim)\n",
        "!(test (prog1 1 2 3) 1)\n",
        "!(test (progn 1 2 3) 3)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "metta4_prog");
}
