/* Purpose: check migrating and counting through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/13-migrating_and_counting.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_spaces))\n",
        "!(add-atom &ledger (n 1))\n",
        "!(add-atom &ledger (n 2))\n",
        "!(add-atom &ledger (m 9))\n",
        "!(test (match-count &ledger (n $x)) 2)\n",
        "!(test (match-count &ledger (m $x)) 1)\n",
        "!(test (match-count &ledger (zzz $x)) 0)\n",
        "!(assertEqual (match-count &ledger ($head $tail)) (space-atom-count &ledger))\n",
        "!(test (collapse (migrateAtoms &ledger &archive (n $x))) ((true true) (true true)))\n",
        "!(test (collapse (get-atoms &ledger)) ((m 9)))\n",
        "!(test (match-count &ledger (n $x)) 0)\n",
        "!(test (collapse (get-atoms &archive)) ())\n",
        "!(test (collapse (migrateAtoms &ledger &archive (n $x))) ())\n",
        "!(test (collapse (get-atoms &ledger)) ((m 9)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "migrating_and_counting");
}
