/* Purpose: check multiset operations through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/10-multiset_operations.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (unique-atom (a b c d d)) (a b c d))\n",
        "!(test (union-atom (a b b c) (b c c d)) (a b b c b c c d))\n",
        "!(test (intersection-atom (a b c c) (b c c c d)) (b c c))\n",
        "!(test (subtraction-atom (a b b c) (b c c d)) (a b))\n",
        "!(test (intersection-atom (a b c c) (b c d)) (b c))\n",
        "!(test (intersection-atom (a a a) (a)) (a))\n",
        "!(test (subtraction-atom (a a a) (a)) (a a))\n",
        "!(test (intersection-atom (a b) ()) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "multiset_operations");
}
