/* Purpose: check multicall through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/09-multicall.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (mycalc $x $y) (+ $x $y))\n",
        "(= (mycalc $x $y) (- $x $y))\n",
        "!(test (collapse (mycalc 1 2)) (3 -1))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "multicall");
}
