/* Purpose: check mutex and transaction through the embedded source interface.
 * Source: examples/ch15-writing-transactions-and-worlds/01-mutex_and_transaction.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &temp (cnt 37))\n",
        "(= (sloppyinc) (match &temp (cnt $x) ((remove-atom &temp (cnt $x)) (let $inc (+ $x 1) (add-atom &temp (cnt $inc))))))\n",
        "(= (mutexinc) (with_mutex testmutex (match &temp (cnt $x) ((remove-atom &temp (cnt $x)) (let $inc (+ $x 1) (add-atom &temp (cnt $inc)))))))\n",
        "(= (Transaction_rollback_fail_to_inc) (transaction (match &temp (cnt $x) ((remove-atom &temp (cnt $x)) (let $inc (+ $x 1) (add-atom &temp (cnt $inc))) (empty)))))\n",
        "!(hyperpose ((mutexinc) (mutexinc) (mutexinc) (mutexinc) (mutexinc)))\n",
        "!(test (collapse (get-atoms &temp)) ((cnt 42)))\n",
        "!(Transaction_rollback_fail_to_inc)\n",
        "!(test (collapse (get-atoms &temp)) ((cnt 42)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "mutex_and_transaction");
}
