/* Purpose: check myinterpreter through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/03-myinterpreter.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: myinterpreter (-> Atom %Undefined%))\n",
        "(= (myinterpreter $code) (let $temp (println! (\"Runtime-interpreting code\" $code)) (eval $code)))\n",
        "(= (w) 42)\n",
        "(= (v) 43)\n",
        "!(test (myinterpreter (if (== 1 1) (w) (v))) 42)\n",
        "!(test (myinterpreter (if (== 1 2) (w) (v))) 43)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "myinterpreter");
}
