/* Purpose: check nars tuffy through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/09-nars_tuffy.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_nars))\n",
        "(= (kb) ((Sentence ((==> (--> (× $1 $2) friend) (==> (--> $1 ([] smokes)) (--> $2 ([] smokes)))) (stv 0.4 0.9)) (1)) (Sentence ((==> (--> $1 ([] smokes)) (--> $1 ([] cancerous))) (stv 0.6 0.9)) (2)) (Sentence ((--> (× Anna Bob) friend) (stv 1.0 0.9)) (3)) (Sentence ((--> (× Anna Edward) friend) (stv 1.0 0.9)) (4)) (Sentence ((--> (× Anna Frank) friend) (stv 1.0 0.9)) (5)) (Sentence ((--> (× Edward Frank) friend) (stv 1.0 0.9)) (6)) (Sentence ((--> (× Gary Helen) friend) (stv 1.0 0.9)) (7)) (Sentence ((--> (× Gary Frank) friend) (stv 0.0 0.9)) (8)) (Sentence ((--> Anna ([] smokes)) (stv 1.0 0.9)) (9)) (Sentence ((--> Edward ([] smokes)) (stv 1.0 0.9)) (10))))\n",
        "!(test (NARS.Query (kb) (--> Edward ([] cancerous))) ((stv 0.6 0.48941156079382964) (2 5 6 9 10)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "nars_tuffy");
}
