/* Purpose: check nestedcons through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/01-nestedcons.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f (cons $a (cons $b $L))) $b)\n",
        "!(test (f (a b c d)) b)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "nestedcons");
}
