/* Purpose: check newtons method through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-03-search/01-newtons_method.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_memo))\n",
        "!(config-memoize (strategy wtinylfu) (unique-limit 100))\n",
        "!(memoize energy)\n",
        "(= (energy $x $n) (if (<= $n 0) (* $x $x) (+ (energy (+ (* 0.5 $x) 0.4) (- $n 1)) (energy (+ (* 0.5 $x) 0.4) (- $n 1)))))\n",
        "!(test (energy 2.0 0) 4.0)\n",
        "!(test (energy 2.0 1) 3.9199999999999995)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "newtons_method");
}
