/* Purpose: check nilbc through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-01-logic-programs/04-nilbc.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: Nat Type)\n",
        "(: Z Nat)\n",
        "(: S (-> Nat Nat))\n",
        "(: fromNumber (-> Number Nat))\n",
        "(= (fromNumber $n) (if (<= $n 0) Z (S (fromNumber (- $n 1)))))\n",
        "(: fromNat (-> Nat Number))\n",
        "(= (fromNat Z) 0)\n",
        "(= (fromNat (S $k)) (+ 1 (fromNat $k)))\n",
        "(: bc (-> $a Nat $b $b))\n",
        "(= (bc $knowledge_base $_1 $query) (let (: $proof $theorem) $query (match $knowledge_base (: $proof $theorem) (: $proof $theorem))))\n",
        "(= (bc $knowledge_base (S $depth) (: ($proof_rule $premise_proof) $theorem)) (let* (((: $proof_rule (-> (: $premise_proof $premise_type) $theorem)) (bc $knowledge_base $depth (: $proof_rule (-> (: $premise_proof $premise_type) $theorem)))) ((: $premise_proof $premise_type) (bc $knowledge_base $depth (: $premise_proof $premise_type)))) (: ($proof_rule $premise_proof) $theorem)))\n",
        "(= (bc $knowledge_base (S $depth) (: ($proof_rule $premise_proof1 $premise_proof2) $theorem)) (let* (((: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) $theorem)) (bc $knowledge_base $depth (: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) $theorem)))) ((: $premise_proof1 $premise_type1) (bc $knowledge_base $depth (: $premise_proof1 $premise_type1))) ((: $premise_proof2 $premise_type2) (bc $knowledge_base $depth (: $premise_proof2 $premise_type2)))) (: ($proof_rule $premise_proof1 $premise_proof2) $theorem)))\n",
        "(= (bc $knowledge_base (S $depth) (: ($proof_rule $premise_proof1 $premise_proof2 $premise_proof3) $theorem)) (let* (((: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) (: $premise_proof3 $premise_type3) $theorem)) (bc $knowledge_base $depth (: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) (: $premise_proof3 $premise_type3) $theorem)))) ((: $premise_proof1 $premise_type1) (bc $knowledge_base $depth (: $premise_proof1 $premise_type1))) ((: $premise_proof2 $premise_type2) (bc $knowledge_base $depth (: $premise_proof2 $premise_type2))) ((: $premise_proof3 $premise_type3) (bc $knowledge_base $depth (: $premise_proof3 $premise_type3)))) (: ($proof_rule $premise_proof1 $premise_proof2 $premise_proof3) $theorem)))\n",
        "(= (bc $knowledge_base (S $depth) (: ($proof_rule $premise_proof1 $premise_proof2 $premise_proof3 $premise_proof4) $theorem)) (let* (((: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) (: $premise_proof3 $premise_type3) (: $premise_proof4 $premise_type4) $theorem)) (bc $knowledge_base $depth (: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) (: $premise_proof3 $premise_type3) (: $premise_proof4 $premise_type4) $theorem)))) ((: $premise_proof1 $premise_type1) (bc $knowledge_base $depth (: $premise_proof1 $premise_type1))) ((: $premise_proof2 $premise_type2) (bc $knowledge_base $depth (: $premise_proof2 $premise_type2))) ((: $premise_proof3 $premise_type3) (bc $knowledge_base $depth (: $premise_proof3 $premise_type3))) ((: $premise_proof4 $premise_type4) (bc $knowledge_base $depth (: $premise_proof4 $premise_type4)))) (: ($proof_rule $premise_proof1 $premise_proof2 $premise_proof3 $premise_proof4) $theorem)))\n",
        "(= (bc $knowledge_base (S $depth) (: ($proof_rule $premise_proof1 $premise_proof2 $premise_proof3 $premise_proof4 $premise_proof5) $theorem)) (let* (((: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) (: $premise_proof3 $premise_type3) (: $premise_proof4 $premise_type4) (: $premise_proof5 $premise_type5) $theorem)) (bc $knowledge_base $depth (: $proof_rule (-> (: $premise_proof1 $premise_type1) (: $premise_proof2 $premise_type2) (: $premise_proof3 $premise_type3) (: $premise_proof4 $premise_type4) (: $premise_proof5 $premise_type5) $theorem)))) ((: $premise_proof1 $premise_type1) (bc $knowledge_base $depth (: $premise_proof1 $premise_type1))) ((: $premise_proof2 $premise_type2) (bc $knowledge_base $depth (: $premise_proof2 $premise_type2))) ((: $premise_proof3 $premise_type3) (bc $knowledge_base $depth (: $premise_proof3 $premise_type3))) ((: $premise_proof4 $premise_type4) (bc $knowledge_base $depth (: $premise_proof4 $premise_type4))) ((: $premis",
        "e_proof5 $premise_type5) (bc $knowledge_base $depth (: $premise_proof5 $premise_type5)))) (: ($proof_rule $premise_proof1 $premise_proof2 $premise_proof3 $premise_proof4 $premise_proof5) $theorem)))\n",
        "!(bind! &kbe (new-space))\n",
        "!(add-atom &kbe (: a1 (-> (: $ter (⟨=⟩ $t $r)) (: $tes (⟨=⟩ $t $s)) (⟨=⟩ $r $s))))\n",
        "!(add-atom &kbe (: a2 (⟨=⟩ (⟨+⟩ $t ⟨0⟩) $t)))\n",
        "!(test (bc &kbe (fromNumber 1) (: $prf (⟨=⟩ $t $t))) (: (a1 a2 a2) (⟨=⟩ $t $t)))\n",
        "!(bind! &kbm (new-space))\n",
        "!(add-atom &kbm (: ⟨0⟩ ⟨term⟩))\n",
        "!(add-atom &kbm (: ⟨+⟩ (-> (: $t ⟨term⟩) (: $r ⟨term⟩) ⟨term⟩)))\n",
        "!(add-atom &kbm (: ⟨=⟩ (-> (: $t ⟨term⟩) (: $r ⟨term⟩) ⟨wff⟩)))\n",
        "!(add-atom &kbm (: a1 (-> (: $t ⟨term⟩) (: $r ⟨term⟩) (: $s ⟨term⟩) (: $ter (⟨=⟩ $t $r)) (: $tes (⟨=⟩ $t $s)) (⟨=⟩ $r $s))))\n",
        "!(add-atom &kbm (: a2 (-> (: $t ⟨term⟩) (⟨=⟩ (⟨+⟩ $t ⟨0⟩) $t))))\n",
        "!(add-atom &kbm (: ⟨t⟩ ⟨term⟩))\n",
        "!(test (is-member (: (a1 (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩ ⟨t⟩ (a2 ⟨t⟩) (a2 ⟨t⟩)) (⟨=⟩ ⟨t⟩ ⟨t⟩)) (collapse (bc &kbm (fromNumber 3) (: $prf (⟨=⟩ ⟨t⟩ ⟨t⟩))))) true)\n",
        "!(bind! &kbh (new-space))\n",
        "!(add-atom &kbh (: ⟨0⟩ ⟨term⟩))\n",
        "!(add-atom &kbh (: ⟨+⟩ (-> (: $t ⟨term⟩) (: $r ⟨term⟩) ⟨term⟩)))\n",
        "!(add-atom &kbh (: ⟨=⟩ (-> (: $t ⟨term⟩) (: $r ⟨term⟩) ⟨wff⟩)))\n",
        "!(add-atom &kbh (: ⟨->⟩ (-> (: $P ⟨wff⟩) (: $Q ⟨wff⟩) ⟨wff⟩)))\n",
        "!(add-atom &kbh (: a1 (-> (: $t ⟨term⟩) (: $r ⟨term⟩) (: $s ⟨term⟩) (⟨->⟩ (⟨=⟩ $t $r) (⟨->⟩ (⟨=⟩ $t $s) (⟨=⟩ $r $s))))))\n",
        "!(add-atom &kbh (: a2 (-> (: $t ⟨term⟩) (⟨=⟩ (⟨+⟩ $t ⟨0⟩) $t))))\n",
        "!(add-atom &kbh (: mp (-> (: $maj (⟨->⟩ $P $Q)) (: $P ⟨wff⟩) (: $Q ⟨wff⟩) (: $min $P) $Q)))\n",
        "!(add-atom &kbh (: ⟨t⟩ ⟨term⟩))\n",
        "!(test (bc &kbh (fromNumber 1) (: $prf (⟨->⟩ (⟨=⟩ ⟨t⟩ ⟨t⟩) (⟨->⟩ (⟨=⟩ ⟨t⟩ ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩))))) (: (a1 ⟨t⟩ ⟨t⟩ ⟨t⟩) (⟨->⟩ (⟨=⟩ ⟨t⟩ ⟨t⟩) (⟨->⟩ (⟨=⟩ ⟨t⟩ ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩)))))\n",
        "!(test (bc &kbh (fromNumber 2) (: $prf (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩))))) (: (a1 (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩ ⟨t⟩) (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩)))))\n",
        "!(test (bc &kbh (fromNumber 1) (: $prf (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩))) (: (a2 ⟨t⟩) (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩)))\n",
        "!(test (bc &kbh (fromNumber 2) (: (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) ⟨wff⟩)) (: (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) ⟨wff⟩))\n",
        "!(test (bc &kbh (fromNumber 1) (: (⟨=⟩ ⟨t⟩ ⟨t⟩) ⟨wff⟩)) (: (⟨=⟩ ⟨t⟩ ⟨t⟩) ⟨wff⟩))\n",
        "!(test (bc &kbh (fromNumber 4) (: $prf (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩)))) (: (mp (a1 (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩ ⟨t⟩) (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩)) (a2 ⟨t⟩)) (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩))))\n",
        "!(test (bc &kbh (fromNumber 5) (: $prf (⟨=⟩ ⟨t⟩ ⟨t⟩))) (: (mp (mp (a1 (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩ ⟨t⟩) (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨->⟩ (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩)) (a2 ⟨t⟩)) (⟨=⟩ (⟨+⟩ ⟨t⟩ ⟨0⟩) ⟨t⟩) (⟨=⟩ ⟨t⟩ ⟨t⟩) (a2 ⟨t⟩)) (⟨=⟩ ⟨t⟩ ⟨t⟩)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "nilbc");
}
