/* Purpose: check nop through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/11-nop.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (nop) ())\n",
        "!(test (nop 1) ())\n",
        "!(test (nop 1 2 3) ())\n",
        "!(test (nop (add-atom &log (seen 1)) (add-atom &log (seen 2))) ())\n",
        "!(test (collapse (match &log (seen $n) $n)) (1 2))\n",
        "!(test (collapse (nop 1)) (()))\n",
        "!(test (collapse (empty)) ())\n",
        "!(test (collapse (nop (let $x (superpose (1 2 3)) (add-atom &drained (x $x))))) (() () ()))\n",
        "!(test (space-atom-count &drained) 3)\n",
        "!(test (== (nop 1) (add-atom &log (seen 3))) false)\n",
        "!(test (== (nop 1) (nop 2)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "nop");
}
