/* Purpose: check once through the embedded source interface.
 * Source: examples/ch06-many-answers/06-once.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(foo 1)\n",
        "(foo 2)\n",
        "(= (match-single $space $pat $ret) (once (match $space $pat $ret)))\n",
        "!(let $x (match-single &self (foo $1) $1) (add-atom &self (bar $x)))\n",
        "!(test (collapse (match &self (bar $1) (bar $1))) ((bar 1)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "once");
}
