/* Purpose: check outputtype through the embedded source interface.
 * Source: examples/ch09-types/04-outputtype.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: f (-> Number %Undefined%))\n",
        "(= (f $x) (+ $x 42))\n",
        "(: g (-> Number Atom))\n",
        "(= (g $x) (+ $x 42))\n",
        "(: h (-> Atom Atom))\n",
        "(= (h $x) (+ $x 42))\n",
        "!(test (f (+ 1 1)) 44)\n",
        "!(test (g (+ 1 1)) (noeval (+ 2 42)))\n",
        "!(test (h (+ 1 1)) (noeval (+ (+ 1 1) 42)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "outputtype");
}
