/* Purpose: check owned records through the embedded source interface.
 * Source: examples/ch15-writing-transactions-and-worlds/07-owned_records.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(bind! &ledger (new-space))\n",
        "!(add-atom &metta (@owned-record &ledger $account &ledger (balance $account)))\n",
        "!(add-atom &ledger (owned-by (Account 1)))\n",
        "!(test (owned-record-read (@owned-record &ledger (Account 1) &ledger (balance (Account 1)))) ())\n",
        "!(add-atom &ledger (balance (Account 1) (+ 5 5)))\n",
        "!(test (owned-record-read (@owned-record &ledger (Account 1) &ledger (balance (Account 1)))) ((balance (Account 1) (noeval (+ 5 5)))))\n",
        "!(transaction (progn (remove-atom &ledger (balance (Account 1) (+ 5 5))) (add-atom &ledger (balance (Account 1) 12))))\n",
        "!(test (owned-record-read (@owned-record &ledger (Account 1) &ledger (balance (Account 1)))) ((balance (Account 1) 12)))\n",
        "!(test (if-error (catch (transaction (add-atom &ledger (balance (Account 1) 13)))) refused committed) refused)\n",
        "!(test (owned-record-read (@owned-record &ledger (Account 1) &ledger (balance (Account 1)))) ((balance (Account 1) 12)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "owned_records");
}
