/* Purpose: check pairs lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/24-pairs_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_pairs))\n",
        "!(bind! &sales ((sydney 120) (perth 90) (sydney 30)))\n",
        "!(test (pairs-is &sales) true)\n",
        "!(test (pairs-is ((a 1) (b))) false)\n",
        "!(test (pairs-is ()) true)\n",
        "!(test (pairs-is 7) false)\n",
        "!(test (pairs-keys &sales) (sydney perth sydney))\n",
        "!(test (pairs-values &sales) (120 90 30))\n",
        "!(test (pairs-keys ()) ())\n",
        "!(test (pairs-swap &sales) ((120 sydney) (90 perth) (30 sydney)))\n",
        "!(test (pairs-swap (pairs-swap &sales)) ((sydney 120) (perth 90) (sydney 30)))\n",
        "!(test (pairs-sort-by-key &sales) ((perth 90) (sydney 120) (sydney 30)))\n",
        "!(test (pairs-sort-by-value &sales) ((sydney 30) (perth 90) (sydney 120)))\n",
        "!(test (pairs-sort-by-key ((b 1) (a 2) (b 0) (a 1))) ((a 2) (a 1) (b 1) (b 0)))\n",
        "!(test (pairs-group &sales) ((perth (90)) (sydney (120 30))))\n",
        "!(test (pairs-group ()) ())\n",
        "!(test (pairs-group ((a 1))) ((a (1))))\n",
        "!(test (pairs-ungroup (pairs-group &sales)) ((perth 90) (sydney 120) (sydney 30)))\n",
        "!(test (pairs-ungroup ((a (1 2)) (b ()))) ((a 1) (a 2)))\n",
        "!(test (pairs-ungroup ()) ())\n",
        "!(test (collapse (pairs-lookup &sales sydney)) (120 30))\n",
        "!(test (collapse (pairs-lookup &sales perth)) (90))\n",
        "!(test (collapse (pairs-lookup &sales darwin)) ())\n",
        "!(test (if (== () (collapse (pairs-lookup &sales darwin))) none found) none)\n",
        "!(test (if (== () (collapse (pairs-lookup &sales perth))) none found) found)\n",
        "!(test (collapse (pairs-lookup &sales $city)) ())\n",
        "!(test (if-error (catch (pairs-keys ((a 1) b))) refused fine) refused)\n",
        "!(test (if-error (catch (pairs-group ((a 1) (b 2 3)))) refused fine) refused)\n",
        "!(test (if-error (catch (pairs-lookup 7 a)) refused fine) refused)\n",
        "!(test (if-error (catch (pairs-ungroup ((a 1)))) refused fine) refused)\n",
        "!(test (pairs-is $x) false)\n",
        "!(test (pairs-is (quote ((+ a) (Error b)))) true)\n",
        "!(test (pairs-keys (quote ((+ a) (Error b)))) (quote (+ Error)))\n",
        "!(test (pairs-values (quote ((a (+ 1 2)) (b (Error a b))))) (quote ((+ 1 2) (Error a b))))\n",
        "!(test (pairs-swap (quote ((a (+ 1 2)) (b (Error a b))))) (quote (((+ 1 2) a) ((Error a b) b))))\n",
        "!(test (pairs-group (quote ((b (+ 1 2)) (a 2) (b (Error a b))))) (quote ((a (2)) (b ((+ 1 2) (Error a b))))))\n",
        "!(test (pairs-ungroup (quote ((a ()) (b ((+ 1 2) (Error a b)))))) (quote ((b (+ 1 2)) (b (Error a b)))))\n",
        "!(test (collapse (pairs-lookup (quote ((a (+ 1 2)) (a (Error a b)))) a)) (quote ((+ 1 2) (Error a b))))\n",
        "!(test (collapse (pairs-lookup (quote (($key 7) (a 8))) $key)) (7))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "pairs_lib");
}
