/* Purpose: check parametric types through the embedded source interface.
 * Source: examples/ch09-types/08-parametric_types.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: apply (-> (-> $tx $ty) $tx $ty))\n",
        "(= (apply $f $x) ($f $x))\n",
        "!(apply not false)\n",
        "!(get-type (apply not false))\n",
        "!(test (let (get-type apply) (-> (-> Bool Bool) Bool $result) $result) Bool)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "parametric_types");
}
