/* Purpose: check ground expression space names through the embedded source interface.
 * Source: examples/ch19-spaces-backed-by-anything/19-01-spaces-of-your-own/03-parametric_spaces.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(new-space (cache &primary-kb 100))\n",
        "!(new-space (cache &secondary-kb 10))\n",
        "!(add-atom (cache &primary-kb 100) (= (cache-config) (let (cache $base $limit) (context-space) (config $base $limit))))\n",
        "!(add-atom (cache &secondary-kb 10) (= (cache-config) (let (cache $base $limit) (context-space) (config $base $limit))))\n",
        "!(add-atom (cache &primary-kb 100) (entry primary))\n",
        "!(add-atom (cache &secondary-kb 10) (entry secondary))\n",
        "!(test (evalc (cache-config) (cache &primary-kb 100)) (config &primary-kb 100))\n",
        "!(test (evalc (cache-config) (cache &secondary-kb 10)) (config &secondary-kb 10))\n",
        "!(test (collapse (match (cache &primary-kb 100) (entry $which) $which)) (primary))\n",
        "!(test (collapse (match (cache &secondary-kb 10) (entry $which) $which)) (secondary))\n",
        "!(test (get-type (cache &primary-kb 100)) SpaceType)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "parametric_spaces");
}
