/* Purpose: check partialdef through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/04-partialdef.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (mp) (+))\n",
        "!(test (mp 1 1) 2)\n",
        "(= (.. $f1 $f2 $arg) ($f1 ($f2 $arg)))\n",
        "(= (plus1times2) (.. (* 2) (+ 1)))\n",
        "!(test (plus1times2 1) 4)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "partialdef");
}
