/* Purpose: check patrick through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/11-patrick.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_patrick))\n",
        "(= (mirror $A) (let $A (@ $L (cons $head $tail)) (append (reverse $L) $tail)))\n",
        "!(test (mirror (h a n n e s)) (s e n n a h a n n e s))\n",
        "!(test (collapse (for $x (1 2 3 4 5 6) (if (> $x 3) $x))) (4 5 6))\n",
        "!(test (iterate 0 10 1 (|-> ($i $x) (+ $x $i))) 46)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "patrick");
}
