/* Purpose: check patrick iterate fib through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/12-patrick_iterate_fib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_patrick))\n",
        "(= (fib-step $i ($a $b)) ($b (+ $a $b)))\n",
        "(= (fib $n) (first (iterate 0 $n (0 1) fib-step)))\n",
        "!(test (fib 100) 354224848179261915075)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "patrick_iterate_fib");
}
