/* Purpose: check peano through the embedded source interface.
 * Source: examples/ch07-control-flow/07-05-recursion/06-peano.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (add-atom-no-duplicate $Space $Atom) (if (== () (collapse (once (match $Space $Atom $Atom)))) (add-atom $Space $Atom) (empty)))\n",
        "(= (expand-once) (case (match &self (num $t) $t) (($x (add-atom-no-duplicate &self (num (S $x)))))))\n",
        "(= (expandK $n) (if (== $n 0) done (let $temp1 (expand-once) (expandK (- $n 1)))))\n",
        "(= (demo-peano $K) (let* (($s (add-atom &self (num Z))) ($g (expandK $K))) (match &self (num $1) $1)))\n",
        "!(test (length (collapse (demo-peano 300))) 301)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "peano");
}
