/* Purpose: check peanofast through the embedded source interface.
 * Source: examples/ch18-performance/18-01-larger-workloads/04-peanofast.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (expandK $expression $n) (if (== $n 0) done (let $temp1 (add-atom &self (num $expression)) (expandK (S $expression) (- $n 1)))))\n",
        "(= (demo-peano $K) (expandK Z $K))\n",
        "!(demo-peano 2500)\n",
        "!(test (length (collapse (match &self (num $1) $1))) 2500)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "peanofast");
}
