/* Purpose: check pln derivation control through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/19-pln_derivation_control.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_pln))\n",
        "!(test (PLN.Config.MaxSteps) 100)\n",
        "!(test (PLN.Config.TaskQueueSize) 10)\n",
        "!(test (PLN.Config.BeliefQueueSize) 100)\n",
        "!(test (StampDisjoint (1 2) (3 4)) true)\n",
        "!(test (StampDisjoint (1 2) (2 3)) false)\n",
        "!(test (StampDisjoint () (1)) true)\n",
        "!(test (StampConcat (3 1) (2)) (1 2 3))\n",
        "!(test (StampConcat (3 1) ()) (3 1))\n",
        "!(test (== (StampConcat (1) (2)) (StampConcat (2) (1))) true)\n",
        "!(test (PriorityRank (Sentence (a (stv 1.0 0.9)) (1))) 0.9)\n",
        "!(test (PriorityRank ()) -99999.0)\n",
        "!(test (PriorityRankNeg (Sentence (a (stv 1.0 0.9)) (1))) -0.9)\n",
        "!(test (PriorityRankNeg ()) -99999.0)\n",
        "!(test (ConfidenceRank ((stv 1.0 0.9) (1))) 0.9)\n",
        "!(test (ConfidenceRank ()) 0)\n",
        "!(test (BestCandidate PriorityRank () ((Sentence (a (stv 1.0 0.5)) (1)) (Sentence (b (stv 1.0 0.9)) (2)))) (Sentence (b (stv 1.0 0.9)) (2)))\n",
        "!(test (BestCandidate PriorityRankNeg () ((Sentence (a (stv 1.0 0.5)) (1)) (Sentence (b (stv 1.0 0.9)) (2)))) (Sentence (a (stv 1.0 0.5)) (1)))\n",
        "!(test (BestCandidate PriorityRank () ()) ())\n",
        "!(test (LimitSize ((Sentence (a (stv 1.0 0.5)) (1))) 5) ((Sentence (a (stv 1.0 0.5)) (1))))\n",
        "!(test (LimitSize ((Sentence (a (stv 1.0 0.5)) (1)) (Sentence (b (stv 1.0 0.9)) (2))) 2) ((Sentence (b (stv 1.0 0.9)) (2))))\n",
        "!(test (LimitSize ((Sentence (a (stv 1.0 0.5)) (1)) (Sentence (b (stv 1.0 0.9)) (2))) 1) ())\n",
        "!(test (index-atom (PLN.Derive ((Sentence ((Implication a b) (stv 1.0 0.9)) (1))) ((Sentence (a (stv 1.0 0.9)) (2))) 2) 1) ((Sentence (a (stv 1.0 0.9)) (2)) (Sentence (b (stv 1.0 0.81)) (1 2))))\n",
        "!(test (PLN.Derive ((Sentence ((Implication a b) (stv 1.0 0.9)) (1))) ((Sentence (a (stv 1.0 0.9)) (2))) 0) (((Sentence ((Implication a b) (stv 1.0 0.9)) (1))) ((Sentence (a (stv 1.0 0.9)) (2)))))\n",
        "!(test (PLN.Derive () ((Sentence (a (stv 1.0 0.9)) (2))) 100) (() ((Sentence (a (stv 1.0 0.9)) (2)))))\n",
        "!(test (PLN.Query ((Sentence ((Implication a b) (stv 1.0 0.9)) (1)) (Sentence (a (stv 1.0 0.9)) (2))) b 2) ((stv 1.0 0.81) (1 2)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "pln_derivation_control");
}
