/* Purpose: check pln formulas through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/18-pln_formulas.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_pln))\n",
        "!(test (/safe 1.0 2.0) 0.5)\n",
        "!(test (collapse (/safe 1.0 0.0)) ())\n",
        "!(test (negate 0.25) 0.75)\n",
        "!(test (invert 4.0) 0.25)\n",
        "!(test (collapse (invert 0.0)) ())\n",
        "!(test (and5 true true true true true) true)\n",
        "!(test (and5 true true false true true) false)\n",
        "!(test (min5 5 3 9 1 7) 1)\n",
        "!(test (TupleCount (a b c)) 3)\n",
        "!(test (TupleCount ()) 0)\n",
        "!(test (Without (1 2 3 2) 2) (1 3))\n",
        "!(test (ElementOf 2 (1 2 3)) true)\n",
        "!(test (ElementOf 9 (1 2 3)) false)\n",
        "!(test (Unique (1 2 1 3) ()) (1 2 3))\n",
        "!(test (InsertSorted 3 ()) (3))\n",
        "!(test (InsertSorted 3 (1 5)) (1 3 5))\n",
        "!(test (InsertSorted 0 (1 5)) (0 1 5))\n",
        "!(test (InsertionSort (3 1 2) ()) (1 2 3))\n",
        "!(test (Test2 1 1) ((Is: 1) (Should: 1) (Passed: true)))\n",
        "!(test (Test2 1 2) ((Is: 1) (Should: 2) (Passed: false)))\n",
        "!(test (Consistency_ImplicationImplicantConjunction 0.5 0.5 0.5 0.5 0.5) true)\n",
        "!(test (Consistency_ImplicationImplicantConjunction 0.0 0.5 0.5 0.5 0.5) false)\n",
        "!(test (Consistency_ImplicationImplicantConjunction 0.5 0.5 0.1 0.5 0.5) false)\n",
        "!(test (Truth_w2c 9.0) 0.9)\n",
        "!(test (< (abs-math (- (Truth_c2w 0.9) 9.0)) 1e-9) true)\n",
        "!(test (collapse (Truth_c2w 1.0)) ())\n",
        "!(test (Truth_Negation (stv 0.8 0.9)) (stv 0.19999999999999996 0.9))\n",
        "!(test (Truth_Revision (stv 1.0 0.9) (stv 0.0 0.9)) (stv 0.5 0.9473684210526316))\n",
        "!(test (Truth_SymmetricModusPonens (stv 1.0 0.9) (stv 1.0 0.8)) (stv 1.0 0.8))\n",
        "!(test (SymmetricModusPonensRuleGuard Similarity) true)\n",
        "!(test (SymmetricModusPonensRuleGuard IntentionalSimilarity) true)\n",
        "!(test (SymmetricModusPonensRuleGuard ExtensionalSimilarity) true)\n",
        "!(test (collapse (SymmetricModusPonensRuleGuard Inheritance)) ())\n",
        "!(test (Truth_inversion (stv 0.5 0.9) (stv 0.8 0.9)) (stv 0.8 0.48600000000000004))\n",
        "!(test (Truth_equivalenceToImplication (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.8 0.9)) (stv 0.888888888888889 0.9))\n",
        "!(test (TransitiveSimilarityStrength 0.5 0.5 0.5 0.5 0.5) 0.3846153846153847)\n",
        "!(test (Truth_transitiveSimilarity (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.8) (stv 0.5 0.7)) (stv 0.3846153846153847 0.7))\n",
        "!(test (simpleDeductionStrength 0.5 0.5 0.5 0.5 0.5) 0.5)\n",
        "!(test (collapse (simpleDeductionStrength 0.0 0.5 0.5 0.5 0.5)) ())\n",
        "!(test (Truth_evaluationImplication (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9)) (stv 0.5 0.6561000000000001))\n",
        "!(test (Truth_Induction (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9)) (stv 0.5 0.4736842105263158))\n",
        "!(test (Truth_Abduction (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9) (stv 0.5 0.9)) (stv 0.5 0.4736842105263158))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "pln_formulas");
}
