/* Purpose: check pln roman through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/06-pln_roman.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_pln))\n",
        "(= (STV A) (stv 0.5 0.9))\n",
        "(= (STV B) (stv 0.25 0.9))\n",
        "(= (STV C) (stv 0.25 0.9))\n",
        "(= (STV D) (stv 0.5 0.9))\n",
        "(= (kb) ((Sentence ((Inheritance A B) (stv 0.25 0.9)) (1)) (Sentence ((Inheritance A C) (stv 0.25 0.9)) (2)) (Sentence ((Inheritance B D) (stv 0.5 0.9)) (3)) (Sentence ((Inheritance C D) (stv 0.5 0.9)) (4))))\n",
        "!(test (with-pragma! ((max-stack-depth 100000000)) (PLN.Query (kb) (Inheritance A D))) ((stv 0.5 0.9473684210526316) (1 2 3 4)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "pln_roman");
}
