/* Purpose: check plntest through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/03-plntest.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (clamp $v $min $max) (min $max (max $v $min)))\n",
        "(: smallest-intersection-probability (-> Number Number Number))\n",
        "(= (smallest-intersection-probability $As $Bs) (clamp (/ (- (+ $As $Bs) 1) $As) 0 1))\n",
        "(: largest-intersection-probability (-> Number Number Number))\n",
        "(= (largest-intersection-probability $As $Bs) (clamp (/ $Bs $As) 0 1))\n",
        "(: conditional-probability-consistency (-> Number Number Number Bool))\n",
        "(= (conditional-probability-consistency $As $Bs $ABs) (and (< 0 $As) (and (<= (smallest-intersection-probability $As $Bs) $ABs) (<= $ABs (largest-intersection-probability $As $Bs)))))\n",
        "(= (Truth_Deduction (stv $Ps $Pc) (stv $Qs $Qc) (stv $Rs $Rc) (stv $PQs $PQc) (stv $QRs $QRc)) (if (and (conditional-probability-consistency $Ps $Qs $PQs) (conditional-probability-consistency $Qs $Rs $QRs)) (stv (if (< 0.9999 $Qs) $Rs (+ (* $PQs $QRs) (/ (* (- 1 $PQs) (- $Rs (* $Qs $QRs))) (- 1 $Qs)))) (min $Pc (min $Qc (min $Rc (min $PQc $QRc))))) (stv 1 0)))\n",
        "(= (SyllogisticRuleGuard Inheritance) true)\n",
        "(= (SyllogisticRuleGuard Implication) true)\n",
        "(= (STV a) (stv 0.4 0.9))\n",
        "(= (STV b) (stv 0.4 0.9))\n",
        "(= (STV c) (stv 0.4 0.9))\n",
        "(= (|- (($LinkType $A $B) $T1) (($LinkType $B $C) $T2)) (if (SyllogisticRuleGuard $LinkType) (($LinkType $A $C) (Truth_Deduction (STV $A) (STV $B) (STV $C) $T1 $T2)) (empty)))\n",
        "!(test (|- ((Inheritance a b) (stv 0.9 0.9)) ((Inheritance b c) (stv 0.8 0.9))) ((Inheritance a c) (stv 0.7333333333333334 0.9)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "plntest");
}
