/* Purpose: check post add hooks through the embedded source interface.
 * Source: examples/ch15-writing-transactions-and-worlds/05-post_add_hooks.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (audit (raw $x)) (accept (cooked $x)))\n",
        "(= (audit (secret $x)) (refuse \"no secrets survive the audit\"))\n",
        "(= (audit (dup $x)) (drop))\n",
        "(= (audit (plain $x)) (accept))\n",
        "!(declare-post-add! &pool audit)\n",
        "!(add-atom &pool (plain 1))\n",
        "!(test (match &pool (plain $x) $x) 1)\n",
        "!(add-atom &pool (raw 7))\n",
        "!(test (match &pool (cooked $x) $x) 7)\n",
        "!(test (collapse (match &pool (raw $x) $x)) ())\n",
        "!(add-atom &pool (dup 3))\n",
        "!(test (collapse (match &pool (dup $x) $x)) ())\n",
        "!(test (repr (catch (add-atom &pool (secret 1)))) \"(Error (metta_add_refused &pool (secret 1) \\\"no secrets survive the audit\\\") none)\")\n",
        "!(test (collapse (match &pool (secret $x) $x)) ())\n",
        "!(test (repr (catch (add-atom &pool (uncovered 9)))) \"(Error (metta_hook_stuck &pool post-add audit (uncovered 9)) none)\")\n",
        "!(test (collapse (match &pool (uncovered $x) $x)) ())\n",
        "(= (other-audit $a) (accept))\n",
        "!(test (repr (catch (declare-post-add! &pool other-audit))) \"(Error (metta_hook_conflict &pool post-add audit other-audit) none)\")\n",
        "(= (gate (raw $x)) (accept))\n",
        "(= (gate (banned $x)) (drop))\n",
        "(= (gate (plain $x)) (accept))\n",
        "!(declare-pre-add! &pool gate)\n",
        "!(add-atom &pool (raw 8))\n",
        "!(test (match &pool (cooked 8) found) found)\n",
        "!(add-atom &pool (banned 1))\n",
        "!(test (collapse (match &pool (banned $x) $x)) ())\n",
        "!(undeclare-post-add! &pool)\n",
        "!(undeclare-pre-add! &pool)\n",
        "!(add-atom &pool (uncovered 10))\n",
        "!(test (match &pool (uncovered $x) $x) 10)\n",
        "!(undeclare-post-add! &pool)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "post_add_hooks");
}
