/* Purpose: check pre add hooks through the embedded source interface.
 * Source: examples/ch15-writing-transactions-and-worlds/03-pre_add_hooks.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (guard (secret $x)) (refuse \"no secrets in this pool\"))\n",
        "(= (guard (raw $x)) (accept (cooked $x)))\n",
        "(= (guard (dup $x)) (drop))\n",
        "(= (guard (plain $x)) (accept))\n",
        "!(declare-pre-add! &pool guard)\n",
        "!(add-atom &pool (plain 1))\n",
        "!(test (match &pool (plain $x) $x) 1)\n",
        "!(add-atom &pool (raw 7))\n",
        "!(test (match &pool (cooked $x) $x) 7)\n",
        "!(add-atom &pool (dup 3))\n",
        "!(test (collapse (match &pool (dup $x) $x)) ())\n",
        "!(test (repr (catch (add-atom &pool (secret 1)))) \"(Error (metta_add_refused &pool (secret 1) \\\"no secrets in this pool\\\") none)\")\n",
        "!(test (repr (catch (add-atom &pool (uncovered 9)))) \"(Error (metta_hook_stuck &pool pre-add guard (uncovered 9)) none)\")\n",
        "(= (other-guard $a) (accept))\n",
        "!(test (repr (catch (declare-pre-add! &pool other-guard))) \"(Error (metta_hook_conflict &pool pre-add guard other-guard) none)\")\n",
        "!(undeclare-pre-add! &pool)\n",
        "!(add-atom &pool (uncovered 10))\n",
        "!(test (match &pool (uncovered $x) $x) 10)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "pre_add_hooks");
}
