/* Purpose: check process lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/32-process_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_process))\n",
        "!(test (process-run! \"echo\" (\"hi\")) (process-result 0 \"hi\\n\" \"\"))\n",
        "!(test (process-run! \"echo\" (\"one\" \"two\")) (process-result 0 \"one two\\n\" \"\"))\n",
        "!(test (process-run! \"true\" ()) (process-result 0 \"\" \"\"))\n",
        "!(test (process-run! \"false\" ()) (process-result 1 \"\" \"\"))\n",
        "!(test (index-atom (process-run! \"sh\" (\"-c\" \"exit 7\")) 1) 7)\n",
        "!(test (process-run! \"sh\" (\"-c\" \"echo out; echo err 1>&2; exit 3\")) (process-result 3 \"out\\n\" \"err\\n\"))\n",
        "!(test (process-run! \"echo\" (\"; echo hacked\")) (process-result 0 \"; echo hacked\\n\" \"\"))\n",
        "!(test (process-run! \"sh\" (\"-c\" \"echo shell\")) (process-result 0 \"shell\\n\" \"\"))\n",
        "!(test (process-run-input! \"cat\" () \"fed\") (process-result 0 \"fed\" \"\"))\n",
        "!(test (process-run-input! \"wc\" (\"-c\") \"1234\") (process-result 0 \"4\\n\" \"\"))\n",
        "!(test (if-error (catch (process-run! \"no_such_program_anywhere\" ())) refused fine) refused)\n",
        "!(test (if-error (catch (process-run! \"/no/such/binary\" ())) refused fine) refused)\n",
        "!(bind! &quick (process-start! \"true\" ()))\n",
        "!(test (> &quick 0) true)\n",
        "!(test (process-wait! &quick) 0)\n",
        "!(test (if-error (catch (process-wait! &quick)) refused fine) refused)\n",
        "!(bind! &sleeper (process-start! \"sleep\" (\"30\")))\n",
        "!(test (process-status &sleeper) running)\n",
        "!(test (process-signal! &sleeper term) true)\n",
        "!(test (process-wait! &sleeper) -15)\n",
        "!(test (process-signals) (term kill int hup))\n",
        "!(test (if-error (catch (process-signal! 1 nosuch)) refused fine) refused)\n",
        "!(test (if-error (catch (process-run! \"echo\" \"not a collection\")) refused fine) refused)\n",
        "!(test (if-error (catch (process-run! \"echo\" ((nested)))) refused fine) refused)\n",
        "!(test (if-error (catch (process-run! 7 ())) refused fine) refused)\n",
        "!(test (if-error (catch (process-wait! \"not a process\")) refused fine) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "process_lib");
}
