/* Purpose: check program order through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/03-program_order.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(p121-example-respond me)\n",
        "(= (p121-example-respond me) hello)\n",
        "!(test (p121-example-respond me) hello)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "program_order");
}
