/* Purpose: check reader tokens through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-07-tokens-and-the-reader/01-reader-tokens.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (repr (parse \"12px\")) \"12px\")\n",
        "!(test (register-token! \"[0-9]+px\" Pixels) true)\n",
        "!(test (repr (parse \"12px\")) \"(Pixels \\\"12px\\\")\")\n",
        "!(test (repr (parse \"(width 12px)\")) \"(width (Pixels \\\"12px\\\"))\")\n",
        "!(test (repr (parse \"(box 12px 4px)\")) \"(box (Pixels \\\"12px\\\") (Pixels \\\"4px\\\"))\")\n",
        "!(test (repr (parse \"12pxy\")) \"12pxy\")\n",
        "!(test (repr (parse \"px\")) \"px\")\n",
        "!(test (register-token! \"[0-9]+%\" Percent) true)\n",
        "!(test (repr (parse \"(size 50% 12px)\")) \"(size (Percent \\\"50%\\\") (Pixels \\\"12px\\\"))\")\n",
        "!(test (register-token! \"[0-9]+px\" Device) true)\n",
        "!(test (repr (parse \"12px\")) \"(Device \\\"12px\\\")\")\n",
        "!(test (unregister-token! \"[0-9]+px\") true)\n",
        "!(test (repr (parse \"12px\")) \"12px\")\n",
        "!(test (unregister-token! \"[0-9]+px\") true)\n",
        "!(test (repr (parse \"50%\")) \"(Percent \\\"50%\\\")\")\n",
        "!(test (unregister-token! \"[0-9]+%\") true)\n",
        "!(test (repr (parse \"50%\")) \"50%\")\n",
        "!(test (repr (catch (register-token! 12 Pixels))) \"(Error (type_error text 12) (context register-token! a token pattern is text))\")\n",
        "!(test (repr (catch (register-token! \"[0-9]+em\" \"not a symbol\"))) \"(Error (domain_error metta_reader_constructor \\\"not a symbol\\\") (context (/ register-token! 3) the constructor must be a readable symbol))\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "reader_tokens");
}
