/* Purpose: check recursive types2 through the embedded source interface.
 * Source: examples/ch09-types/10-recursive_types2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: Z Nat)\n",
        "(: S (-> Nat Nat))\n",
        "(: Greater (-> Nat Nat Bool))\n",
        "(= (Greater (S $x) Z) true)\n",
        "(= (Greater Z $x) false)\n",
        "(= (Greater (S $x) (S $y)) (Greater $x $y))\n",
        "!(test (Greater (S Z) (S Z)) false)\n",
        "!(test (Greater (S (S Z)) (S Z)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "recursive_types2");
}
