/* Purpose: check recursive types through the embedded source interface.
 * Source: examples/ch09-types/09-recursive_types.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: blacksmith (-> Metal Sword))\n",
        "(: blacksmith (-> Metal Paperclip))\n",
        "(: iron Metal)\n",
        "(: gold Metal)\n",
        "!(test (get-type iron) Metal)\n",
        "!(test (collapse (get-type blacksmith)) ((-> Metal Sword) (-> Metal Paperclip)))\n",
        "!(test (collapse (get-type (blacksmith iron))) (Sword Paperclip))\n",
        "!(test (collapse (get-type (iron blacksmith))) ((Metal (-> Metal Sword)) (Metal (-> Metal Paperclip))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "recursive_types");
}
