/* Purpose: check reference maps through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/12-reference_maps.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(from ./fixtures/modules/references/maps (only (map-value)))\n",
        "!(test (map-value 2) 3)\n",
        "!(test (collapse (map-label)) ((map-label)))\n",
        "(from ./fixtures/modules/references/maps (except (map-value)))\n",
        "!(test (map-label) label)\n",
        "(from ./fixtures/modules/references/maps (prefix p.))\n",
        "(from ./fixtures/modules/references/maps (rename ((map-value renamed))))\n",
        "(from ./fixtures/modules/references/maps (qualified module))\n",
        "!(test (p.map-value 2) 3)\n",
        "!(test (renamed 2) 3)\n",
        "!(test (module.map-value 2) 3)\n",
        "!(test (collapse (map-label)) (label))\n",
        "(from ./fixtures/modules/references/maps (rename ((map-value (only-two 2)))))\n",
        "!(test (only-two 2) 3)\n",
        "(from ./fixtures/modules/references/maps (|-> ($h) (if (== $h map-value) (superpose (lambda-one lambda-two)) (empty))))\n",
        "!(test (lambda-one 2) 3)\n",
        "!(test (lambda-two 2) 3)\n",
        "!(test ((prefix text.) word) text.word)\n",
        "!(pragma! from-map (prefix default.))\n",
        "(from ./fixtures/modules/references/maps)\n",
        "!(test (default.map-value 2) 3)\n",
        "!(pragma! from-map none)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "reference_maps");
}
