/* Purpose: check reference loading through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-04-modules-and-the-catalog/13-reference_loading.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(pragma! load lazy)\n",
        "(from ./fixtures/modules/references/maps (prefix lazy.))\n",
        "!(test (lazy.map-value 41) 42)\n",
        "!(test (lazy.map-label) label)\n",
        "!(pragma! load background)\n",
        "(from ./fixtures/modules/references/background)\n",
        "!(test (background-value 41) 42)\n",
        "!(test (case (catch (add-atom &self (from ./fixtures/modules/references/effectful))) (((Error $form $reason) refused))) refused)\n",
        "!(pragma! load lazy)\n",
        "!(test (case (catch (add-atom &self (from ./fixtures/modules/references/effectful))) (((Error $form $reason) refused))) refused)\n",
        "!(pragma! load eager)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "reference_loading");
}
