/* Purpose: check reflect lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/14-reflect_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_reflect))\n",
        "(= (mine $x) $x)\n",
        "!(test (knows? car-atom) true)\n",
        "!(test (knows? mine) true)\n",
        "!(test (knows? no-such-name-anywhere) false)\n",
        "!(test (collapse (arity-of car-atom)) (2))\n",
        "!(test (collapse (arity-of cons-atom)) (3))\n",
        "!(test (collapse (arity-of no-such-name-anywhere)) ())\n",
        "!(test (once (car-atom (origin-of car-atom))) origin)\n",
        "!(test (car-atom (origin-of mine)) origin)\n",
        "!(test (collapse (origin-of no-such-name-anywhere)) ())\n",
        "!(test (> (size-atom (collapse (builtins))) 100) true)\n",
        "!(test (> (size-atom (collapse (special-forms))) 10) true)\n",
        "!(test (is-member mine (collapse (user-functions))) true)\n",
        "!(test (is-member car-atom (collapse (user-functions))) false)\n",
        "!(test (is-member car-atom (collapse (functions))) true)\n",
        "!(test (is-member case (collapse (builtins))) false)\n",
        "!(test (is-member case (collapse (special-forms))) true)\n",
        "!(test (is-member let (collapse (builtins))) true)\n",
        "!(test (is-member let (collapse (special-forms))) true)\n",
        "!(test (> (size-atom (collapse (extension-points))) 3) true)\n",
        "!(test (is-member (foreign_space 1 ownership) (collapse (extension-points))) true)\n",
        "!(test (size-atom (surface-counts)) 4)\n",
        "!(test (let $counts (surface-counts) (index-atom (car-atom $counts) 0)) builtins)\n",
        "!(test (> (string-length (surface-json)) 1000) true)\n",
        "!(test (string-starts-with (surface-json) \"{\") true)\n",
        "!(test (== (collapse (engine-arity car-atom)) (collapse (arity-of car-atom))) true)\n",
        "!(test (engine-knows car-atom) true)\n",
        "!(test (engine-knows no-such-name-anywhere) false)\n",
        "!(test (collapse (engine-origin car-atom)) ((builtin)))\n",
        "!(test (== (engine-surface-counts) (surface-counts)) true)\n",
        "!(test (== (size-atom (collapse (engine-builtin))) (size-atom (collapse (builtins)))) true)\n",
        "!(test (== (size-atom (collapse (engine-special-form))) (size-atom (collapse (special-forms)))) true)\n",
        "!(test (== (size-atom (collapse (engine-function))) (size-atom (collapse (functions)))) true)\n",
        "!(test (== (size-atom (collapse (engine-user-function))) (size-atom (collapse (user-functions)))) true)\n",
        "!(test (== (size-atom (collapse (engine-extension-point))) (size-atom (collapse (extension-points)))) true)\n",
        "!(test (atom-replace (+ 1 2) ((1 10))) (noeval (+ 10 2)))\n",
        "!(test (atom-replace (f a) (((f a) root) (a child))) root)\n",
        "!(test (atom-replace (a a) ((a b) (b c))) (b b))\n",
        "!(test (collapse (atom-replace (a a) ((a b) (a c)))) ((b b) (b c) (c b) (c c)))\n",
        "!(test (collapse (atom-replace a ((a b) (a b)))) (b b))\n",
        "!(test (atom-replace (f ()) ((f g) (() empty-value))) (g empty-value))\n",
        "!(test (atom-replace () ((() (f a)))) (f a))\n",
        "!(test (atom-replace (+ 1 2) ()) (noeval (+ 1 2)))\n",
        "!(test (atom-replace a ((a (Error data code)))) (noeval (Error data code)))\n",
        "!(test (atom-replace a ((a Empty))) (noeval Empty))\n",
        "!(test (collapse (atom-replace (a a) ((a Empty) (a b)))) (noeval ((Empty Empty) (Empty b) (b Empty) (b b))))\n",
        "!(test (atom-replace (1 1.0) ((1 integer) (1.0 float))) (integer float))\n",
        "!(test (let $vars (atom-variables ($x ($y $x) $z $y)) (== $vars (quote ($x $y $z)))) true)\n",
        "!(test (let $vars (atom-variables (let $x $y (f $x $z))) (== $vars (quote ($x $y $z)))) true)\n",
        "!(test (atom-variables (+ 1 2)) ())\n",
        "!(test (let $changed (atom-replace ($x $y $x) (($x $z))) (== $changed (quote ($z $y $z)))) true)\n",
        "!(test (let $kept (atom-replace (p $x) (((p $y) wrong))) (== $kept (quote (p $x)))) true)\n",
        "(reflect-rule a b)\n",
        "(reflect-rule a c)\n",
        "!(test (let $rules (collapse (match &self (reflect-rule $from $to) (quote ($from $to)))) (collapse (atom-replace (h a) $rules))) ((h b) (h c)))\n",
        "!(test (alltd fail (+ 1 2)) (noeval (+ 1 2)))\n",
        "!(test (seq (+ 1 2)) (noeval (+ 1 2)))\n",
        "!(test (seq id id id (+ 1 2)) (noeval (+ 1 2)))\n",
        "!(test (collapse (choice (+ 1 2))) ())\n",
        "!(test (collapse (repeat 3 (noeval token))) (token token token))\n",
        "!(test (if-error (catch (atom-replace a ((a)))) refused accepted) refused)\n",
        "!(test (let $source (match &self (= (atom-variables $term) $body) (quote (|-> ($term) $body))) (let $inspect (eval $source) (let $vars ($inspect (quote ($x $x))) (== $vars (quote ($x)))))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "reflect_lib");
}
