/* Purpose: check regex lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/04-regex_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_regex))\n",
        "!(test (re-match \"(?i)^needle\" \"Needle in a haystack\") true)\n",
        "!(test (re-match \"^x\" \"abc\") false)\n",
        "!(test (collapse (re-find \"\\\\d+\" \"a1 b22 c333\")) (\"1\" \"22\" \"333\"))\n",
        "!(test (re-captures \"(?<year_I>\\\\d\\\\d\\\\d\\\\d)-(?<month_I>\\\\d\\\\d)\" \"2017-04-20\") ((0 \"2017-04\") (month 4) (year 2017)))\n",
        "!(test (re-split \":\\\\s*\" \"Age: 33\") (\"Age\" \": \" \"33\"))\n",
        "!(test (re-replace-all \"a+\" \"X\" \"banana\") \"bXnXnX\")\n",
        "!(test (re-replace \"(?<y>\\\\d+)\" \"[$y]\" \"n 42 n\") \"n [42] n\")\n",
        "!(test (regex_match \"^x\" \"xyz\") true)\n",
        "!(test (collapse (regex_find \"x\" \"x-x\")) (\"x\" \"x\"))\n",
        "!(test (regex_captures \"(x)\" \"x\") ((0 \"x\") (1 \"x\")))\n",
        "!(test (regex_split \",\" \"a,b\") (\"a\" \",\" \"b\"))\n",
        "!(test (regex_replace \"x\" \"y\" \"xx\") \"yx\")\n",
        "!(test (regex_replace_all \"x\" \"y\" \"xx\") \"yy\")\n",
        "!(test (let $pattern (re-compile \"\\\\d+\") (collapse (re-find $pattern \"n7 n8\"))) (\"7\" \"8\"))\n",
        "!(test (re-fullmatch \"a|ab\" \"ab\") true)\n",
        "!(test (re-fullmatch \"a|ab\" \"abc\") false)\n",
        "!(test (collapse (re-scan \"(?<n_I>\\\\d+)\" \"a1 b22\")) (((0 \"1\") (n 1)) ((0 \"22\") (n 22))))\n",
        "!(test (collapse (re-ranges \".\" \"é🦊\")) ((0 1) (1 1)))\n",
        "!(test (re-count \"\" \"é🦊\") 3)\n",
        "!(test (re-fullmatch (re-escape \"a.*\\\\E #\") \"a.*\\\\E #\") true)\n",
        "!(test (collapse (re-find \"a*?\" \"aa\")) (\"\" \"a\" \"\" \"a\" \"\"))\n",
        "!(test (re-split \"\" \"a\") (\"\" \"\" \"a\" \"\" \"\"))\n",
        "!(test (re-replace-all \"a*?\" \"X\" \"aa\") \"XXXXX\")\n",
        "!(test (re-captures \"((a)?b)\" \"b\") ((0 \"b\") (1 \"b\")))\n",
        "!(test (re-replace \"(?<term_T>1-2)\" \"$term\" \"before 1-2 after\") \"before 1-2 after\")\n",
        "!(test (re-captures \"(?<span_R>é)(?<term_T>1-2)\" \"é1-2\") (quote ((0 \"é1-2\") (span (- 0 1)) (term (- 1 2)))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "regex_lib");
}
