/* Purpose: check registering prolog predicates through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-03-prolog-underneath/04-registering_prolog_predicates.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_import))\n",
        "(: Predicate (-> Expression %Undefined%))\n",
        "!(test (check_prolog_function_names (noeval (rung_fresh_one rung_fresh_two)) \"example.pl\") true)\n",
        "!(test (let $reported (catch (check_prolog_function_names (noeval (car-atom)) \"example.pl\")) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(permission_error register metta_builtin car-atom)\")\n",
        "!(test (let $reported (catch (check_prolog_function_names (noeval (rung_fresh_one car-atom)) \"example.pl\")) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(permission_error register metta_builtin car-atom)\")\n",
        "!(test (let $reported (catch (import_prolog_functions (noeval (rung_absent_predicate)))) (unify $reported (Error $ball $context) (repr $ball) no-error)) \"(existence_error procedure rung_absent_predicate)\")\n",
        "!(import_prolog_functions_from_file \"./fixtures/prolog/rung_functions.pl\" ())\n",
        "!(test (import_prolog_functions (rung_double rung_greeting)) true)\n",
        "!(test (rung_double 21) 42)\n",
        "!(test (rung_greeting) world)\n",
        "!(test (assertzPredicate (Predicate (rung_fact a))) true)\n",
        "!(test (assertzPredicate (Predicate (rung_fact b))) true)\n",
        "!(test (collapse (let $t (callPredicate (Predicate (rung_fact $x))) $x)) (a b))\n",
        "!(test (retractPredicate (Predicate (rung_fact a))) true)\n",
        "!(test (collapse (let $t (callPredicate (Predicate (rung_fact $x))) $x)) (b))\n",
        "!(test (retractPredicate (Predicate (rung_fact zzz))) false)\n",
        "!(test (assertaPredicate (Predicate (rung_fact earliest))) true)\n",
        "!(test (collapse (let $t (callPredicate (Predicate (rung_fact $x))) $x)) (earliest b))\n",
        "!(test (register_metta_library_path rung-alias \"./fixtures/prolog\") true)\n",
        "!(test (register_metta_library_path rung-alias \"./fixtures/prolog\") true)\n",
        "!(import! &self (library rung-alias rung_library.metta))\n",
        "!(test (rung-aliased 5) 105)\n",
        "!(test (let $reported (catch (register_metta_library_path rung-nowhere \"./no/such/directory\")) (unify $reported (Error $ball $context) (car-atom $ball) no-error)) existence_error)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "registering_prolog_predicates");
}
