/* Purpose: check relational integer division through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-04-arithmetic-that-runs-backwards/04-relational_integer_division.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (#// 7 2) 3)\n",
        "!(test (#div 7 2) 3)\n",
        "!(test (#// -7 2) -3)\n",
        "!(test (#div -7 2) -4)\n",
        "!(test (#// 7 -2) -3)\n",
        "!(test (#div 7 -2) -4)\n",
        "!(test (+ (* (#div -7 2) 2) (#mod -7 2)) -7)\n",
        "!(test (+ (* (#// -7 2) 2) (#mod -7 2)) -5)\n",
        "!(test (let 3 (#// 7 $d) $d) 2)\n",
        "!(test (let true (#< $n 7) (let 3 (#// $n 2) $n)) 6)\n",
        "!(test (let true (#> $n 6) (let 3 (#// $n 2) $n)) 7)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "relational_integer_division");
}
