/* Purpose: check repr through the embedded source interface.
 * Source: examples/ch03-atoms-and-expressions/04-repr.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (repr 42) \"42\")\n",
        "!(test (repr \"42\") \"\\\"42\\\"\")\n",
        "!(test (repr (A (B C))) \"(A (B C))\")\n",
        "!(test (repr (A (, B , C ,))) \"(A (, B , C ,))\")\n",
        "!(test (repr 2025_12_12) \"2025_12_12\")\n",
        "!(test (repr ()) \"()\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "repr");
}
