/* Purpose: check roman through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/15-roman.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_roman))\n",
        "!(test (map-flat (+ 1) (1 2 3)) (2 3 4))\n",
        "!(test (map-nested (+ 1) (1 (2 3))) (2 (3 4)))\n",
        "!(test (fold-flat + 0 (1 2 3)) 6)\n",
        "!(test (foldr-flat cons () (1 (2 3) 4)) (1 (2 3) 4))\n",
        "!(test (fold-nested + 0 (1 (2 3))) 6)\n",
        "!(test (/=\\ (1 2 $a) (2 3 4)) (2 2))\n",
        "!(test (/==\\ (1 2 3) (2 3 4)) (2 3))\n",
        "!(test (/=a\\ (1 2 $a) (2 $a 4)) (2 $a))\n",
        "!(test (\\= (1 2 3) ($a 3 4)) (2))\n",
        "!(test (\\== (1 2 3) (2 3 4)) (1))\n",
        "!(test (\\=a (1 2 $a) (2 $a 4)) (1))\n",
        "!(test (\\=/ (1 2 3) ($a 3 4)) (2 1 3 4))\n",
        "!(test (\\==/ (1 2 3) (2 3 4)) (1 2 3 4))\n",
        "!(test (\\=a/ (1 2 $a) (2 $a 4)) (1 2 $a 4))\n",
        "!(test (. (+ 1) (* 2) 1) 3)\n",
        "!(test (.: (+ 1) + 2 3) 6)\n",
        "!(test (&&& (+ 2) (* 2) 1) (3 2))\n",
        "(= (mfail $x) (empty))\n",
        "!(test (collapse (&^& (+ 1) (mfail) 1)) (2))\n",
        "!(test (let (@ $lst (cons $h $t)) (1 2 3) ($lst $h $t)) ((1 2 3) 1 (2 3)))\n",
        "!(test (let (head $x) (1 2 3) $x) 1)\n",
        "!(test (let (tail $xs) (1 2 3) $xs) (2 3))\n",
        "!(test (let (mylast $x) (1 2 3) $x) 3)\n",
        "!(test (let (init $xs) (1 2 3) $xs) (1 2))\n",
        "!(test (let (rcons $xs $x) (1 2 3) ($xs $x)) ((1 2) 3))\n",
        "!(test (prog1 (+ 1 1) (+ 2 2)) 2)\n",
        "!(test (progn (+ 1 1) (+ 2 2)) 4)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "roman");
}
