/* Purpose: check roman general operators through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/20-roman_general_operators.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_roman))\n",
        "(: close-enough (-> Number Number Bool))\n",
        "(= (close-enough $a $b) (< (abs-math (- $a $b)) 2))\n",
        "!(test (/?\\ close-enough (1 5 9) (2 100)) (1))\n",
        "!(test (/?\\ close-enough (1 5 9) ()) ())\n",
        "!(test (\\? close-enough (1 5 9) (2 100)) (5 9))\n",
        "!(test (\\? close-enough (1 5 9) ()) (1 5 9))\n",
        "!(test (\\?/ close-enough (1 5 9) (2 100)) (5 9 2 100))\n",
        "!(test (\\?/ close-enough () (2 100)) (2 100))\n",
        "!(test (== (/?\\ == (1 2 3) (2 3 4)) (/==\\ (1 2 3) (2 3 4))) true)\n",
        "!(test (== (\\? == (1 2 3) (2 3 4)) (\\== (1 2 3) (2 3 4))) true)\n",
        "!(test (== (\\?/ == (1 2 3) (2 3 4)) (\\==/ (1 2 3) (2 3 4))) true)\n",
        "!(test (fst (a b)) a)\n",
        "!(test (snd (a b)) b)\n",
        "!(test (cns (1 (2 3))) (1 2 3))\n",
        "!(test (cns ((f 1) ())) ((f 1)))\n",
        "!(test (traceid 42) 42)\n",
        "!(test (tracem \"the answer\" 42) 42)\n",
        "!(test (+ 1 (traceid 41)) 42)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "roman_general_operators");
}
