/* Purpose: check scallop readme through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-01-logic-programs/05-scallop_readme.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(sc-edge 0 1)\n",
        "(sc-edge 1 2)\n",
        "(= (sc-edge-to $a) (match (context-space) (sc-edge $a $b) $b))\n",
        "(= (sc-path-to $a) (sc-edge-to $a))\n",
        "(= (sc-path-to $a) (let $b (sc-edge-to $a) (sc-path-to $b)))\n",
        "(= (sc-paths) (collapse (let $a (match (context-space) (sc-edge $a $_1) $a) (let $b (sc-path-to $a) ($a $b)))))\n",
        "!(test (sc-paths) ((0 1) (0 2) (1 2)))\n",
        "(sc-number 0)\n",
        "(sc-number 1)\n",
        "(sc-number 2)\n",
        "(sc-number 3)\n",
        "(sc-number 4)\n",
        "(sc-number 5)\n",
        "(sc-number 6)\n",
        "(sc-number 7)\n",
        "(sc-number 8)\n",
        "(sc-number 9)\n",
        "(sc-number 10)\n",
        "(= (sc-odd? 1) true)\n",
        "(= (sc-odd? $x) (let $n (match (context-space) (sc-number $x) $x) (sc-odd? (- $n 2))))\n",
        "(= (sc-evens) (collapse (let $y (match (context-space) (sc-number $y) $y) (let true (not-provable (sc-odd? $y)) $y))))\n",
        "!(test (sc-evens) (0 2 4 6 8 10))\n",
        "(sc-object-color 0 \"blue\")\n",
        "(sc-object-color 1 \"green\")\n",
        "(sc-object-color 2 \"blue\")\n",
        "(= (sc-one-color $c) (let $o (match (context-space) (sc-object-color $o $c) $o) 1))\n",
        "(= (sc-color-count $c) (foldall + (sc-one-color $c) 0))\n",
        "(= (sc-color-counts) (collapse (let $c (superpose (\"blue\" \"green\")) ($c (sc-color-count $c)))))\n",
        "!(test (sc-color-counts) ((\"blue\" 2) (\"green\" 1)))\n",
        "(sc-class-student-grade 0 \"tom\" 50)\n",
        "(sc-class-student-grade 0 \"jerry\" 70)\n",
        "(sc-class-student-grade 0 \"alice\" 60)\n",
        "(sc-class-student-grade 1 \"bob\" 80)\n",
        "(sc-class-student-grade 1 \"sherry\" 90)\n",
        "(sc-class-student-grade 1 \"frank\" 30)\n",
        "(= (sc-pick-max $a $b) (if (> $a $b) $a $b))\n",
        "(= (sc-class-max $c) (foldall sc-pick-max (match (context-space) (sc-class-student-grade $c $_1 $g) $g) -1))\n",
        "(= (sc-class-top) (collapse (let $c (superpose (0 1)) (let $g (sc-class-max $c) (let $s (match (context-space) (sc-class-student-grade $c $s $g) $s) ($c $s))))))\n",
        "!(test (sc-class-top) ((0 \"jerry\") (1 \"sherry\")))\n",
        "(sc-is-a giraffe mammal)\n",
        "(sc-is-a tiger mammal)\n",
        "(sc-is-a mammal animal)\n",
        "(sc-name 1 giraffe)\n",
        "(sc-name 1 tiger)\n",
        "(sc-name 2 giraffe)\n",
        "(sc-name 2 tiger)\n",
        "(= (sc-parent-kind $x) (match (context-space) (sc-is-a $x $y) $y))\n",
        "(= (sc-ancestor-kind $x) (sc-parent-kind $x))\n",
        "(= (sc-ancestor-kind $x) (let $y (sc-parent-kind $x) (sc-ancestor-kind $y)))\n",
        "(= (sc-animal-object) (let ($o $kind) (match (context-space) (sc-name $o $kind) ($o $kind)) (let $ancestor (sc-ancestor-kind $kind) (if (== $ancestor animal) $o (empty)))))\n",
        "(= (sc-one-animal) (let $o (unique (sc-animal-object)) 1))\n",
        "(= (sc-animal-count) (foldall + (sc-one-animal) 0))\n",
        "!(test (sc-animal-count) 2)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "scallop_readme");
}
