/* Purpose: check scale through the embedded source interface.
 * Source: examples/ch18-performance/18-01-larger-workloads/01-scale.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (addK $K) (if (== $K 0) done (let* (($K10 (% $K 10)) ($t (add-atom &self (r $K $K10)))) (addK (- $K 1)))))\n",
        "(= (q-all) (collapse (match &self (r $x $y) (r $x $y))))\n",
        "(= (q-first $a) (collapse (match &self (r $a $y) (r $a $y))))\n",
        "(= (q-second $b) (collapse (match &self (r $x $b) (r $x $b))))\n",
        "(= (q-both $a $b) (collapse (match &self (r $a $b) (r $a $b))))\n",
        "(= (q-rel $r) (collapse (match &self ($r 643 3) ($r 643 3))))\n",
        "(= (indexing-demo $K) (let* (($temp (addK $K)) ($all (q-all)) ($first (q-first 7)) ($second (q-second 3)) ($rel (q-rel r)) ($both (q-both 42 2))) (all: (length $all) first: (length $first) second: (length $second) rel: (length $rel) both: (length $both))))\n",
        "!(test (indexing-demo 1000000) (all: 1000000 first: 1 second: 100000 rel: 1 both: 1))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "scale");
}
