/* Purpose: check sealed through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/08-sealed.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (let $atom (sealed () (let $x 2 $x)) (eval $atom)) 2)\n",
        "!(test (let $atom (sealed () (let $y 5 $y)) (eval $atom)) 5)\n",
        "!(test (collapse (let $z 7 (sealed ($z) ($z $w)))) ((7 $unbound)))\n",
        "!(test (sealed () 42) 42)\n",
        "!(test (let $atom (sealed () (let $n 2 (sealed () (let $n 3 $n)))) (let $step (eval $atom) (eval $step))) 3)\n",
        "(= (mk-tagger) (|-> ($item) (sealed ($item) (tagged $item $fresh))))\n",
        "!(test (collapse (let $f (mk-tagger) (superpose (($f 1) ($f 2))))) ((tagged 1 $a) (tagged 2 $b)))\n",
        "!(test (collapse (let $outer 7 (sealed ($outer) (both $outer $local)))) ((both 7 $c)))\n",
        "!(let $rule (sealed () (stored-rule $r ok)) (add-atom &self $rule))\n",
        "!(let $rule (sealed () (stored-rule $r ok)) (add-atom &self $rule))\n",
        "!(test (collapse (match &self (stored-rule $x $y) ($x $y))) (($p ok) ($q ok)))\n",
        "!(test (collapse (let $x 1 (let $y 2 (sealed ($y) (pair $x $y))))) ((pair $fresh 2)))\n",
        "!(test (let $atom (sealed () (+ 1 2)) (eval $atom)) 3)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "sealed");
}
