/* Purpose: check seeking and sizing through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-06-files-and-processes/05-seeking-and-sizing.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_file))\n",
        "!(test (let* (($path (temp-path! \"seek\")) ($written (write-file! $path \"hello world\")) ($handle (file-open! $path \"r\")) ($before (file-get-size! $handle)) ($all (file-read-to-string! $handle)) ($after (file-get-size! $handle)) ($closed (file-close! $handle)) ($gone (delete-file! $path))) ($before $all $after)) (11 \"hello world\" 11))\n",
        "!(test (let* (($path (temp-path! \"seek\")) ($written (write-file! $path \"hello world\")) ($handle (file-open! $path \"r\")) ($first (file-read-to-string! $handle)) ($rewound (file-seek! $handle 0)) ($second (file-read-to-string! $handle)) ($closed (file-close! $handle)) ($gone (delete-file! $path))) ($first $second)) (\"hello world\" \"hello world\"))\n",
        "!(test (let* (($path (temp-path! \"seek\")) ($written (write-file! $path \"hello world\")) ($handle (file-open! $path \"r\")) ($moved (file-seek! $handle 6)) ($tail (file-read-to-string! $handle)) ($closed (file-close! $handle)) ($gone (delete-file! $path))) $tail) \"world\")\n",
        "!(test (let* (($path (temp-path! \"seek\")) ($written (write-file! $path \"hello world\")) ($handle (file-open! $path \"r\")) ($size (file-get-size! $handle)) ($moved (file-seek! $handle $size)) ($rest (file-read-to-string! $handle)) ($again (file-get-size! $handle)) ($closed (file-close! $handle)) ($gone (delete-file! $path))) ($size $rest $again)) (11 \"\" 11))\n",
        "!(test (let* (($path (temp-path! \"seek\")) ($written (write-file! $path \"hello world\")) ($handle (file-open! $path \"r\")) ($first (file-read-exact! $handle 5)) ($moved (file-seek! $handle 6)) ($second (file-read-exact! $handle 5)) ($closed (file-close! $handle)) ($gone (delete-file! $path))) ($first $second)) (\"hello\" \"world\"))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "seeking_and_sizing");
}
