/* Purpose: check segments through the embedded source interface.
 * Source: examples/ch08-data/08-02-sequence-variables/01-segments.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &self (Order 7 x y))\n",
        "!(add-atom &self (Order 8))\n",
        "!(add-atom &self (Order 9 z))\n",
        "!(add-atom &self (Note 1))\n",
        "!(test (collapse (match &self (Order ...) matched)) (matched matched matched))\n",
        "!(test (collapse (match &self (Order 8 (:seg $rest)) $rest)) (()))\n",
        "!(test (collapse (match &self (Order 7 (:seg $rest)) $rest)) ((x y)))\n",
        "!(test (collapse (match &self (Note ...) matched)) (matched))\n",
        "!(test (collapse (let ($pre ... SEP ... $post) (a b SEP c SEP d) ($pre $post))) ((a d) (a d)))\n",
        "!(test (collapse (let (f (:seg $run) mid (:seg $run)) (f a b mid a b) $run)) ((a b)))\n",
        "!(test (collapse (let (f (:seg $run) mid (:seg $run)) (f a b mid c) $run)) ())\n",
        "!(test (case (Order 7 x y) (((Order $id (:seg $rest)) ($id $rest)) ($_2 nope))) (7 (x y)))\n",
        "!(test (unify (f a (:seg $u)) (f a b (:seg $v)) $u none) (b (:seg $v)))\n",
        "!(test (get-metatype (catch (unify (f (:seg $x) a) (f a (:seg $x)) yes no))) Expression)\n",
        "!(add-atom &self (Marked ... tail))\n",
        "!(test (collapse (match &self (Marked $slot tail) $slot)) (...))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "segments");
}
