/* Purpose: check selfprog through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/09-selfprog.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (function1) OK)\n",
        "!(remove-atom &self (= (function1) OK))\n",
        "!(test (repr (function1)) \"(function1)\")\n",
        "!(add-atom &self (= (function1) (OK)))\n",
        "!(test (repr (function1)) \"(OK)\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "selfprog");
}
