/* Purpose: check smartdispatch through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/05-smartdispatch.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f $x) (* $x 2))\n",
        "(= (g $f $x) (justdata $f $x))\n",
        "(= (h $f $x) ($f $x))\n",
        "(= (notjustdata $x) f)\n",
        "(= (datawithnondatacomponent) ((lol (f 42))))\n",
        "!(test ((f 21) (g f 2) (h f 2) ((notjustdata 42) 21) (datawithnondatacomponent)) (42 (justdata f 2) 4 42 ((lol 84))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "smartdispatch");
}
