/* Purpose: check socket lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/40-socket_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_file))\n",
        "!(import! &self (library lib_socket))\n",
        "(: socket-answers (-> Number Number))\n",
        "(= (socket-answers $handle) (superpose (1 2)))\n",
        "!(test (path-join \"one\" \"two\") \"one/two\")\n",
        "!(test (socket-wait! () infinite) ())\n",
        "!(bind! &listener (tcp-listen! (endpoint ipv4 \"127.0.0.1\" 0) 8))\n",
        "!(bind! &address (socket-endpoint &listener local))\n",
        "!(test (socket-kind &listener) listener)\n",
        "!(test (let (endpoint $family $host $port) &address $family) ipv4)\n",
        "!(test (let (endpoint $family $host $port) &address $host) \"127.0.0.1\")\n",
        "!(test (let (endpoint $family $host $port) &address (> $port 0)) true)\n",
        "!(test (socket-wait! (&listener) 0) ())\n",
        "!(bind! &client (tcp-connect! &address))\n",
        "!(test (socket-wait! (&listener) infinite) (&listener))\n",
        "!(bind! &accepted (tcp-accept! &listener))\n",
        "!(test (socket-kind &client) tcp)\n",
        "!(test (socket-kind &accepted) tcp)\n",
        "!(test (socket-endpoint &accepted local) &address)\n",
        "!(test (socket-endpoint &client peer) &address)\n",
        "!(test (socket-endpoint &accepted peer) (socket-endpoint &client local))\n",
        "!(test (file-write-bytes! &client (0 128 255 10)) true)\n",
        "!(test (socket-wait! (&accepted &accepted) infinite) (&accepted &accepted))\n",
        "!(test (file-read-bytes! &accepted 2) (0 128))\n",
        "!(test (file-read-bytes! &accepted 2) (255 10))\n",
        "!(test (socket-shutdown! &client write) true)\n",
        "!(test (file-read-bytes! &accepted) ())\n",
        "!(test (file-write-bytes! &accepted (42)) true)\n",
        "!(test (file-read-bytes! &client 1) (42))\n",
        "!(test (socket-shutdown! &accepted both) true)\n",
        "!(test (file-close! &listener) true)\n",
        "!(test (file-close! &client) true)\n",
        "!(test (file-close! &accepted) true)\n",
        "!(test (file-close! &accepted) true)\n",
        "!(bind! &udp (udp-bind! (endpoint ipv6 \"::1\" 0)))\n",
        "!(bind! &udp-address (socket-endpoint &udp local))\n",
        "!(test (socket-kind &udp) udp)\n",
        "!(test (let (endpoint $family $host $port) &udp-address $family) ipv6)\n",
        "!(test (let (endpoint $family $host $port) &udp-address $host) \"::1\")\n",
        "!(test (socket-wait! (&udp) 0) ())\n",
        "!(test (udp-send! &udp &udp-address (0 255 1)) true)\n",
        "!(test (udp-send! &udp &udp-address ()) true)\n",
        "!(test (socket-wait! (&udp) infinite) (&udp))\n",
        "!(test (udp-receive! &udp) (datagram &udp-address (0 255 1)))\n",
        "!(test (udp-receive! &udp) (datagram &udp-address ()))\n",
        "!(test (if-error (catch (udp-send! &udp &udp-address (256))) refused fine) refused)\n",
        "!(test (socket-wait! (&udp) 0) ())\n",
        "!(test (if-error (catch (udp-send! &udp (endpoint ipv4 \"127.0.0.1\" 1) ())) refused fine) refused)\n",
        "!(test (if-error (catch (socket-endpoint &udp peer)) refused fine) refused)\n",
        "!(test (if-error (catch (tcp-accept! &udp)) refused fine) refused)\n",
        "!(test (if-error (catch (socket-shutdown! &udp write)) refused fine) refused)\n",
        "!(test (file-close! &udp) true)\n",
        "!(test (if-error (catch (socket-kind &udp)) refused fine) refused)\n",
        "!(test (if-error (catch (udp-bind! (endpoint unknown \"127.0.0.1\" 0))) refused fine) refused)\n",
        "!(test (if-error (catch (udp-bind! (endpoint ipv4 \"\" 0))) refused fine) refused)\n",
        "!(test (if-error (catch (udp-bind! (endpoint ipv4 \"127.0.0.1\" 65536))) refused fine) refused)\n",
        "!(test (if-error (catch (tcp-connect! (endpoint ipv4 \"127.0.0.1\" 0))) refused fine) refused)\n",
        "!(test (if-error (catch (tcp-listen! (endpoint ipv4 \"127.0.0.1\" 0) -1)) refused fine) refused)\n",
        "!(test (if-error (catch (socket-wait! () -1)) refused fine) refused)\n",
        "!(test (if-error (catch (transaction (udp-bind! (endpoint ipv4 \"127.0.0.1\" 0)))) refused fine) refused)\n",
        "!(test (collapse (with-socket (udp-bind! (endpoint ipv4 \"127.0.0.1\" 0)) socket-answers)) (1 2))\n",
        "!(test (with-socket (udp-bind! (endpoint ipv4 \"127.0.0.1\" 0)) socket-kind) udp)\n",
        "!(bind! &closed (with-socket (udp-bind! (endpoint ipv4 \"127.0.0.1\" 0)) (lambda $handle $handle)))\n",
        "!(test (if-error (catch (socket-kind &closed)) refused fine) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "socket_lib");
}
