/* Purpose: check soft through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/02-soft.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_measure))\n",
        "!(import! &self (library lib_soft))\n",
        "(similar cat feline 0.8)\n",
        "(similar dog wolf 0.7)\n",
        "!(test (sym-sim cat cat) 1.0)\n",
        "!(test (sym-sim cat feline) 0.8)\n",
        "!(test (sym-sim feline cat) 0.8)\n",
        "!(test (sym-sim cat dog) 0.0)\n",
        "!(test (soft-score (likes cat fish) (likes cat fish)) 1.0)\n",
        "!(test (soft-score (likes feline fish) (likes cat fish)) 0.8)\n",
        "!(test (soft-score (likes feline wolf) (likes cat dog)) 0.7)\n",
        "!(test (soft-score (likes cat) (likes cat fish)) 0.0)\n",
        "!(test (soft-score (likes cat fish) (hates cat fish)) 0.0)\n",
        "!(test (soft-score 3 3) 1.0)\n",
        "!(test (soft-score 3 4) 0.0)\n",
        "!(test (soft-score (= (likes cat $f) $body) (= (likes feline fish) tasty)) 0.8)\n",
        "!(test (soft-score (likes cat (+ 1 2)) (likes feline (+ 1 2))) 0.8)\n",
        "!(test (soft-score $x anything) 1.0)\n",
        "!(test (let $probe (soft-score (likes $who fish) (likes cat fish)) ($probe $who)) (1.0 cat))\n",
        "!(add-atom &zoo (likes cat fish))\n",
        "!(add-atom &zoo (likes dog bones))\n",
        "!(add-atom &zoo (likes bird seeds))\n",
        "!(test (collapse (soft-match &zoo (likes feline fish) 0.5)) ((0.8 (likes cat fish))))\n",
        "!(test (soft-best &zoo (likes feline fish)) (likes cat fish))\n",
        "!(test (let $answers (collapse (soft-match &zoo (likes $x $y) 0.0)) (size-atom $answers)) 3)\n",
        "!(test (< (abs-math (- (ws-total (ws-softmax (collapse (soft-match &zoo (likes feline $f) 0.0)) 1.0)) 1.0)) 1e-9) true)\n",
        "!(test (soft-score (likes cat fish) (likes dog fish)) 0.0)\n",
        "!(test (< (abs-math (- (soft-score-by mean (likes cat fish) (likes dog fish)) 0.6666666666666666)) 1e-9) true)\n",
        "!(test (soft-score-by mean (likes cat fish) (likes cat fish)) 1.0)\n",
        "!(test (soft-aggregation) min)\n",
        "(soft-aggregate mean)\n",
        "!(test (soft-aggregation) mean)\n",
        "!(test (< (abs-math (- (soft-score (likes cat fish) (likes dog fish)) 0.6666666666666666)) 1e-9) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "soft");
}
