/* Purpose: check soft aggregation underneath through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/14-soft_aggregation_underneath.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_soft))\n",
        "(similar cat feline 0.8)\n",
        "(similar fish shark 0.5)\n",
        "!(test (soft-symbol? cat) true)\n",
        "!(test (soft-symbol? min) true)\n",
        "!(test (soft-symbol? 1) false)\n",
        "!(test (soft-symbol? \"text\") false)\n",
        "!(test (soft-symbol? (f 1)) false)\n",
        "!(test (soft-fold min (cat fish) (feline fish)) 0.8)\n",
        "!(test (soft-fold min (cat fish) (feline shark)) 0.5)\n",
        "!(test (soft-fold min (cat fish) (dog fish)) 0.0)\n",
        "!(test (soft-fold mean (cat fish) (feline shark)) 0.65)\n",
        "!(test (soft-fold mean (cat fish) (dog fish)) 0.5)\n",
        "!(test (soft-fold min (cat fish) (dog fish)) 0.0)\n",
        "!(test (soft-walk min (cat fish) (feline shark) 1.0) 0.5)\n",
        "!(test (soft-walk mean (cat fish) (feline shark) 0.0) 1.3)\n",
        "!(test (soft-fold mean (cat fish) (feline shark)) (/ (soft-walk mean (cat fish) (feline shark) 0.0) 2))\n",
        "!(test (soft-walk min (dog whale otter) (cat shark seal) 1.0) 0.0)\n",
        "!(test (soft-walk min (dog whale) (cat shark) 0.0) 0.0)\n",
        "!(test (soft-walk min () () 1.0) 1.0)\n",
        "!(test (soft-walk mean () () 0.0) 0.0)\n",
        "!(test (soft-score (likes cat fish) (likes feline shark)) 0.5)\n",
        "(soft-aggregate mean)\n",
        "!(test (soft-score (likes cat fish) (likes feline shark)) (soft-fold mean (likes cat fish) (likes feline shark)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "soft_aggregation_underneath");
}
