/* Purpose: check sorted constructors through the embedded source interface.
 * Source: examples/ch09-types/24-sorted_constructors.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: SortedPoint (-> Number Number SortedPoint))\n",
        "(= (sorted-x (SortedPoint $x $y)) $x)\n",
        "(= (plain-x (PlainPoint $x $y)) $x)\n",
        "(= (make-sorted-point $x $y) (SortedPoint $x $y))\n",
        "(= (sorted-norm (SortedPoint $x $y)) (sqrt-math (+ (* $x $x) (* $y $y))))\n",
        "!(test (get-type (SortedPoint 3 4)) SortedPoint)\n",
        "!(test (sorted-x (SortedPoint 3 4)) 3)\n",
        "!(test (sorted-norm (SortedPoint 3 4)) 5.0)\n",
        "!(test (make-sorted-point \"bad\" 4) (Error (SortedPoint \"bad\" 4) (BadArgType 1 Number String)))\n",
        "(= (constructor-control $n $sum) (if (== $n 0) $sum (let $x 3 (constructor-control (- $n 1) (+ $sum $x)))))\n",
        "(= (constructor-sorted $n $sum) (if (== $n 0) $sum (let $x (sorted-x (SortedPoint 3 4)) (constructor-sorted (- $n 1) (+ $sum $x)))))\n",
        "(= (constructor-plain $n $sum) (if (== $n 0) $sum (let $x (plain-x (PlainPoint 3 4)) (constructor-plain (- $n 1) (+ $sum $x)))))\n",
        "!(test (constructor-control 20 0) 60)\n",
        "!(test (constructor-sorted 20 0) 60)\n",
        "!(test (constructor-plain 20 0) 60)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "sorted_constructors");
}
