/* Purpose: check sorting and deduplication through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/18-sorting_and_deduplication.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (sort (3 1 2 1)) (1 2 3))\n",
        "!(test (sort-atom (3 1 2 1)) (1 1 2 3))\n",
        "!(test (msort (3 1 2 1)) (1 1 2 3))\n",
        "!(test (sort ()) ())\n",
        "!(test (sort (b a 10 2 \"s\")) (2 10 \"s\" a b))\n",
        "!(test (list_to_set (b a b c a)) (b a c))\n",
        "!(test (list_to_set (3 1 2 1)) (3 1 2))\n",
        "!(test (list_to_set ()) ())\n",
        "!(test (exclude-item 2 (1 2 3 2)) (1 3))\n",
        "!(test (exclude-item x (1 2 3)) (1 2 3))\n",
        "!(test (exclude-item 1 (1 1 1)) ())\n",
        "!(test (collapse (unique (superpose ((f $x) (f $y) (g $z))))) ((f $a) (f $b) (g $c)))\n",
        "!(test (collapse (alpha-unique (superpose ((f $x) (f $y) (g $z))))) ((f $a) (g $b)))\n",
        "!(test (collapse (alpha-unique (superpose (1 2 1 3)))) (1 2 3))\n",
        "!(test (collapse (unique (superpose (1 2 1 3)))) (1 2 3))\n",
        "!(test (collapse (alpha-unique (superpose ((f $x) (f $y) (f 1))))) ((f $a) (f 1)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "sorting_and_deduplication");
}
