/* Purpose: check spaces2 through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/02-spaces2.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(foo 1)\n",
        "(foo 2)\n",
        "(foo 42 42)\n",
        "(foo (42 42))\n",
        "!(bar 42)\n",
        "!(bar 43)\n",
        "(= (answer) 42)\n",
        "!(test (space (msort (collapse (superpose ((match &self (foo $1) (foo $1)) (match &self (foo $1 $2) (foo $1 $2)) (match &self (bar $1) (bar $1)))))) (answer)) (space ((foo 1) (foo 2) (foo 42 42) (foo (42 42))) 42))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces2");
}
