/* Purpose: check spacefunction through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/08-spacefunction.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &self (= (f $x $y) (+ $x $y)))\n",
        "!(add-atom &self (= (g $x $y) (+ $x $y)))\n",
        "!(remove-atom &self (= (f $x $y) (+ $x $y)))\n",
        "!(test (f 3 4) (f 3 4))\n",
        "!(test (g 3 4) 7)\n",
        "!(add-atom &self (my test))\n",
        "!(remove-atom &self (my test))\n",
        "!(test (collapse (match &self (my test) (my test))) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spacefunction");
}
