/* Purpose: check spaces through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/01-spaces.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (matchtrickery) (let* (($t1 (add-atom &self (foo a))) ($t2 (add-atom &self (foo b)))) (match &self (foo $1) (bar $1))))\n",
        "!(test (collapse (matchtrickery)) ((bar a) (bar b)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces");
}
