/* Purpose: check spaces3 through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/03-spaces3.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &wuspace (wu))\n",
        "!(add-atom &wuspace (wu 42))\n",
        "!(test (collapse (match &wuspace ($1) ($1))) ((wu)))\n",
        "!(test (collapse (match &wuspace ($1) (hu $1))) ((hu wu)))\n",
        "!(test (collapse (match &wuspace ($1) $1)) (wu))\n",
        "!(test (msort (collapse (match &wuspace $1 $1))) (msort (collapse (get-atoms &wuspace))))\n",
        "!(test (msort (collapse (match &wuspace $1 (wu $1)))) ((wu (wu)) (wu (wu 42))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces3");
}
