/* Purpose: check spaces lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/20-spaces_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_spaces))\n",
        "!(add-atom &ledger (entry rent 1200))\n",
        "!(add-atom &ledger (entry food 300))\n",
        "!(add-atom &ledger (note \"checked\"))\n",
        "!(test (match-count &ledger (entry $what $amount)) 2)\n",
        "!(test (match-count &ledger (invoice $n)) 0)\n",
        "!(test (find &ledger (entry rent $amount)) true)\n",
        "!(test (find &ledger (entry car $amount)) false)\n",
        "!(test (succeedsPredicate (&ledger entry rent $amount)) true)\n",
        "!(test (sort-atom (collapse (space-copy &ledger &audit (entry $what $amount)))) (true true))\n",
        "!(test (match-count &audit (entry $what $amount)) 2)\n",
        "!(test (match-count &ledger (entry $what $amount)) 2)\n",
        "!(test (sort-atom (collapse (space-copy &ledger &everything $any))) (true true true))\n",
        "!(test (space-atom-count &everything) 3)\n",
        "!(bind! &before (space-snapshot &ledger))\n",
        "!(test (space-atom-count &before) 3)\n",
        "!(add-atom &ledger (entry travel 90))\n",
        "!(test (space-atom-count &before) 3)\n",
        "!(test (space-atom-count &ledger) 4)\n",
        "!(test (collapse (move-atoms &ledger &archive (entry travel $amount))) (true))\n",
        "!(test (collapse (match &archive (entry $what $amount) ($what $amount))) ((travel 90)))\n",
        "!(test (match-count &ledger (entry travel $amount)) 0)\n",
        "!(test (collapse (migrateAtoms &ledger &nowhere (entry food $amount))) ((true true)))\n",
        "!(test (collapse (get-atoms &nowhere)) ())\n",
        "!(test (match-count &ledger (entry food $amount)) 0)\n",
        "!(test (collapse (space-drain &ledger (note $text))) ((note \"checked\")))\n",
        "!(test (collapse (get-atoms &ledger)) ((entry rent 1200)))\n",
        "!(test (sort-atom (collapse (space-subtract &everything &audit))) (true true))\n",
        "!(test (collapse (get-atoms &everything)) ((note \"checked\")))\n",
        "!(test (collapse (space-subtract &everything &audit)) (true true))\n",
        "!(test (collapse (remove-all-atoms &everything)) ((true)))\n",
        "!(test (collapse (get-atoms &everything)) ())\n",
        "!(test (collapse (remove-all-atoms &everything)) (()))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces_lib");
}
