/* Purpose: check spaces removeallatoms through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/06-spaces_removeallatoms.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_spaces))\n",
        "(friend tim tom)\n",
        "(= (f $x) 42)\n",
        "!(remove-all-atoms &self)\n",
        "!(test (collapse (remove-all-atoms &self)) ((remove-all-atoms &self)))\n",
        "!(test (repr (f 42)) \"(f 42)\")\n",
        "!(test (collapse (get-atoms &self)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces_removeallatoms");
}
