/* Purpose: check spaces succeedspredicate through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/05-spaces_succeedspredicate.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_spaces))\n",
        "!(test (succeedsPredicate (&self friend tim tom)) false)\n",
        "(friend a b)\n",
        "!(test (if (succeedsPredicate (&self friend $a $b)) ($a $b) NotFound) (a b))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces_succeedspredicate");
}
