/* Purpose: check spaces find through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-01-a-space-is-where-a-program-lives/04-spaces_find.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_spaces))\n",
        "(friend a b)\n",
        "(friend b c)\n",
        "!(test (collapse (if (find &self (friend $a $b)) (if (find &self (friend $b $c)) (FoundChain $a $b $c) (MissedSecondPiece)) (MissedAllPieces))) ((FoundChain a b c) (MissedSecondPiece)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "spaces_find");
}
