/* Purpose: check specializecyclic through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-02-changing-the-equations/06-specializecyclic.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (f1 $f $a) (if (< $a 0) ($f nevercalled 42) (if (== $a 0) (f2 $f (- $a 1)) finish)))\n",
        "(= (f2 $f $a) (if (< $a 0) ($f nevercalled 42) (f1 $f $a)))\n",
        "!(test (f1 + 2) finish)\n",
        "(= (f3 $f $n) (if (== $n 0) finish (f4 $f $n)))\n",
        "(= (f4 $f $n) (f3 $f (- $n 1)))\n",
        "!(test (f3 + 1) finish)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "specializecyclic");
}
