/* Purpose: check specialize through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-02-changing-the-equations/04-specialize.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (map-flat $f ()) ())\n",
        "(= (map-flat $f (cons $x $xs)) (let $head ($f $x) (let $rest (map-flat $f $xs) (cons $head $rest))))\n",
        "!(test (map-flat (+ 1) (1 2 3)) (2 3 4))\n",
        "(= (map-flat2 (() $f)) ())\n",
        "(= (map-flat2 ((cons $x $xs) $f)) (let $head ($f $x) (let $rest (map-flat2 ($xs $f)) (cons $head $rest))))\n",
        "!(test (map-flat2 ((1 2 3) (+ 1))) (2 3 4))\n",
        "(: map-flat3 (-> Atom %Undefined%))\n",
        "(= (map-flat3 ($f ())) ())\n",
        "(= (map-flat3 ($f (cons $x $xs))) (let $head ($f $x) (let $rest (map-flat3 ($f $xs)) (cons $head $rest))))\n",
        "(= (p1 $x) (+ 1 $x))\n",
        "!(test (map-flat3 (p1 (1 2))) (2 3))\n",
        "(: map-flat4 (-> Atom %Undefined%))\n",
        "(= (map-flat4 ($v ($f ()))) ())\n",
        "(= (map-flat4 ($v ($f (cons $x $xs)))) (let $head ($f $x) (let $rest (map-flat4 ($v ($f $xs))) (cons $head $rest))))\n",
        "!(test (map-flat4 (x (p1 (1 2)))) (2 3))\n",
        "(= (wrapper $f $list) (map-flat $f $list))\n",
        "!(test (wrapper (+ 1) (1 2 3)) (2 3 4))\n",
        "(= (wrapper2 $f) (id $f))\n",
        "!(test (wrapper2 (+ 1)) (+ 1))\n",
        "(= (trickyspec $f) (if (= ($f 1) 2) (trickyspec (+ 2)) ($f 1)))\n",
        "!(test (trickyspec (+ 4)) 5)\n",
        "!(test (trickyspec (+ 1)) 3)\n",
        "(= (fold-nested $f $init ()) $init)\n",
        "(= (fold-nested $f $init (cons $x $xs)) (if (is-expr $x) (fold-nested $f (fold-nested $f $init $x) $xs) (fold-nested $f ($f $init $x) $xs)))\n",
        "!(test (fold-nested + 0 (1 (2 3))) 6)\n",
        "(= (higher-order-fun $a $b) (($a 1) ($b 1)))\n",
        "(= (fun2) (higher-order-fun (+ 1) (* 1)))\n",
        "(= (fun3) (higher-order-fun (* 1) (+ 1)))\n",
        "!(test (fun2) (2 1))\n",
        "!(test (fun3) (1 2))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "specialize");
}
