/* Purpose: check specialize recursive wrap through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-02-changing-the-equations/05-specialize_recursive_wrap.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (derive $g) $g)\n",
        "(= (twice $r $g) ($r ($r $g)))\n",
        "(= (evolve $r $n $g) (if (== $n 0) $g (evolve (twice $r) (- $n 1) $g)))\n",
        "!(test (evolve derive 2 stmt) stmt)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "specialize_recursive_wrap");
}
