/* Purpose: check strategy internals through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-02-metta-written-in-metta/13-strategy_internals.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_strategy))\n",
        "(= (mark $x) (marked $x))\n",
        "!(test (strategy-eval mark a) (marked a))\n",
        "!(test (strategy-eval id a) a)\n",
        "!(test (== (strategy-eval mark a) (strategy-apply mark a)) true)\n",
        "!(test (strategy-choice-tail (fail id mark) (+ 1 2)) (noeval (+ 1 2)))\n",
        "!(test (collapse (strategy-choice-tail () a)) ())\n",
        "!(test (strategy-all mark (h a b)) ((marked h) (marked a) (marked b)))\n",
        "!(test (strategy-all mark leaf) leaf)\n",
        "!(test (strategy-all mark ()) ())\n",
        "!(test (strategy-all-tail mark (a b)) ((marked a) (marked b)))\n",
        "!(test (strategy-all-tail mark ()) ())\n",
        "!(test (== (strategy-all-tail mark (a b)) (cdr-atom (strategy-all mark (h a b)))) true)\n",
        "!(test (collapse (strategy-all-tail mark leaf)) ())\n",
        "!(test (strategy-all mark leaf) leaf)\n",
        "!(test (collapse (strategy-one mark (h a))) (((marked h) a) (h (marked a))))\n",
        "!(test (collapse (strategy-one mark leaf)) ())\n",
        "(: DA Type)\n",
        "(: DS Type)\n",
        "(: da DA)\n",
        "(: preserve (-> DA DA))\n",
        "(= (preserve $x) (kept $x))\n",
        "!(test (strategy-typed-tp preserve da) (kept da))\n",
        "!(test (collapse (strategy-typed-tp preserve 1)) ())\n",
        "(: summarize (-> DA DS))\n",
        "(= (summarize $x) (sum $x))\n",
        "!(test (strategy-typed-tu summarize DS da) (sum da))\n",
        "!(test (collapse (strategy-typed-tu summarize DA da)) ())\n",
        "!(test (strategy-typed-apply preserve DA da) (kept da))\n",
        "!(test (collapse (strategy-typed-apply preserve DA 1)) ())\n",
        "!(test (== (strategy-typed-apply preserve DA da) (◁ preserve TP da)) true)\n",
        "!(test (collapse (strategy-typed-apply preserve DA (undeclared-name))) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "strategy_internals");
}
