/* Purpose: check string lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/18-string_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_string))\n",
        "!(test (string-length \"a🦊é\") 3)\n",
        "!(test (string-slice \"a🦊é\" 1 99) \"🦊é\")\n",
        "!(test (string-split \",;\" \"a,b;;c\") (\"a\" \"b\" \"\" \"c\"))\n",
        "!(test (string-split-exact \"::\" \"::a::::\") (\"\" \"a\" \"\" \"\"))\n",
        "!(test (string-join \" / \" (\"a\" \"b\")) \"a / b\")\n",
        "!(test (string-trim \" \\ta\\r\\n\") \"a\")\n",
        "!(test (string-upper hello) \"HELLO\")\n",
        "!(test (string-lower \"HELLO\") \"hello\")\n",
        "!(test (string-starts-with \"a🦊é\" \"a🦊\") true)\n",
        "!(test (string-ends-with \"a🦊é\" \"é\") true)\n",
        "!(test (string-contains \"a🦊é\" \"🦊\") true)\n",
        "!(test (string-index-of \"banana\" \"ana\") 1)\n",
        "!(test (string-last-index-of \"banana\" \"ana\") 3)\n",
        "!(test (string-count \"aaaaa\" \"aa\") 2)\n",
        "!(test (string-count \"aaaaa\" \"aa\" true) 4)\n",
        "!(test (string-replace \"aaaaa\" \"aa\" \"X\") \"XXa\")\n",
        "!(test (string-replace \"abc\" \"\" \"X\") \"abc\")\n",
        "!(test (string-last-index-of \"a🦊\" \"\") 2)\n",
        "!(test (string-count \"a🦊\" \"\") 3)\n",
        "!(test (string-chars \"a🦊\") (\"a\" \"🦊\"))\n",
        "!(test (string-from-chars (\"ab\" c 42)) \"abc42\")\n",
        "!(test (string-codes \"a🦊\") (97 129418))\n",
        "!(test (string-from-codes (97 129418)) \"a🦊\")\n",
        "!(test (string-codes (string-from-codes (97 0 129418))) (97 0 129418))\n",
        "!(test (string-repeat \"ab\" 3) \"ababab\")\n",
        "!(test (string-pad-left \"x\" 4 \"ab\") \"abax\")\n",
        "!(test (string-pad-right \"x\" 4 \"ab\") \"xaba\")\n",
        "!(test (string-center \"x\" 6 \"ab\") \"abxaba\")\n",
        "!(test (string-lines \"a\\n\\nb\\n\") (\"a\" \"\" \"b\"))\n",
        "!(test (string-unlines (\"a\" \"\" \"b\")) \"a\\n\\nb\\n\")\n",
        "!(test (string-dedent \"  a\\n  b\\n\") \"a\\nb\\n\")\n",
        "!(test (string-indent \"> \" \"a\\n \\nb\\n\") \"> a\\n \\n> b\\n\")\n",
        "!(test (string-wrap \"one two three\" 7) \"one two\\nthree\")\n",
        "!(test (string-wrap \"a b c d\" 4 justify) \"a  b\\nc d\")\n",
        "!(test (string-template \"Dear {Name}: {Value}. {Missing,none}\" (quote ((Name \"Ada\") (Value (age 3))))) \"Dear Ada: (age 3). none\")\n",
        "!(test (string-edit-distance \"kitten\" \"sitting\") 3)\n",
        "!(test (string-similarity \"ab\" \"ac\") 0.5)\n",
        "!(test (string-isub \"language\" \"language\") 1.0)\n",
        "!(test (string-isub \"A.B\" \"ab\" ((normalize true) (zero-to-one true) (substring-threshold 0))) 1.0)\n",
        "!(test (parse-number \"0x10\") 16)\n",
        "!(test (number-to-string 42) \"42\")\n",
        "!(test (collapse (parse-number \"not a number\")) ())\n",
        "!(test (string-repeat 42 2) \"4242\")\n",
        "!(test (string-repeat \"\" 1000000000000000000000000) \"\")\n",
        "!(test (string-center 12 7 3) \"3312333\")\n",
        "!(test (string-center \"x\" 1000000000000000000000000 \"\") \"x\")\n",
        "!(test (string-ends-with \"ab\" \"abc\") false)\n",
        "!(test (if-error (catch (string-repeat \"\" 1.5)) true false) true)\n",
        "!(test (collapse (string-repeat \"x\" (superpose (0 2)))) (\"\" \"xx\"))\n",
        "!(test (let $recipe (match &self (= (string-repeat $value $n) $body) (quote (|-> ($value $n) $body))) (let $function (eval $recipe) ($function \"ab\" 2))) \"abab\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "string_lib");
}
