/* Purpose: check string through the embedded source interface.
 * Source: examples/ch03-atoms-and-expressions/02-string.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test \"a test (with newlines and parentheses)\" \"a test (with newlines and parentheses)\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "string");
}
