/* Purpose: check string comments through the embedded source interface.
 * Source: examples/ch03-atoms-and-expressions/03-string_comments.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test \")\" \")\")\n",
        "!(test \"(\" \"(\")\n",
        "!(test \";\" \";\")\n",
        "!(test (quote \";\") (quote \";\"))\n",
        "!(test \"foo;bar\" \"foo;bar\")\n",
        "!(test \";;;\" \";;;\")\n",
        "!(test \";start\" \";start\")\n",
        "!(test \"end;\" \"end;\")\n",
        "!(test \"quote: \\\"\" \"quote: \\\"\")\n",
        "!(test \"path\\\\file\" \"path\\\\file\")\n",
        "(= (test-func) result)\n",
        "!(test (test-func) result)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "string_comments");
}
