/* Purpose: check subtyping through the embedded source interface.
 * Source: examples/ch09-types/11-subtyping.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: Rex Dog)\n",
        "(:< Dog Animal)\n",
        "!(test (collapse (get-type Rex)) (Dog Animal))\n",
        "(: speak (-> Animal String))\n",
        "(= (speak $a) \"some noise\")\n",
        "!(test (speak Rex) \"some noise\")\n",
        "(:< Animal LivingThing)\n",
        "!(test (collapse (get-type Rex)) (Dog Animal LivingThing))\n",
        "(:< Number Countable)\n",
        "!(test (collapse (get-type 1)) (Number))\n",
        "(: half (-> Number Fraction))\n",
        "(= (half $n) (/ $n 2))\n",
        "(:< Fraction Rational)\n",
        "!(test (collapse (get-type (half 3))) (Fraction))\n",
        "(: ratio (-> Number Number Fraction))\n",
        "!(test (collapse (get-type (ratio 1 2))) (Fraction Rational))\n",
        "(:< Bat Bird)\n",
        "(:< Bat Mammal)\n",
        "(:< Bird Animal2)\n",
        "(:< Mammal Animal2)\n",
        "(: Stellaluna Bat)\n",
        "!(test (collapse (get-type Stellaluna)) (Bat Bird Mammal Animal2 Animal2))\n",
        "(:< (Boxed $t) Container)\n",
        "(: crate (Boxed Apple))\n",
        "!(test (collapse (get-type crate)) ((Boxed Apple) Container))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "subtyping");
}
