/* Purpose: check super through the embedded source interface.
 * Source: examples/ch19-spaces-backed-by-anything/19-01-spaces-of-your-own/04-super.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (store $atom) (stored $atom))\n",
        "!(bind! &guarded (new-space))\n",
        "!(add-atom &guarded (= (store $atom) (if (== $atom bad) refused (super (store $atom)))))\n",
        "!(test (evalc (store good) &guarded) (stored good))\n",
        "!(test (evalc (store bad) &guarded) refused)\n",
        "!(test (store bad) (stored bad))\n",
        "!(bind! &wrapping (new-space))\n",
        "!(add-atom &wrapping (= (car-atom $expr) (wrapped (super (car-atom $expr)))))\n",
        "!(test (evalc (car-atom (1 2 3)) &wrapping) (wrapped 1))\n",
        "!(test (car-atom (1 2 3)) 1)\n",
        "!(test (evalc (store good) &self) (stored good))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "super");
}
