/* Purpose: check superpose primes through the embedded source interface.
 * Source: examples/ch18-performance/18-01-larger-workloads/03-superpose_primes.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (find-divisor $n $test-divisor) (if (> (* $test-divisor $test-divisor) $n) $n (if (== 0 (% $n $test-divisor)) $test-divisor (find-divisor $n (+ $test-divisor 1)))))\n",
        "(= (prime? $n) (== $n (find-divisor $n 2)))\n",
        "!(test (with-pragma! ((max-stack-depth 1000000)) ((prime? 53537257) (prime? 53781811) (prime? 54218443) (prime? 54734431))) (true true true true))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "superpose_primes");
}
