/* Purpose: check supercollapse through the embedded source interface.
 * Source: examples/ch06-many-answers/04-supercollapse.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (TupleConcat $Ev1 $Ev2) (collapse (superpose ((superpose $Ev1) (superpose $Ev2)))))\n",
        "(= (range $K $N) (if (< $K $N) (TupleConcat ($K) (range (+ $K 1) $N)) ()))\n",
        "!(test (range 1 10) (1 2 3 4 5 6 7 8 9))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "supercollapse");
}
