/* Purpose: check superpose nested through the embedded source interface.
 * Source: examples/ch06-many-answers/01-superpose_nested.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (progme) ((collapse (superpose ((superpose (a b c)) (superpose (x y z))))) (collapse (superpose (a b c))) (collapse (superpose ((superpose (a b c))))) (collapse (superpose ((superpose (a b c)) x y z)))))\n",
        "!(test (progme) ((a b c x y z) (a b c) (a b c) (a b c x y z)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "superpose_nested");
}
