/* Purpose: check swi term doors through the embedded source interface.
 * Source: examples/ch08-data/08-01-atoms-lists-and-folds/17-swi_term_doors.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (atom_chars abc) (a b c))\n",
        "!(test (atom_chars \"abc\") (a b c))\n",
        "!(test (size-atom (atom_chars 123)) 3)\n",
        "!(test (== (atom_chars 123) (1 2 3)) false)\n",
        "!(test (atom_concat (car-atom (atom_chars abc)) bc) abc)\n",
        "!(test (atom_concat ab cd) abcd)\n",
        "!(test (atom_concat \"ab\" cd) abcd)\n",
        "!(test (atom_concat ab 1) ab1)\n",
        "!(test (== (atom_concat \"ab\" \"cd\") \"abcd\") false)\n",
        "!(test (=alpha (copy_term (foo $x $y)) (foo $a $b)) true)\n",
        "!(test (let ($p $q) (copy_term ($x $x)) (=? $p $q)) true)\n",
        "!(test (let ($p $q) (copy_term ($x $y)) (== $p $q)) false)\n",
        "!(test (== (term_hash (foo 1)) (term_hash (foo 1))) true)\n",
        "!(test (== (term_hash (foo 1)) (term_hash (foo 2))) false)\n",
        "!(test (== (+ 0 (term_hash (foo 1))) (term_hash (foo 1))) true)\n",
        "!(test (is-ground (foo 1)) true)\n",
        "!(test (is-ground (foo $x)) false)\n",
        "!(test (let $h (term_hash (foo $x)) (is-var $h)) true)\n",
        "!(test (pretty-atom (noeval (= (f 1) (+ 1 1)))) \"(= (f 1) (+ 1 1))\")\n",
        "!(test (== (pretty-atom (noeval (f $x))) (pretty-atom (noeval (f $y)))) true)\n",
        "!(test (pretty-atom 1) \"1\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "swi_term_doors");
}
