/* Purpose: check system lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/31-system_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_system))\n",
        "!(import! &self (library lib_pairs))\n",
        "!(import! &self (library lib_string))\n",
        "!(test (collapse (env-get \"NO_SUCH_VARIABLE_HERE\")) ())\n",
        "!(test (if (== () (collapse (env-get \"NO_SUCH_VARIABLE_HERE\"))) unset set) unset)\n",
        "!(test (env-set! \"METTA_SYSTEM_EXAMPLE\" \"on\") true)\n",
        "!(test (env-get \"METTA_SYSTEM_EXAMPLE\") \"on\")\n",
        "!(test (env-set! \"METTA_SYSTEM_EXAMPLE\" \"\") true)\n",
        "!(test (env-get \"METTA_SYSTEM_EXAMPLE\") \"\")\n",
        "!(test (if (== () (collapse (env-get \"METTA_SYSTEM_EXAMPLE\"))) unset set) set)\n",
        "!(test (env-unset! \"METTA_SYSTEM_EXAMPLE\") true)\n",
        "!(test (collapse (env-get \"METTA_SYSTEM_EXAMPLE\")) ())\n",
        "!(test (env-unset! \"METTA_SYSTEM_EXAMPLE\") true)\n",
        "!(test (env-set! \"METTA_SYSTEM_EXAMPLE\" \"listed\") true)\n",
        "!(test (pairs-is (env-all)) true)\n",
        "!(test (collapse (pairs-lookup (env-all) \"METTA_SYSTEM_EXAMPLE\")) (\"listed\"))\n",
        "!(test (collapse (pairs-lookup (env-all) \"NO_SUCH_VARIABLE_HERE\")) ())\n",
        "!(test (env-unset! \"METTA_SYSTEM_EXAMPLE\") true)\n",
        "!(test (platform-info family) \"unix\")\n",
        "!(test (platform-info dialect) \"swi\")\n",
        "!(test (== (platform-info cores) (platform-info cores)) true)\n",
        "!(test (size-atom (platform-info version-numbers)) 3)\n",
        "!(test (size-atom (platform-keys)) 10)\n",
        "!(test (if-error (catch (platform-info nosuch)) refused fine) refused)\n",
        "!(test (string-starts-with (platform-info version) (number-to-string (car-atom (platform-info version-numbers)))) true)\n",
        "!(test (string-starts-with (working-directory) \"/\") true)\n",
        "!(test (string-ends-with (working-directory) \"/\") false)\n",
        "!(test (if-error (catch (change-directory! \"/no/such/directory/here\")) refused fine) refused)\n",
        "!(test (string-starts-with (working-directory) \"/\") true)\n",
        "!(test (if-error (catch (env-get 7)) refused fine) refused)\n",
        "!(test (if-error (catch (env-set! \"A\" (nosuch))) refused fine) refused)\n",
        "!(test (if-error (catch (change-directory! 7)) refused fine) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "system_lib");
}
