/* Purpose: check tabling doors through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/18-tabling_doors.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_tabling))\n",
        "!(import! &self (library lib_spaces))\n",
        "!(add-atom &self (edge a b))\n",
        "(= (reach $x $y) (match &self (edge $x $y) $y))\n",
        "!(tabled (reach $x $y))\n",
        "!(test (collapse (reach a $y)) (b))\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 1) (complete-call 1) (invalidated 0) (reevaluated 0) (policy (incremental shared))))\n",
        "!(test (untabled (reach $x $y)) true)\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 0) (complete-call 1) (invalidated 0) (reevaluated 0)))\n",
        "!(test (tabled (reach $x $y)) true)\n",
        "!(test (tabled (reach $x $y)) true)\n",
        "!(test (index-atom (table-stats (reach $x $y)) 5) (policy (incremental shared)))\n",
        "!(test (collapse (reach a $y)) (b))\n",
        "!(test (table-clear-all) true)\n",
        "!(test (index-atom (table-stats (reach $x $y)) 1) (answers 0))\n",
        "!(test (metta_untabled_decl (quote (reach $x $y))) true)\n",
        "!(test (metta_tabled_decl (quote (reach $x $y))) true)\n",
        "!(test (collapse (reach a $y)) (b))\n",
        "!(test (== (metta_table_statistics (quote (reach $x $y))) (table-stats (reach $x $y))) true)\n",
        "!(test (metta_table_clear (quote (reach $x $y))) true)\n",
        "!(test (index-atom (metta_table_statistics (quote (reach $x $y))) 1) (answers 0))\n",
        "!(test (metta_table_clear_all) true)\n",
        "!(test (injectPrologCode \"metta_doors_greeting(world).\") true)\n",
        "!(test (succeedsPredicate (metta_doors_greeting world)) true)\n",
        "!(test (succeedsPredicate (metta_doors_greeting mars)) false)\n",
        "!(test (injectPrologCode \"metta_doors_add(X, Y) :- Y is X + 1.\") true)\n",
        "!(test (succeedsPredicate (metta_doors_add 41 42)) true)\n",
        "!(test (succeedsPredicate (metta_doors_add 41 43)) false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "tabling_doors");
}
