/* Purpose: check tabling fib through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/09-tabling_fib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_tabling))\n",
        "(= (fib $N) (if (< $N 2) $N (+ (fib (- $N 1)) (fib (- $N 2)))))\n",
        "!(tabled (fib $N))\n",
        "!(test (fib 30) 832040)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "tabling_fib");
}
