/* Purpose: check tabling space write through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/11-tabling_space_write.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_tabling))\n",
        "!(add-atom &self (edge a b))\n",
        "!(add-atom &self (edge b c))\n",
        "(= (reach $x $y) (match &self (edge $x $y) $y))\n",
        "(= (twohop $x $z) (match &self (, (edge $x $y) (edge $y $z)) $z))\n",
        "!(tabled (reach $x $y))\n",
        "!(tabled (twohop $x $z))\n",
        "!(test (collapse (reach a $y)) (b))\n",
        "!(test (collapse (twohop a $z)) (c))\n",
        "!(add-atom &self (edge a c))\n",
        "!(test (sort-atom (collapse (reach a $y))) (b c))\n",
        "!(remove-atom &self (edge a b))\n",
        "!(test (collapse (reach a $y)) (c))\n",
        "!(add-atom &self (edge c d))\n",
        "!(test (collapse (twohop b $z)) (d))\n",
        "(= (bypattern $p) (match &self $p $p))\n",
        "!(test (repr (catch (tabled (bypattern $p)))) \"(Error (metta_tabling_unresolved_read match $_0) none)\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "tabling_space_write");
}
