/* Purpose: check tabling statistics through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/12-tabling_statistics.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_tabling))\n",
        "!(add-atom &self (edge a b))\n",
        "(= (reach $x $y) (match &self (edge $x $y) $y))\n",
        "!(tabled (reach $x $y))\n",
        "!(collapse (reach a $y))\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 1) (complete-call 1) (invalidated 0) (reevaluated 0) (policy (incremental shared))))\n",
        "!(add-atom &self (edge b d))\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 1) (complete-call 1) (invalidated 0) (reevaluated 0) (policy (incremental shared))))\n",
        "!(add-atom &self (unrelated x y))\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 1) (complete-call 1) (invalidated 0) (reevaluated 0) (policy (incremental shared))))\n",
        "!(add-atom &self (edge a c))\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 1) (complete-call 1) (invalidated 1) (reevaluated 0) (policy (incremental shared))))\n",
        "!(test (sort-atom (collapse (reach a $y))) (b c))\n",
        "!(test (table-stats (reach $x $y)) ((tables 1) (answers 2) (complete-call 2) (invalidated 1) (reevaluated 1) (policy (incremental shared))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "tabling_statistics");
}
