/* Purpose: check tabling equation change through the embedded source interface.
 * Source: examples/ch18-performance/18-02-memoisation-and-tabling/10-tabling_equation_change.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_tabling))\n",
        "(= (pick $x) one)\n",
        "!(tabled (pick $x))\n",
        "!(test (collapse (pick a)) (one))\n",
        "!(test (collapse (pick a)) (one))\n",
        "(= (pick $x) two)\n",
        "!(test (sort-atom (collapse (pick a))) (one two))\n",
        "!(remove-atom &self (= (pick $x) one))\n",
        "!(test (collapse (pick a)) (two))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "tabling_equation_change");
}
