/* Purpose: check take through the embedded source interface.
 * Source: examples/ch07-control-flow/07-04-bounded-and-committed-searches/03-take.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (collapse (take 3 (superpose (a b c d e)))) (a b c))\n",
        "!(test (collapse (take 9 (superpose (a b)))) (a b))\n",
        "!(test (collapse (take 0 (superpose (a b)))) ())\n",
        "(= (from $n) (superpose ($n (from (+ $n 1)))))\n",
        "!(test (collapse (take 4 (from 0))) (0 1 2 3))\n",
        "!(test (let $refusal (catch (take foo (superpose (a b)))) (car-atom $refusal)) Error)\n",
        "(edge a b)\n",
        "(edge b c)\n",
        "(edge c d)\n",
        "!(test (collapse (take 2 (match &self (edge $x $y) (edge $x $y)))) ((edge a b) (edge b c)))\n",
        "!(test (collapse (take 2 (match &self (, (edge $x $y) (edge $y $z)) ($x $z)))) ((a c) (b d)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "take");
}
