/* Purpose: check testing lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/43-testing_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_combinatorics))\n",
        "!(import! &self (library lib_testing))\n",
        "!(test (collapse (range -2 3)) (-2 -1 0 1 2))\n",
        "!(test (collapse (range 3 4)) (3))\n",
        "!(test (collapse (range 3 3)) ())\n",
        "!(test (collapse (range 100000000000000000000 100000000000000000003)) (100000000000000000000 100000000000000000001 100000000000000000002))\n",
        "!(test (collapse (superpose (a a \"π\"))) (a a \"π\"))\n",
        "!(test (collapse (superpose ())) ())\n",
        "!(test (size-atom (index-atom (quote ((+ 1 2))) 0)) 3)\n",
        "!(test (collapse (index-atom (()) 0)) (()))\n",
        "!(test (let $items (collapse (range 1 4)) (collapse (index-atom $items (range 0 (size-atom $items))))) (1 2 3))\n",
        "!(test (collapse (cartesian-power (0 1) 0)) (()))\n",
        "!(test (collapse (cartesian-power (0 1) 2)) ((0 0) (0 1) (1 0) (1 1)))\n",
        "!(test (collapse (cartesian-power (a a) 2)) ((a a) (a a) (a a) (a a)))\n",
        "!(test (collapse (cartesian-power () 0)) (()))\n",
        "!(test (collapse (cartesian-power () 2)) ())\n",
        "!(test (collapse (let* (($population (collapse (range 0 2))) ($length (range 0 3))) (cartesian-power $population $length))) (() (0) (1) (0 0) (0 1) (1 0) (1 1)))\n",
        "!(test (collapse (cartesian-power (0 1) (range 2 2))) ())\n",
        "!(test (let $choice (index-atom ((row $x $x)) 0) (let $pair (map-atom (1 2) $ignored (copy_term (quote $choice))) (=alpha $pair ((row $a $a) (row $b $b))))) true)\n",
        "!(test (collapse (cartesian-power (() (a)) 1)) ((()) ((a))))\n",
        "!(forall (range -3 4) (|-> ($x) (test (>= (* $x $x) 0) true)))\n",
        "!(forall (cartesian-power (0 1) (range 0 4)) (|-> ($xs) (test (reverse (reverse $xs)) $xs)))\n",
        "!(test (forall (range 0 5) (<= 0)) true)\n",
        "!(test (foldall (|-> ($value $count) (+ $count 1)) (superpose (a a b)) 0) 3)\n",
        "!(test (forall (superpose ()) (|-> ($x) false)) true)\n",
        "!(test (foldall (|-> ($value $count) (+ $count 1)) (superpose ()) 0) 0)\n",
        "!(forall (range 1 3) (|-> ($x) (assertEqualToResult (superpose (2 1 1)) (1 2 1))))\n",
        "!(forall (range 1 3) (|-> ($x) (assertEqualToResult (empty) ())))\n",
        "!(forall (index-atom (quote ((+ 1 2))) 0) (|-> ($value) (assertEqualToResult (quote $value) ((+ 1 2)))))\n",
        "!(forall (index-atom ((row $x $x)) 0) (|-> ($value) (test (=alpha $value (row $y $y)) true)))\n",
        "!(test (once (let $x (range 0 6) (if (>= $x 3) $x (empty)))) 3)\n",
        "!(test (collapse (once (let $x (range 0 6) (if (>= $x 3) $x (empty))))) (3))\n",
        "!(test (collapse (once (let $x (range 0 3) (if (>= $x 3) $x (empty))))) ())\n",
        "!(test (collapse (once (superpose ()))) ())\n",
        "!(test (once (let $x (range 0 6) (if (== (sort-atom (collapse (superpose (2 1 1)))) (1 1 2)) $x (empty)))) 0)\n",
        "!(test (size-atom (once (index-atom (quote ((+ 1 2))) 0))) 3)\n",
        "!(test (collapse (once (let $x (index-atom (() (a)) (range 0 2)) (if (== (size-atom $x) 0) $x (empty))))) (()))\n",
        "!(forall (range 0 3) (|-> ($x) (test (once (let $y (range 0 3) (if (== $x $y) $y (empty)))) $x)))\n",
        "!(test (foldall (|-> ($x $count) (let $checked (test (>= $x 0) true) (+ $count 1))) (range 0 3) 0) 3)\n",
        "!(test (forall (range 0 2) (|-> ($x) (superpose (false true)))) true)\n",
        "!(test (forall (range 0 2) (|-> ($x) (empty))) false)\n",
        "!(test (forall (range 0 2) (|-> ($x) 7)) false)\n",
        "!(test (let $error (catch (assertEqualToResult (superpose (1 1)) (1 2))) (unify $error (Error $ball $context) (repr $ball) no-error)) \"(metta_assertion_failed (assertEqualToResult (superpose (1 1)) (1 2)) (2) (1))\")\n",
        "!(test (if-error (catch (cartesian-power (a) -1)) refused fine) refused)\n",
        "!(test (if-error (catch (cartesian-power (a) 1.5)) refused fine) refused)\n",
        "!(test (let $value (once (unify $x 3 $x (empty))) $x) 3)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "testing_lib");
}
