/* Purpose: check tests through the embedded source interface.
 * Source: examples/ch06-many-answers/07-tests.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (program1 $Y) (let $X $Y (collapse (superpose (12 (+ $X 4))))))\n",
        "(= (program2 $Y) (let $list (let $L (1 2 3) (collapse (superpose $L))) (superpose $list)))\n",
        "(= (program3 $x) (if (== $x 2) (let $z (superpose ((if (< $x 10) (superpose ((42 43))) 43))) $z) (let $z 4 $z)))\n",
        "(= (program4) (collapse ((program1 42) (program2 42) (program3 2))))\n",
        "!(test (program4) (((12 46) 1 (42 43)) ((12 46) 2 (42 43)) ((12 46) 3 (42 43))))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "tests");
}
