/* Purpose: check text lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/03-text_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_string))\n",
        "!(import! &self (library lib_file))\n",
        "!(test (string-length \"hello\") 5)\n",
        "!(test (string-slice \"hello world\" 0 5) \"hello\")\n",
        "!(test (string-slice \"hello\" 3 999) \"lo\")\n",
        "!(test (string-slice \"hello\" 99 120) \"\")\n",
        "!(test (string-split \",\" \"a,b,c\") (\"a\" \"b\" \"c\"))\n",
        "!(test (string-join \", \" (\"a\" \"b\" \"c\")) \"a, b, c\")\n",
        "!(test (string-trim \"  padded  \") \"padded\")\n",
        "!(test (string-upper \"shout\") \"SHOUT\")\n",
        "!(test (string-lower \"QUIET\") \"quiet\")\n",
        "!(test (string-starts-with \"hello\" \"he\") true)\n",
        "!(test (string-ends-with \"hello\" \"lo\") true)\n",
        "!(test (string-contains \"hello\" \"ell\") true)\n",
        "!(test (string-contains \"hello\" \"zzz\") false)\n",
        "!(test (string-index-of \"hello\" \"l\") 2)\n",
        "!(test (string-index-of \"hello\" \"z\") -1)\n",
        "!(test (string-replace \"banana\" \"a\" \"X\") \"bXnXnX\")\n",
        "!(test (string-chars \"abc\") (\"a\" \"b\" \"c\"))\n",
        "!(test (string-from-chars (\"a\" \"b\" \"c\")) \"abc\")\n",
        "!(test (string-repeat \"ab\" 3) \"ababab\")\n",
        "!(test (string-pad-left \"7\" 3 \"0\") \"007\")\n",
        "!(test (string-pad-right \"7\" 3 \".\") \"7..\")\n",
        "!(test (format-args \"Probability of {} is {}%\" (head 50)) \"Probability of head is 50%\")\n",
        "!(test (format-args \"{} and {}\" (\"only\")) \"only and \")\n",
        "!(test (sort-strings (\"pear\" \"apple\" \"fig\")) (\"apple\" \"fig\" \"pear\"))\n",
        "!(test (parse-number \"42\") 42)\n",
        "!(test (number-to-string 42) \"42\")\n",
        "!(test (string-length hello) 5)\n",
        "!(test (string-upper hello) \"HELLO\")\n",
        "!(bind! &scratch (temp-path! \"metta-text-example\"))\n",
        "!(test (write-file! &scratch \"one\\ntwo\\nthree\\n\") true)\n",
        "!(test (read-file! &scratch) \"one\\ntwo\\nthree\\n\")\n",
        "!(test (file-lines! &scratch) (\"one\" \"two\" \"three\"))\n",
        "!(test (append-file! &scratch \"four\\n\") true)\n",
        "!(test (file-lines! &scratch) (\"one\" \"two\" \"three\" \"four\"))\n",
        "!(test (let $h (file-open! &scratch \"r\") (let $head (file-read-exact! $h 3) (let $_2 (file-close! $h) $head))) \"one\")\n",
        "!(test (let $log (file-space! &scratch) (collapse (match $log (line $n $t) ($n $t)))) ((1 \"one\") (2 \"two\") (3 \"three\") (4 \"four\")))\n",
        "!(test (let $log (file-space! &scratch) (collapse (match $log (line 2 $t) $t))) (\"two\"))\n",
        "!(test (delete-file! &scratch) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "text_lib");
}
