/* Purpose: check the clock and the command line through the embedded source interface.
 * Source: examples/ch14-seeing-your-program/03-the_clock_and_the_command_line.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_string))\n",
        "!(test (> (current-time) 1700000000.0) true)\n",
        "!(test (<= (current-time) (current-time)) true)\n",
        "!(test (format-time \"abc\") abc)\n",
        "!(test (== (format-time \"abc\") \"abc\") false)\n",
        "!(test (string-length (format-time \"a literal\")) 9)\n",
        "!(test (string-length (format-time \"\")) 0)\n",
        "!(test (string-length (format-time \"%%\")) 1)\n",
        "!(test (string-length (format-time \"%Y\")) 4)\n",
        "!(test (string-length (format-time \"%Y-%m-%d\")) 10)\n",
        "!(test (string-length (format-time \"%H:%M:%S\")) 8)\n",
        "!(test (collapse (argv 999)) ())\n",
        "!(test (collapse (argv -1)) ())\n",
        "!(test (== (argv 0) (argv 0)) true)\n",
        "(= (argument-or $index $default) (let $found (collapse (argv $index)) (if (== $found ()) $default (car-atom $found))))\n",
        "!(test (argument-or 999 no-such-argument) no-such-argument)\n",
        "!(test (== (argument-or 0 no-such-argument) no-such-argument) false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "the_clock_and_the_command_line");
}
