/* Purpose: check the module doors through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-03-prolog-underneath/05-the-module-doors.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_import))\n",
        "!(import! &self (library lib_zar))\n",
        "!(import! &self (library lib_file))\n",
        "!(test (consult_file \"./fixtures/prolog/rung_functions.pl\") true)\n",
        "!(test (import_prolog_functions (noeval (rung_double rung_greeting))) true)\n",
        "!(test (rung_double 21) 42)\n",
        "!(test (use_module_file \"./fixtures/prolog/rung_module.pl\") true)\n",
        "!(test (import_prolog_functions (noeval (rung_module_triple))) true)\n",
        "!(test (rung_module_triple 14) 42)\n",
        "!(test (let $reported (catch (import_prolog_functions (noeval (rung_module_hidden)))) (unify $reported (Error $ball $context) (car-atom $ball) no-error)) existence_error)\n",
        "!(test (let \"./fixtures/prolog/rung_global.pl\" (use_module_global) loaded) loaded)\n",
        "!(test (import_prolog_functions_from_module \"./fixtures/prolog/rung_global.pl\" (rung_global_six)) true)\n",
        "!(test (rung_global_six 7) 42)\n",
        "!(test (import_prolog_functions_from_file_pred \"./fixtures/prolog/rung_pred_file.pl\" (rung_pred_quad)) true)\n",
        "!(test (rung_pred_quad 10) 40)\n",
        "!(test (import_prolog_functions_from_module_pred \"./fixtures/prolog/rung_pred_module.pl\" (rung_pred_five)) true)\n",
        "!(test (rung_pred_five 10) 50)\n",
        "!(test (use-module! lists) true)\n",
        "!(test (static-import! &self \"fixtures/prolog/static_rows\") true)\n",
        "!(test (sort-atom (collapse (match &self (city $c france) $c))) (lyon paris))\n",
        "!(test (collapse (match &self (population paris $n) $n)) (2100000))\n",
        "!(test (file-exists \"./fixtures/prolog/static_rows.tokens-v1.pl\") true)\n",
        "!(test (file-exists \"./fixtures/prolog/static_rows.tokens-v1.qlf\") true)\n",
        "!(delete-file! \"./fixtures/prolog/static_rows.tokens-v1.pl\")\n",
        "!(delete-file! \"./fixtures/prolog/static_rows.tokens-v1.qlf\")\n",
        "!(test (file-exists \"./fixtures/prolog/static_rows.tokens-v1.pl\") false)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "the_module_doors");
}
