/* Purpose: check the measure algebra underneath through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/13-the_measure_algebra_underneath.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_measure))\n",
        "!(test (ws-ranked ((0.2 low) (0.7 high) (0.1 mid))) ((0.7 high) (0.2 low) (0.1 mid)))\n",
        "!(test (ws-ranked ()) ())\n",
        "!(test (ws-take ((0.7 high) (0.2 low) (0.1 mid)) 2) ((0.7 high) (0.2 low)))\n",
        "!(test (ws-take ((0.7 high)) 5) ((0.7 high)))\n",
        "!(test (ws-take ((0.7 high) (0.2 low)) 0) ())\n",
        "!(test (ws-take () 2) ())\n",
        "!(test (== (ws-top ((0.2 low) (0.7 high) (0.1 mid)) 2) (ws-take (ws-ranked ((0.2 low) (0.7 high) (0.1 mid))) 2)) true)\n",
        "!(test (ws-pickmax (0.2 a) (0.7 b)) (0.7 b))\n",
        "!(test (ws-pickmax (0.7 b) (0.2 a)) (0.7 b))\n",
        "!(test (ws-pickmax (0.5 a) (0.5 b)) (0.5 a))\n",
        "!(test (ws-sample-walk ((0.5 a) (0.3 b) (0.2 c)) 0.1) a)\n",
        "!(test (ws-sample-walk ((0.5 a) (0.3 b) (0.2 c)) 0.6) b)\n",
        "!(test (ws-sample-walk ((0.5 a) (0.3 b) (0.2 c)) 0.9) c)\n",
        "!(test (ws-sample-walk ((0.5 a) (0.5 b)) 1.5) b)\n",
        "!(test (ws-merge-into () (0.3 x)) ((0.3 x)))\n",
        "!(test (ws-merge-into ((0.3 x) (0.4 y)) (0.2 x)) ((0.5 x) (0.4 y)))\n",
        "!(test (ws-merge-into ((0.3 x)) (0.2 z)) ((0.3 x) (0.2 z)))\n",
        "!(test (== (ws-collapse ((0.3 x) (0.4 y) (0.2 x))) (ws-merge-into (ws-merge-into (ws-merge-into () (0.3 x)) (0.4 y)) (0.2 x))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "the_measure_algebra_underneath");
}
