/* Purpose: check the prolog rung under lib thread through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/06-the_prolog_rung_under_lib_thread.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_thread))\n",
        "(: inc (-> Number Number))\n",
        "(= (inc $x) (+ $x 1))\n",
        "(: big? (-> Number Bool))\n",
        "(= (big? $x) (> $x 2))\n",
        "!(test (par_map inc (1 2 3)) (2 3 4))\n",
        "!(test (par_filter big? (1 2 3 4)) (3 4))\n",
        "!(test (par_forall big? (3 4)) true)\n",
        "!(test (par_forall big? (1 4)) false)\n",
        "!(test (par_any big? (1 9)) true)\n",
        "!(test (par_any big? (1 2)) false)\n",
        "!(test (== (par_map inc (1 2 3)) (par-map inc (1 2 3))) true)\n",
        "!(test (par_race ((inc 41) (inc 41))) 42)\n",
        "!(test (let $f (thread_spawn (inc 41)) (thread_await $f)) 42)\n",
        "!(test (let $f (thread_spawn (inc 41)) (let $_1 (thread_await $f) (thread_settled $f))) true)\n",
        "!(test (let $f (thread_spawn (let $_1 (sleep 30) 1)) (let $running (thread_settled $f) (let $__ (thread_cancel $f) $running))) false)\n",
        "!(test (let $c (channel_new) (let $_1 (channel_send $c hi) (channel_recv $c))) hi)\n",
        "!(test (let $c (channel_new) (let $_1 (channel_send $c hi) (channel_size $c))) 1)\n",
        "!(test (let $c (channel_new) (collapse (channel_try_recv $c))) ())\n",
        "!(test (let $c (channel_new) (let $_1 (channel_send $c hi) (collapse (channel_try_recv $c)))) (hi))\n",
        "!(test (let $c (channel_new) (channel_close $c)) true)\n",
        "!(test (let $p (pool_create rung-pool 2) (let $h (pool_submit rung-pool (inc 9)) (thread_await $h))) 10)\n",
        "!(test (pool_stats rung-pool) ((size 2) (running 0) (backlog 0) (free 2)))\n",
        "!(test (pool_destroy rung-pool) true)\n",
        "!(test (collapse (thread_await (timer_after 0.05 (inc 41)))) (42))\n",
        "!(test (let $t (timer_every 0.05 (inc 41)) (let $_1 (sleep 0.2) (let $__ (thread_cancel $t) stopped))) stopped)\n",
        "!(test (collapse (with_lock rung-lock (superpose (1 2 3)))) (1 2 3))\n",
        "!(add-atom &rung-jobs (job 7))\n",
        "!(test (space_await &rung-jobs (job $n)) (job 7))\n",
        "!(test (space_await &rung-jobs (job $n)) (job 7))\n",
        "!(test (space_take &rung-jobs (job $n)) (job 7))\n",
        "!(test (collapse (get-atoms &rung-jobs)) ())\n",
        "!(add-atom &rung-work (job 2))\n",
        "!(add-atom &rung-work (job 9))\n",
        "!(test (space_await_where &rung-work (job $n) (> $n 5)) (job 9))\n",
        "!(test (space_take_where &rung-work (job $n) (> $n 5)) (job 9))\n",
        "!(test (collapse (get-atoms &rung-work)) ((job 2)))\n",
        "!(test (collapse (space_take_where &rung-work (job $n) (> $n 100) 0.05)) ())\n",
        "!(test (collapse (get-atoms &rung-work)) ((job 2)))\n",
        "!(test (> (cpu_count) 0) true)\n",
        "!(test (> (thread_count) 0) true)\n",
        "!(test (== (cpu_count) (cpu-count)) true)\n",
        "!(test (== (thread_count) (thread-count)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "the_prolog_rung_under_lib_thread");
}
