/* Purpose: check the two sided fragments through the embedded source interface.
 * Source: examples/ch08-data/08-02-sequence-variables/04-the-two-sided-fragments.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (unify (f a b) (f a (:seg $v)) $v none) (b))\n",
        "!(test (unify (f a b) (f a b (:seg $v)) $v none) ())\n",
        "!(test (unify (f a (:seg $u)) (f a b (:seg $v)) $u none) (b (:seg $v)))\n",
        "!(test (unify (f (:seg $u)) (f (:seg $v)) $u none) ((:seg $v)))\n",
        "!(test (unify (f ...) (f (:seg $v)) taken none) taken)\n",
        "!(test (unify (f (g (:seg $x)) (h (:seg $x))) (f (g (:seg $y)) (h b)) $x none) (b))\n",
        "!(test (unify (f (:seg $u)) (f (:seg $u)) yes no) yes)\n",
        "!(test (collapse (unify (f a b) (f a b (:seg $v)) $v none)) (()))\n",
        "!(test (unify (f (:seg $u) b) (f a (:seg $v)) ($u $v) no) ((a) (b)))\n",
        "!(test (unify (f (:seg $u) (g a)) (f (g b) (:seg $v)) ($u $v) no) (((g b)) ((g a))))\n",
        "!(test (collapse (unify (f (:seg $u) b) (f a (:seg $v)) ($u $v) no)) (((a) (b))))\n",
        "!(add-atom &self (friend Bob Alice))\n",
        "!(add-atom &self (friend Carol Alice))\n",
        "!(test (collapse (unify &self (friend (:seg $who)) $who none)) ((Bob Alice) (Carol Alice)))\n",
        "!(test (collapse (match &self (friend (:seg $who)) $who)) ((Bob Alice) (Carol Alice)))\n",
        "!(test (if-error (catch (unify (f (:seg $x) a) (f a (:seg $x)) yes no)) refused answered) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "the_two_sided_fragments");
}
