/* Purpose: check the fence through the embedded source interface.
 * Source: examples/ch08-data/08-02-sequence-variables/05-the-fence.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &self (Order 7 x y))\n",
        "!(test (if-error (catch (match &self (Order (:seg $m) $m) hit)) refused answered) refused)\n",
        "!(test (let $refusal (catch (match &self (Order (:seg $m) $m) hit)) (car-atom (index-atom $refusal 1))) metta_seq_outside_fragment)\n",
        "!(test (let $refusal (catch (match &self (Order (:seg $m) $m) hit)) (index-atom (index-atom $refusal 1) 4)) mixed_roles)\n",
        "!(test (let $refusal (catch (match &self (Order (:seg $m) $m) hit)) (index-atom (index-atom $refusal 1) 1)) (Order (:seg $m) $m))\n",
        "!(test (let $refusal (catch (match &self (Order (:seg $m) $m) hit)) (index-atom (index-atom $refusal 1) 3)) ($m))\n",
        "!(test (case (Order 8) (((Order 8) plain) ((Order (:seg $m) $m) never) ($_1 other))) plain)\n",
        "!(test (collapse (match &self (Order (:seg $run) $last) (pair $run $last))) ((pair (7 x) y)))\n",
        "!(test (collapse (let (Order (:seg $run) $last) (Order (x y) (x y)) (if (== $run ($last)) same different))) (same))\n",
        "(= (echoes ((:seg $xs) tag $xs)) yes)\n",
        "!(test (echoes (a b tag (a b))) yes)\n",
        "!(test (if-error (catch (unify (f (g (:seg $u) b)) (f (g a (:seg $v))) yes no)) refused answered) refused)\n",
        "!(test (let $refusal (catch (unify (f (g (:seg $u) b)) (f (g a (:seg $v))) yes no)) (index-atom (index-atom $refusal 1) 4)) no_certificate)\n",
        "!(test (let $refusal (catch (unify (f (:seg $x) a) (f a (:seg $x)) yes no)) (index-atom (index-atom $refusal 1) 4)) no_certificate)\n",
        "!(test (let $refusal (catch (unify (f (:seg $x) a) (f a (:seg $x)) yes no)) (index-atom (index-atom $refusal 1) 3)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "the_fence");
}
