/* Purpose: check thin forms through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/04-thin_forms.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test-no-answer (superpose ()))\n",
        "!(test (collapse (superpose ())) ())\n",
        "!(test (collapse ()) (()))\n",
        "!(test (prog1 (+ 1 1) (+ 2 2) (+ 3 3)) 2)\n",
        "!(test (progn (+ 1 1) (+ 2 2) (+ 3 3)) 6)\n",
        "!(test (collapse (transaction (progn (add-atom &self (tx-rolled a)) (superpose ())))) ())\n",
        "!(test (collapse (match &self (tx-rolled $x) $x)) ())\n",
        "!(test (collapse (transaction (add-atom &self (tx-kept a)))) (true))\n",
        "!(test (collapse (match &self (tx-kept $x) $x)) (a))\n",
        "(= (tx-three) 1)\n",
        "(= (tx-three) 2)\n",
        "(= (tx-three) 3)\n",
        "!(test (collapse (transaction (tx-three))) (1 2 3))\n",
        "!(test (collapse (transaction (superpose ((add-atom &self (tx-each 1)) (add-atom &self (tx-each 2)))))) (true true))\n",
        "!(test (collapse (match &self (tx-each $x) $x)) (1 2))\n",
        "!(test (collapse (atomically (tx-three))) (1 2 3))\n",
        "(= (tx-body) (noeval (superpose ((+ 1 1) (+ 2 2)))))\n",
        "!(test (collapse (let $b (tx-body) (atomically $b))) (2 4))\n",
        "!(test (let $answers (collapse (let $b (tx-body) (atomically $b))) (size-atom $answers)) 2)\n",
        "!(test (let $answers (collapse (let $b (tx-body) (transaction $b))) (size-atom $answers)) 1)\n",
        "!(test (let ($v $s) (elapsed (+ 1 2)) $v) 3)\n",
        "!(test (let ($v $s) (elapsed (+ 1 2)) (< $s 60)) true)\n",
        "(= (spin $n) (if (== $n 0) done (spin (- $n 1))))\n",
        "!(test (timeout 5 (spin 10)) done)\n",
        "!(test (with_mutex thin-lock-a (+ 1 2)) 3)\n",
        "!(test (with_mutex thin-lock-b (+ 2 2)) 4)\n",
        "!(test (once (hyperpose ((spin 3000000) (spin 3)))) done)\n",
        "!(test (msort (collapse (hyperpose ((+ 1 1) (+ 2 2))))) (2 4))\n",
        "!(test (call (msort (3 1 2))) (1 2 3))\n",
        "!(test (progn (translatePredicate (msort (3 1 2) $s)) $s) (1 2 3))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "thin_forms");
}
