/* Purpose: check thread linda through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/02-thread_linda.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: SWI-Prolog 10.1.14 may abort in PL_cleanup; see ERRORS.md.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_thread))\n",
        "(= (inc $x) (+ $x 1))\n",
        "!(add-atom &jobs (job 7))\n",
        "!(test (peek-atom &jobs (job $n)) (job 7))\n",
        "!(test (peek-atom &jobs (job $n)) (job 7))\n",
        "!(test (await-atom &jobs (job $n)) (job 7))\n",
        "!(test (take-atom &jobs (job $n)) (job 7))\n",
        "!(test (collapse (take-atom &jobs (job $n) 0.05)) ())\n",
        "!(test (collapse (get-atoms &jobs)) ())\n",
        "!(add-atom &work (job 1))\n",
        "!(add-atom &work (job 2))\n",
        "!(test (let $x (take-atom &work (job $a) 1) (let $y (take-atom &work (job $b) 1) (+ $a $b))) 3)\n",
        "!(test (collapse (get-atoms &work)) ())\n",
        "!(test (let $w (spawn (add-atom &inbox (msg hello))) (let $seen (take-atom &inbox (msg $what) 10) (let $_3 (await $w) $seen))) (msg hello))\n",
        "!(test (collapse (get-atoms &inbox)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "thread_linda");
}
