/* Purpose: check thread lib through the embedded source interface.
 * Source: examples/ch17-concurrency-and-the-loop/01-thread_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_thread))\n",
        "(= (inc $x) (+ $x 1))\n",
        "(= (big? $x) (> $x 2))\n",
        "(= (slow $x) (let $_1 (sleep 1) $x))\n",
        "!(test (par-map inc (1 2 3 4)) (2 3 4 5))\n",
        "!(test (par-map inc ()) ())\n",
        "!(test (par-filter big? (1 2 3 4 5)) (3 4 5))\n",
        "!(test (par-forall big? (3 4 5)) true)\n",
        "!(test (par-forall big? (1 4 5)) false)\n",
        "!(test (par-any big? (1 2 9)) true)\n",
        "!(test (par-any big? (1 2)) false)\n",
        "!(test (par-race ((slow 1) (inc 41))) 42)\n",
        "!(test (par-race ((superpose ()) (inc 41))) 42)\n",
        "!(test (let $f (spawn (inc 41)) (await $f)) 42)\n",
        "!(test (let $a (spawn (slow 1)) (let $b (spawn (slow 2)) (+ (await $a) (await $b)))) 3)\n",
        "!(test (let $f (spawn (inc 1)) (let $_1 (await $f) (await $f))) 2)\n",
        "!(test (collapse (await (spawn (superpose (1 2 3))))) (1 2 3))\n",
        "!(test (collapse (await (spawn (superpose ())))) ())\n",
        "!(test (is-space (spawn (inc 1))) true)\n",
        "!(test (let $f (spawn (inc 41)) (let $_1 (await $f) (collapse (get-atoms $f)))) (42))\n",
        "!(test (collapse (await (after 0.05 (inc 41)))) (42))\n",
        "!(test (let $t (after 30 (inc 41)) (let $s (settled? $t) (let $_2 (cancel $t) $s))) false)\n",
        "!(test (let $t (after 0.05 (inc 41)) (let $_1 (cancel $t) (let $__ (sleep 0.25) (collapse (get-atoms $t))))) ())\n",
        "!(test (let $c (channel) (let $_1 (send $c hello) (recv $c))) hello)\n",
        "!(test (let $c (channel) (let $_1 (send $c one) (channel-size $c))) 1)\n",
        "!(test (let $_0 (pool demo-pool 2) (let $h (submit demo-pool (inc 9)) (await $h))) 10)\n",
        "!(test (let $w (spawn (add-atom &self (ready now))) (let $seen (await-atom &self (ready $what) 10) (let $_3 (await $w) $seen))) (ready now))\n",
        "!(test (collapse (with-lock demo-lock (superpose (1 2 3)))) (1 2 3))\n",
        "!(test (collapse (with_mutex demo-lock (superpose (1 2 3)))) (1))\n",
        "!(test (collapse (timeout 10 (superpose (1 2 3)))) (1 2 3))\n",
        "!(test (timeout 10 (inc 41)) 42)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "thread_lib");
}
