/* Purpose: check throwing and tracing through the embedded source interface.
 * Source: examples/ch10-errors-and-refusals/02-throwing_and_tracing.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (throw (my-ball 1)) (Error (throw (my-ball 1)) (my-ball 1)))\n",
        "!(test (throw \"text\") (Error (throw \"text\") \"text\"))\n",
        "!(test (if-error (throw oops) caught fine) caught)\n",
        "!(test (if-error 42 caught fine) fine)\n",
        "!(test (return-on-error (throw oops) carried-on) (Error (throw oops) oops))\n",
        "!(test (return-on-error 42 carried-on) carried-on)\n",
        "!(test (throw (Error (inner 1) because)) (Error (inner 1) because))\n",
        "!(test (throw (throw first)) (Error (throw first) first))\n",
        "(= (half $n) (if (== (% $n 2) 0) (/ $n 2) (throw (odd $n))))\n",
        "!(test (half 10) 5)\n",
        "!(test (half 7) (Error (throw (odd 7)) (odd 7)))\n",
        "!(test (if-error (half 7) refused (half 7)) refused)\n",
        "!(test (trace! \"the answer\" 42) 42)\n",
        "!(test (+ 1 (trace! \"adding one to\" 41)) 42)\n",
        "!(test (trace! (half 10) (half 10)) 5)\n",
        "!(test (trace! (checking (odd 7)) ok) ok)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "throwing_and_tracing");
}
