/* Purpose: check time and pragmas through the embedded source interface.
 * Source: examples/ch14-seeing-your-program/01-time_and_pragmas.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (spin $n) (if (> $n 0) (spin (- $n 1)) done))\n",
        "!(test (timeout 30 (spin 100)) done)\n",
        "!(test (timeout 30 (+ 1 2)) 3)\n",
        "!(test (collapse (timeout 30 (superpose (1 2 3)))) (1 2 3))\n",
        "!(test (let $timed (elapsed (spin 100)) (car-atom $timed)) done)\n",
        "!(test (sleep 0.01) true)\n",
        "!(test (metta (+ 1 2) %Undefined% &self) 3)\n",
        "!(test (evalc (+ 1 2) &self) 3)\n",
        "!(test (pragma! max-time 30) ())\n",
        "!(test (pragma! max-inferences 100000000) ())\n",
        "!(test (pragma! max-time none) ())\n",
        "!(test (pragma! max-inferences none) ())\n",
        "!(test (pragma! max-stack-depth 0) ())\n",
        "!(test (pragma! max-stack-depth -1) (Error (pragma! max-stack-depth -1) UnsignedIntegerIsExpected))\n",
        "!(test (pragma! max-stack-depth none) ())\n",
        "!(pragma! max-stack-depth 20)\n",
        "(= (bounded-factorial 0) 1)\n",
        "(= (bounded-factorial $n) (* $n (bounded-factorial (- $n 1))))\n",
        "!(bounded-factorial 5)\n",
        "!(pragma! max-stack-depth none)\n",
        "!(test (inferences 100000 (spin 100)) done)\n",
        "!(test (collapse (inferences 100000 (superpose (1 2 3)))) (1 2 3))\n",
        "!(test (with-pragma! ((max-inferences 100000)) (+ 20 22)) 42)\n",
        "!(test (with-pragma! ((max-time 30) (max-inferences 100000)) (spin 100)) done)\n",
        "!(test (spin 2000) done)\n",
        "!(pragma! verify-specializations true)\n",
        "(= (verified-inc $x) (+ $x 1))\n",
        "(= (verified-twice $f $x) ($f ($f $x)))\n",
        "!(test (verified-twice verified-inc 20) 22)\n",
        "!(pragma! verify-specializations false)\n",
        "!(test (let 4 (- $x 1) $x) 5)\n",
        "!(test (let 10 (+ $x 3) $x) 7)\n",
        "!(test (let 6 (* $x 2) $x) 3)\n",
        "!(test (let 3 (/ $x 2) $x) 6)\n",
        "!(test (collapse (let 7 (* $x 2) $x)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "time_and_pragmas");
}
