/* Purpose: check translatorrule direction through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-01-translator-rules/02-translatorrule_direction.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: celsius (-> Atom %Undefined%))\n",
        "(= (celsius (degrees $c)) (noeval (kelvin (+ $c 273))))\n",
        "!(add-translator-rule! celsius ((direction forward)))\n",
        "!(test (celsius (degrees 27)) (kelvin 300))\n",
        "(: unpack (-> Atom %Undefined%))\n",
        "(= (unpack (wrap (box $x))) (noeval (twin $x $x)))\n",
        "!(add-translator-rule! unpack ((direction bidirectional)))\n",
        "!(test (unpack (wrap (box 1))) (twin 1 1))\n",
        "!(test (twin (a b c) (a b c)) (unpack (wrap (box (a b c)))))\n",
        "!(test (twin 1 1) (twin 1 1))\n",
        "!(test (unpack (wrap (box (a b c)))) (unpack (wrap (box (a b c)))))\n",
        "!(test (eval (twin 1 1)) (twin 1 1))\n",
        "!(test (reduce (twin 1 1)) (twin 1 1))\n",
        "!(remove-translator-rule! unpack)\n",
        "!(test (twin (a b c) (a b c)) (twin (a b c) (a b c)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "translatorrule_direction");
}
