/* Purpose: check translatepredicate through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-03-prolog-underneath/01-translatepredicate.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (progn (translatePredicate (is $x 2)) (translatePredicate (+ $x 40 $z)) $z) 42)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "translatepredicate");
}
