/* Purpose: check translatorrule cost through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-01-translator-rules/04-translatorrule_cost.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: pow2 (-> Atom %Undefined%))\n",
        "(= (pow2 $x) (noeval (mul $x $x)))\n",
        "!(add-translator-rule! pow2 ((direction bidirectional) (cost 10)))\n",
        "!(test (pow2 3) (mul 3 3))\n",
        "!(test (mul (a b c d e f g h i j) (a b c d e f g h i j)) (pow2 (a b c d e f g h i j)))\n",
        "(unit mass kg)\n",
        "(unit length m)\n",
        "(: unit-of (-> Atom %Undefined%))\n",
        "!(add-translator-rule! unit-of ((left ((unit-of $q) (unit $q $u))) (right (in $u))))\n",
        "!(test (unit-of mass) (in kg))\n",
        "!(test (unit-of length) (in m))\n",
        "!(test (collapse (unit-of time)) ())\n",
        "!(test (match &self (= (unit-of $q) $body) (car-atom $body)) match)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "translatorrule_cost");
}
