/* Purpose: check translatorrule guard through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-01-translator-rules/03-translatorrule_guard.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(add-atom &metta (dispatch-policy add-pairs NoMatchEnum NoMatchFail))\n",
        "(: add-pairs (-> Atom Atom %Undefined%))\n",
        "(= (add-pairs (pair $a $b) (pair $c $d)) (noeval (pair (+ $a $c) (+ $b $d))))\n",
        "!(add-translator-rule! add-pairs)\n",
        "!(test (add-pairs (pair 1 2) (pair 10 20)) (pair 11 22))\n",
        "!(test (collapse (add-pairs 1 2)) ())\n",
        "(= (holds-a-miss) (add-pairs 1 2))\n",
        "!(test (collapse (holds-a-miss)) ())\n",
        "(: hold-pairs (-> Atom Atom %Undefined%))\n",
        "(= (hold-pairs (pair $a $b) (pair $c $d)) (noeval (pair (+ $a $c) (+ $b $d))))\n",
        "(= (hold-pairs $a $b) (noeval (noeval (hold-pairs $a $b))))\n",
        "!(add-translator-rule! hold-pairs)\n",
        "!(test (hold-pairs (pair 1 2) (pair 10 20)) (pair 11 22))\n",
        "!(test (hold-pairs 1 2) (hold-pairs 1 2))\n",
        "!(test (collapse (union (superpose (1 2)) (superpose (2 3)))) (1 2 2 3))\n",
        "!(test (union foo bar) (union foo bar))\n",
        "(: pick (-> Atom %Undefined%))\n",
        "(= (pick a) (empty))\n",
        "(= (pick $x) (noeval (picked $x)))\n",
        "!(add-translator-rule! pick)\n",
        "!(test (pick a) (picked a))\n",
        "!(test (pick b) (picked b))\n",
        "(: only-a (-> Atom %Undefined%))\n",
        "(= (only-a a) (empty))\n",
        "!(add-translator-rule! only-a)\n",
        "!(test (collapse (only-a a)) ())\n",
        "(= (both-ways $x) bw-one)\n",
        "(= (both-ways $x) bw-two)\n",
        "!(test (collapse (both-ways q)) (bw-one bw-two))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "translatorrule_guard");
}
