/* Purpose: check translatorrule refusal through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-01-translator-rules/07-translatorrule_refusal.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: strength (-> Atom Atom %Undefined%))\n",
        "(= (strength (dose $n) (unit mg)) (if (> $n 1000) (refuse \"a dose above 1000 is not a milligram strength\") (noeval (mg $n))))\n",
        "(= (strength (dose $n) (unit mg)) (noeval (grams (/ $n 1000))))\n",
        "!(add-translator-rule! strength)\n",
        "!(test (strength (dose 250) (unit mg)) (mg 250))\n",
        "!(test (strength (dose 5000) (unit mg)) (grams 5))\n",
        "!(test (match &metta (translator-rule-refusal strength $why) $why) \"a dose above 1000 is not a milligram strength\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "translatorrule_refusal");
}
