/* Purpose: check translatorrule for through the embedded source interface.
 * Source: examples/ch20-extending-the-engine/20-01-translator-rules/05-translatorrule_for.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: for (-> Atom Atom Atom %Undefined%))\n",
        "(= (for $var $collection $body) (noeval (let $var (superpose $collection) $body)))\n",
        "!(add-translator-rule! for)\n",
        "(= (myfun $L) (for $x $L (if (== (% $x 2) 0) (even $x) (odd $x))))\n",
        "!(test (collapse (myfun (3 4))) ((odd 3) (even 4)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "translatorrule_for");
}
