/* Purpose: check types through the embedded source interface.
 * Source: examples/ch09-types/01-types.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: a A)\n",
        "(: b B)\n",
        "(: A Type)\n",
        "(: x Letter)\n",
        "(: x Buchstabe)\n",
        "!(test (get-type $a) $z)\n",
        "!(test (get-type a) A)\n",
        "!(test (get-type b) B)\n",
        "!(test (get-type c) %Undefined%)\n",
        "!(test (get-type A) Type)\n",
        "!(test (get-type B) %Undefined%)\n",
        "!(test (get-type (a b)) (A B))\n",
        "!(test (get-type 42) Number)\n",
        "!(test (get-type \"42\") String)\n",
        "!(test (collapse (get-type x)) (Letter Buchstabe))\n",
        "(: mid (-> $a $a))\n",
        "(= (mid $x) (let (a b) $x $x))\n",
        "!(test (mid ($a b)) (a b))\n",
        "(: testx (-> $a $b $a))\n",
        "!(test (get-type (testx 1 \"f\")) Number)\n",
        "(: at A)\n",
        "(: at T)\n",
        "(: t T)\n",
        "(: testf (-> $a $a))\n",
        "(= (testf at) t)\n",
        "!(test (testf at) t)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "types");
}
