/* Purpose: check types nondet through the embedded source interface.
 * Source: examples/ch09-types/13-types_nondet.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: f (-> Type1 Type1))\n",
        "(: f (-> Type2 Type2))\n",
        "(= (f $a) (if (== $a T1in) T1out (if (== $a T2in) T2out Tdefault)))\n",
        "(: T1in Type1)\n",
        "(: T1out Type1)\n",
        "(: T2in Type2)\n",
        "(: T2out Type2)\n",
        "(: T3in Type1)\n",
        "(: Tdefault Type2)\n",
        "!(test (f T1in) T1out)\n",
        "!(test (f T2in) T2out)\n",
        "!(test (f T3in) ())\n",
        "(: T3in Type2)\n",
        "!(test (f T3in) Tdefault)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "types_nondet");
}
