/* Purpose: check types dependent through the embedded source interface.
 * Source: examples/ch09-types/12-types_dependent.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (get-type $x) (catch (let $remainder (% $x 2) (if (=alpha $remainder 0) EvenNumber))))\n",
        "(: f (-> EvenNumber EvenNumber EvenNumber))\n",
        "(= (f $x $y) (+ $x $y))\n",
        "!(test (f 2 4) 6)\n",
        "(= (get-type (cons $head $tail)) (let $head-type (get-type $head) (if (=alpha $head-type EvenNumber) (if (=alpha $tail ()) EvenNumberList (get-type $tail)))))\n",
        "(: g (-> EvenNumberList Bool))\n",
        "(= (g $L) true)\n",
        "!(test (g (2 4 6)) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "types_dependent");
}
