/* Purpose: check type casts that hold through the embedded source interface.
 * Source: examples/ch09-types/20-type_casts_that_hold.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: five Number)\n",
        "(: greeting String)\n",
        "(: twice (-> Number Number))\n",
        "(= (twice $x) (* 2 $x))\n",
        "!(test (type-cast-holds five Number &self) true)\n",
        "!(test (type-cast-holds five Bool &self) false)\n",
        "!(test (type-cast-holds greeting String &self) true)\n",
        "!(test (type-cast-holds 1 Number &self) true)\n",
        "!(test (type-cast-holds \"text\" String &self) true)\n",
        "!(test (type-cast-holds 1 String &self) false)\n",
        "!(test (type-cast-holds twice (-> Number Number) &self) true)\n",
        "!(test (type-cast-holds twice (-> String String) &self) false)\n",
        "!(test (type-cast-holds five %Undefined% &self) false)\n",
        "!(test (type-cast-holds undeclared-name Number &self) false)\n",
        "!(test (type-cast-holds undeclared-name String &self) false)\n",
        "!(test (type-cast-holds undeclared-name %Undefined% &self) true)\n",
        "!(add-atom &other (: five String))\n",
        "!(test (type-cast-holds five String &other) true)\n",
        "!(test (type-cast-holds five String &self) false)\n",
        "!(test (type-cast 1 Number &self) 1)\n",
        "!(test (type-cast five Bool &self) (Error five BadType))\n",
        "!(test (if (type-cast-holds five Bool &self) yes no) no)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "type_casts_that_hold");
}
