/* Purpose: check typing rules through the embedded source interface.
 * Source: examples/ch09-types/16-typing_rules.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: typing-rule-demo (-> DemoPayload Atom))\n",
        "(= (typing-rule-demo $value) (seen $value))\n",
        "!(test (typing-rule-demo unknown-demo) (seen unknown-demo))\n",
        "!(add-typing-rule! deny-unknown-demo ordinary %Undefined% DemoPayload (refuse unknown-demo-is-not-a-payload))\n",
        "!(test (typing-rule-demo unknown-demo) (Error (typing-rule-demo unknown-demo) (BadArgType 1 DemoPayload %Undefined% (TypingRuleRefusal deny-unknown-demo unknown-demo-is-not-a-payload))))\n",
        "!(remove-typing-rule! deny-unknown-demo)\n",
        "!(test (typing-rule-demo unknown-demo) (seen unknown-demo))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "typing_rules");
}
