/* Purpose: check unify through the embedded source interface.
 * Source: examples/ch04-spaces-and-matching/04-02-patterns-and-bindings/07-unify.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(test (unify 1 1 same different) same)\n",
        "!(test (unify 1 2 same different) different)\n",
        "!(test (unify 1 1.0 same different) same)\n",
        "!(test (unify \"x\" \"x\" same different) same)\n",
        "!(test (unify \"x\" \"y\" same different) different)\n",
        "!(test (unify (f $x b) (f a $y) (pair $x $y) nope) (pair a b))\n",
        "!(test (unify $x (f $x) cyclic sound) cyclic)\n",
        "(= (then-probe) (chain (add-atom &self (then-ran)) $_0 3))\n",
        "(= (else-probe) (chain (add-atom &self (else-ran)) $_0 4))\n",
        "!(test (unify A A (then-probe) (else-probe)) 3)\n",
        "!(test (collapse (match &self (else-ran) hit)) ())\n",
        "!(test (unify A B (then-probe) (else-probe)) 4)\n",
        "!(test (collapse (match &self (then-ran) hit)) (hit))\n",
        "(friend Bob Alice)\n",
        "(friend Sam Alice)\n",
        "!(test (collapse (unify &self (friend $who Alice) $who no-friends)) (Bob Sam))\n",
        "!(test (unify &self (friend Pol $who) $who no-friends) no-friends)\n",
        "!(test (unify $s &self bound queried) bound)\n",
        "!(test (collapse (unify a b then Empty)) ())\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "unify");
}
