/* Purpose: check unwind cleanup through the embedded source interface.
 * Source: examples/ch05-equations-and-evaluation/05-01-an-equation-is-a-rewrite/10-unwind_cleanup.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (unwind-note $home $outcome) (add-atom $home (unwound $outcome)))\n",
        "!(test (on-unwind 7 (unwind-note &self)) 7)\n",
        "!(test (collapse (match &self (unwound $outcome) $outcome)) ())\n",
        "!(test (collapse (on-unwind (superpose ()) (unwind-note &self))) ())\n",
        "!(test (collapse (match &self (unwound $outcome) $outcome)) ((fail)))\n",
        "!(remove-atom &self (unwound (fail)))\n",
        "!(test (once (on-unwind (superpose (1 2)) (unwind-note &self))) 1)\n",
        "!(test (collapse (match &self (unwound $outcome) $outcome)) ((!)))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "unwind_cleanup");
}
