/* Purpose: check uri lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/39-uri_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_uri))\n",
        "!(import! &self (library lib_pairs))\n",
        "!(import! &self (library lib_encoding))\n",
        "!(test (uri-parts \"\") ((\"path\" \"\")))\n",
        "!(test (uri-parts \"?#\") ((\"path\" \"\") (\"query\" \"\") (\"fragment\" \"\")))\n",
        "!(test (uri-parts \"https://User:Pass@[::1]:0012/a%2Fb?q=1#F\") ((\"scheme\" \"https\") (\"authority\" \"User:Pass@[::1]:0012\") (\"path\" \"/a%2Fb\") (\"query\" \"q=1\") (\"fragment\" \"F\")))\n",
        "!(test (uri-parts \"urn:Example:ABC\") ((\"scheme\" \"urn\") (\"path\" \"Example:ABC\")))\n",
        "!(test (uri-build ()) \"\")\n",
        "!(test (uri-build ((\"query\" \"\") (\"fragment\" \"\"))) \"?#\")\n",
        "!(test (uri-build ((\"path\" \"/x\") (\"authority\" \"host:\") (\"scheme\" \"http\"))) \"http://host:/x\")\n",
        "!(test (uri-build (uri-parts \"a:b?x#\")) \"a:b?x#\")\n",
        "!(test (uri-normalize \"HTTP://User:Pass@HOST/a/%2e%2e/b?x=%7e#F\") \"http://User:Pass@host/b?x=~#F\")\n",
        "!(test (uri-normalize \"urn:Example:ABC\") \"urn:Example:ABC\")\n",
        "!(test (uri-normalize \"http://HOST/%ff/%c0%af/%2f?#\") \"http://host/%FF/%C0%AF/%2F?#\")\n",
        "!(test (uri-normalize \"../a/./b\") \"../a/./b\")\n",
        "!(test (uri-normalize \"foo:/a/..//b\") \"foo:/.//b\")\n",
        "!(test (uri-resolve \"g\" \"http://a\") \"http://a/g\")\n",
        "!(test (uri-resolve \"../g\" \"http://a/b/c/d;p?q\") \"http://a/b/g\")\n",
        "!(test (uri-resolve \"?\" \"http://a/b?old#f\") \"http://a/b?\")\n",
        "!(test (uri-resolve \"#\" \"http://a/b?old#f\") \"http://a/b?old#\")\n",
        "!(test (uri-resolve \"\" \"http://a/b?old#f\") \"http://a/b?old\")\n",
        "!(test (uri-resolve \"//other/x\" \"http://a/b\") \"http://other/x\")\n",
        "!(test (uri-resolve \"http:g\" \"http://a/b\") \"http:g\")\n",
        "!(test (uri-resolve \"urn:Example:ABC\" \"http://a/b\") \"urn:Example:ABC\")\n",
        "!(test (uri-resolve \"g?y/../x\" \"http://a/b/c/d;p?q\") \"http://a/b/c/g?y/../x\")\n",
        "!(test (uri-resolve \"%2e%2e/g\" \"http://a/b/\") \"http://a/b/%2e%2e/g\")\n",
        "!(test (uri-contexts) (path segment query-value fragment))\n",
        "!(test (uri-encode path \"a b/c?d\") \"a%20b/c%3Fd\")\n",
        "!(test (uri-encode segment \"a b/c?d\") \"a%20b%2Fc%3Fd\")\n",
        "!(test (uri-encode query-value \"a+b&c=d\") \"a%2Bb%26c%3Dd\")\n",
        "!(test (uri-encode fragment \"a+b&c=d/x?y\") \"a+b&c=d/x?y\")\n",
        "!(test (uri-encode segment \"π🙂\") \"%CF%80%F0%9F%99%82\")\n",
        "!(test (uri-encode segment (utf8-decode (97 0 98))) \"a%00b\")\n",
        "!(test (uri-decode \"%CF%80%F0%9F%99%82\") \"π🙂\")\n",
        "!(test (uri-decode \"%252F+a\") \"%2F+a\")\n",
        "!(test (utf8-encode (uri-decode \"%00x\")) (0 120))\n",
        "!(test (uri-query-parse uri \"a+b=c+d&&a=2&bare&empty=&\") ((\"a+b\" \"c+d\") (\"a\" \"2\") (\"bare\" \"\") (\"empty\" \"\")))\n",
        "!(test (uri-query-parse form \"a+b=c+d&&a=2&bare&empty=&\") ((\"a b\" \"c d\") (\"a\" \"2\") (\"bare\" \"\") (\"empty\" \"\")))\n",
        "!(test (uri-query-parse uri \"a=1;b=2&=x\") ((\"a\" \"1;b=2\") (\"\" \"x\")))\n",
        "!(test (uri-query-parse form \"\") ())\n",
        "!(test (uri-query-build uri ((\"a b\" \"c+d\") (\"a b\" \"\") (\"\" \"π🙂\"))) \"a%20b=c%2Bd&a%20b=&=%CF%80%F0%9F%99%82\")\n",
        "!(test (uri-query-build form ((\"a b\" \"c+d\") (\"a b\" \"\") (\"\" \"π🙂\"))) \"a+b=c%2Bd&a+b=&=%CF%80%F0%9F%99%82\")\n",
        "!(test (uri-query-build form ()) \"\")\n",
        "!(test (collapse (pairs-lookup (uri-query-parse uri \"a=1&a=2&b=3\") \"a\")) (\"1\" \"2\"))\n",
        "!(test (uri-query-build form (uri-query-parse form \"%2B=%00&x=a/b?c\")) \"%2B=%00&x=a/b?c\")\n",
        "!(test (if-error (catch (uri-parts \"a b\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-parts (utf8-decode (97 0 98)))) refused fine) refused)\n",
        "!(test (if-error (catch (uri-parts \"x%ZZ\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-build ((\"path\" \"a\") (\"authority\" \"host\")))) refused fine) refused)\n",
        "!(test (if-error (catch (uri-build ((\"path\" \"a\") (\"path\" \"b\")))) refused fine) refused)\n",
        "!(test (if-error (catch (uri-build ((\"missing\" \"x\")))) refused fine) refused)\n",
        "!(test (if-error (catch (uri-resolve \"x\" \"relative\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-encode missing \"x\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-decode \"%\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-decode \"%FF\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-decode \"%C0%AF\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-query-parse form \"x=%ED%A0%80\")) refused fine) refused)\n",
        "!(test (if-error (catch (uri-query-build missing ())) refused fine) refused)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "uri_lib");
}
