/* Purpose: check uuid lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/33-uuid_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_crypto))\n",
        "!(import! &self (library lib_uuid))\n",
        "!(import! &self (library lib_encoding))\n",
        "!(import! &self (library lib_string))\n",
        "!(test (size-atom (crypto-random-bytes 16)) 16)\n",
        "!(test (uuid-version (uuid-random!)) 4)\n",
        "!(test (uuid-variant (uuid-random!)) rfc)\n",
        "!(test (uuid-is (uuid-random!)) true)\n",
        "!(test (!= (uuid-random!) (uuid-random!)) true)\n",
        "!(test (uuid-version (uuid-time!)) 1)\n",
        "!(test (uuid-variant (uuid-time!)) rfc)\n",
        "!(test (> (uuid-timestamp (uuid-time!)) 0) true)\n",
        "!(test (uuid-namespaces) (dns url oid x500))\n",
        "!(test (uuid-name 3 dns \"example.com\") \"9073926b-929f-31c2-abc9-fad77ae3e8eb\")\n",
        "!(test (uuid-name 5 dns \"example.com\") \"cfbff0d1-9375-5685-968c-48ce8b15ae17\")\n",
        "!(test (uuid-name 5 \"6ba7b810-9dad-11d1-80b4-00c04fd430c8\" \"example.com\") (uuid-name 5 dns \"example.com\"))\n",
        "!(test (uuid-name 3 url \"http://example.com\") \"d632b50c-7913-3137-ae9a-2d93f56e70d5\")\n",
        "!(test (uuid-name 5 oid \"1.3.6.1.4.1\") \"106dd502-8b3e-50db-80ed-1134f5c18eae\")\n",
        "!(test (uuid-name 5 x500 \"cn=Test\") \"1a09ab7e-5f76-53b6-b866-3b565a53dc51\")\n",
        "!(test (uuid-name 5 dns \"\") \"4ebd0208-8328-5d69-8c44-ec50939c0967\")\n",
        "!(test (uuid-name 5 dns \"é\") \"ebfe0af8-3997-5ade-b634-ba92cf69f557\")\n",
        "!(test (uuid-name 3 dns \"漢\") \"1f9d873c-79c5-37f3-a181-6bab16c1f1c9\")\n",
        "!(test (uuid-name 5 dns (string-from-codes (97 0 98))) \"0a63f66b-e02f-5d2d-9fd4-aad819cf5352\")\n",
        "!(test (uuid-nil) \"00000000-0000-0000-0000-000000000000\")\n",
        "!(test (uuid-is (uuid-nil)) true)\n",
        "!(test (uuid-version (uuid-nil)) 0)\n",
        "!(test (uuid-variant (uuid-nil)) ncs)\n",
        "!(test (uuid-variant \"00000000-0000-0000-c000-000000000000\") microsoft)\n",
        "!(test (uuid-variant \"ffffffff-ffff-ffff-ffff-ffffffffffff\") future)\n",
        "!(test (uuid-timestamp \"13814000-1dd2-11b2-8000-000000000000\") 0.0)\n",
        "!(test (collapse (uuid-timestamp (uuid-random!))) ())\n",
        "!(test (collapse (uuid-timestamp (uuid-nil))) ())\n",
        "!(test (uuid-is \"CFBFF0D1-9375-5685-968C-48CE8B15AE17\") true)\n",
        "!(test (hex-encode (uuid-bytes \"cfbff0d1-9375-5685-968c-48ce8b15ae17\")) \"cfbff0d193755685968c48ce8b15ae17\")\n",
        "!(test (uuid-of-bytes (uuid-bytes \"CFBFF0D1-9375-5685-968C-48CE8B15AE17\")) \"cfbff0d1-9375-5685-968c-48ce8b15ae17\")\n",
        "!(test (uuid-bytes (uuid-nil)) (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0))\n",
        "!(test (uuid-of-bytes (hex-decode \"ffffffffffffffffffffffffffffffff\")) \"ffffffff-ffff-ffff-ffff-ffffffffffff\")\n",
        "!(test (uuid-is \"------------------------------------\") false)\n",
        "!(test (uuid-is (string-replace (uuid-nil) \"-\" (string-from-codes (0)))) false)\n",
        "!(test (uuid-is \"cfbff0d193755685968c48ce8b15ae17\") false)\n",
        "!(test (uuid-is \"zfbff0d1-9375-5685-968c-48ce8b15ae17\") false)\n",
        "!(test (uuid-is 3) false)\n",
        "!(test (if-error (catch (uuid-version \"broken\")) refused fine) refused)\n",
        "!(test (if-error (catch (uuid-timestamp \"broken\")) refused fine) refused)\n",
        "!(test (if-error (catch (uuid-of-bytes (1 2))) refused fine) refused)\n",
        "!(test (if-error (catch (uuid-of-bytes (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 256))) refused fine) refused)\n",
        "!(test (if-error (catch (uuid-name 2 dns \"name\")) refused fine) refused)\n",
        "!(test (if-error (catch (uuid-name 5 missing \"name\")) refused fine) refused)\n",
        "!(test (if-error (catch (uuid-name 5 \"broken\" \"name\")) refused fine) refused)\n",
        "!(test (let $recipe (match &self (= (uuid-version $id) $body) (quote (|-> ($id) $body))) (let $inspect (eval $recipe) ($inspect (uuid-nil)))) 0)\n",
        "!(test (let $recipe (match &self (= (uuid-name $v $ns $name) $body) (quote (|-> ($v $ns $name) $body))) (let $derive (eval $recipe) ($derive 5 dns \"example.com\"))) \"cfbff0d1-9375-5685-968c-48ce8b15ae17\")\n",
        "!(test (collapse (uuid-version (superpose (\"00000000-0000-0000-0000-000000000000\" \"ffffffff-ffff-ffff-ffff-ffffffffffff\")))) (0 15))\n",
        "!(test (uuid-name 3 dns (string-from-codes (97 0 98))) \"002a0ada-f547-375a-bab5-896a11d1927e\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "uuid_lib");
}
