/* Purpose: check variadic arrow faces through the embedded source interface.
 * Source: examples/ch09-types/23-variadic_arrow_faces.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(: vsum (-> (:seg Number) Number))\n",
        "(= (vsum (:seg $ns)) (foldl-atom $ns 0 +))\n",
        "!(test ((vsum) (vsum 1) (vsum 1 2) (vsum 1 2 3)) (0 1 3 6))\n",
        "(: vflag Bool)\n",
        "!(test ((collapse (vsum vflag 2 3)) (collapse (vsum 1 vflag 3)) (collapse (vsum 1 2 vflag))) (((Error (vsum vflag 2 3) (BadArgType 1 Number Bool))) ((Error (vsum 1 vflag 3) (BadArgType 2 Number Bool))) ((Error (vsum 1 2 vflag) (BadArgType 3 Number Bool)))))\n",
        "(: vheld (-> (:seg Atom) Atom))\n",
        "(= (vheld (:seg $es)) $es)\n",
        "!(test (vheld) ())\n",
        "!(test (vheld (+ 1 1) (+ 2 2)) (noeval ((+ 1 1) (+ 2 2))))\n",
        "!(test (get-type vheld) (-> (:seg Atom) Atom))\n",
        "(: mixed (-> Number (:seg Atom) Atom))\n",
        "(= (mixed $n (:seg $xs)) (kept $n $xs))\n",
        "!(test (mixed (+ 1 1) (+ 2 2) (+ 3 3)) (noeval (kept 2 ((+ 2 2) (+ 3 3)))))\n",
        "!(test (mixed 2) (kept 2 ()))\n",
        "(: fixed2 (-> Number Number Number))\n",
        "(= (fixed2 $a $b) (+ $a $b))\n",
        "!(test (fixed2 1 2) 3)\n",
        "!(test (repr (catch (fixed2 1 2 3))) \"(Error (domain_error (function_input_arities fixed2 (2)) 3) none)\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "variadic_arrow_faces");
}
