/* Purpose: check vector lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/13-vector_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_vector))\n",
        "!(test (dot (1.0 2.0) (3.0 4.0)) 11.0)\n",
        "!(test (dot () ()) 0.0)\n",
        "!(test (dot (1.0 0.0) (0.0 1.0)) 0.0)\n",
        "!(test (norm (3.0 4.0)) 5.0)\n",
        "!(test (norm (1.0 0.0)) 1.0)\n",
        "!(test (norm ()) 0.0)\n",
        "!(test (cosine (1.0 0.0) (2.0 0.0)) 1.0)\n",
        "!(test (cosine (1.0 0.0) (0.0 1.0)) 0.0)\n",
        "!(test (cosine (1.0 0.0) (-2.0 0.0)) -1.0)\n",
        "!(test (cosine-of-normalized (1.0 0.0) (1.0 0.0)) 1.0)\n",
        "!(test (cosine-of-normalized (1.0 0.0) (0.0 1.0)) 0.0)\n",
        "!(test (== (cosine-of-normalized (1.0 0.0) (0.6 0.8)) (cosine (1.0 0.0) (0.6 0.8))) true)\n",
        "!(test (cosine-of-normalized (3.0 4.0) (3.0 4.0)) 25.0)\n",
        "!(test (cosine (3.0 4.0) (3.0 4.0)) 1.0)\n",
        "!(test (let $v (with-seed 17 (random-normal-vector 3)) (size-atom $v)) 3)\n",
        "!(test (let $v (with-seed 17 (random-normal-vector 5)) (< (abs-math (- (norm $v) 1.0)) 1e-6)) true)\n",
        "!(test (let $v (with-seed 17 (random-normal-vector 4)) (< (abs-math (- (cosine-of-normalized $v $v) 1.0)) 1e-6)) true)\n",
        "!(test (vector-add (1 2) (3 4)) (4 6))\n",
        "!(test (vector-subtract (3 4) (1 2)) (2 2))\n",
        "!(test (vector-multiply (1 2) (3 4)) (3 8))\n",
        "!(test (vector-divide (6 8) (2 4)) (3 2))\n",
        "!(test (vector-scale (1 2) 3) (3 6))\n",
        "!(test (vector-normalize (3 4)) (0.6 0.8))\n",
        "!(test (vector-distance (1 2) (4 6)) 5.0)\n",
        "!(test (vector-fill 3 7) (7 7 7))\n",
        "!(test (vector-fill 0 7) ())\n",
        "!(test (vector-normalize ()) ())\n",
        "!(test (dot (1.8014398509481984e16 1.0 -1.8014398509481984e16) (1 1 1)) 1.0)\n",
        "!(test (norm (1e-300)) 1e-300)\n",
        "!(test (cosine (1e308 1e308) (1e308 1e308)) 1.0)\n",
        "!(test (isnan-math (cosine (0 0) (1 2))) true)\n",
        "!(test (isinf-math (norm (1e400))) True)\n",
        "!(test (random-normal-vector 0 (3 4)) (0.6 0.8))\n",
        "!(test (random-normal-vector -2) ())\n",
        "!(test (collapse (vector-fill (superpose (0 2)) 7)) (() (7 7)))\n",
        "!(test (let $recipe (match &self (= (vector-fill $count $value) $body) (quote (|-> ($count $value) $body))) (let $constructor (eval $recipe) ($constructor 3 7))) (7 7 7))\n",
        "!(test (let $q (index-atom (vector-divide (1) (3)) 0) (vector-scale (vector-fill 3 $q) 3)) (1 1 1))\n",
        "!(test (vector-fill 2 -0.0) (-0.0 -0.0))\n",
        "!(test (if-error (catch (vector-fill -1 7)) refused accepted) refused)\n",
        "!(test (if-error (catch (vector-fill 0 bad)) refused accepted) refused)\n",
        "!(test (if-error (catch (random-normal-vector 1.5)) refused accepted) refused)\n",
        "!(test (if-error (catch (random-normal-vector 0 (bad))) refused accepted) refused)\n",
        "!(test (== (with-seed 17 (if-error (catch (random-normal-vector 3 (quote ((random-float 0 1))))) (random-float 0 1) 0)) (with-seed 17 (random-float 0 1))) true)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "vector_lib");
}
