/* Purpose: check walrus through the embedded source interface.
 * Source: examples/ch07-control-flow/07-03-let-and-sequencing/09-walrus.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "(= (double-used $n) (let* (($big (* $n 10))) (+ $big $big)))\n",
        "!(test (double-used 3) 60)\n",
        "(= (guarded-half $n) (let* (($half (floor-div $n 2))) (if (< $half 10) $half nope)))\n",
        "!(test (guarded-half 8) 4)\n",
        "!(test (guarded-half 40) nope)\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "walrus");
}
