/* Purpose: check weighted subset posterior through the embedded source interface.
 * Source: examples/ch22-a-reasoner-you-can-serve/22-02-weighted-answers/11-weighted_subset_posterior.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_statistics))\n",
        "!(test (weighted-subset-posterior-independent ((candidate pump-a 2 (ratio 1 2)) (candidate pump-b 3 (ratio 1 4))) 2) (subset-posterior (ratio 3 8) ((candidate-posterior pump-a (ratio 1 1)) (candidate-posterior pump-b (ratio 0 1)))))\n",
        "!(test (weighted-subset-posterior-independent ((candidate left 1 (ratio 1 2)) (candidate right 1 (ratio 1 2))) 1) (subset-posterior (ratio 1 2) ((candidate-posterior left (ratio 1 2)) (candidate-posterior right (ratio 1 2)))))\n",
        "!(test (weighted-subset-posterior-independent ((candidate metadata-flag 0 (ratio 1 3)) (candidate failing-part 2 (ratio 1 2))) 2) (subset-posterior (ratio 1 2) ((candidate-posterior metadata-flag (ratio 1 3)) (candidate-posterior failing-part (ratio 1 1)))))\n",
        "!(test (weighted-subset-mass-independent ((candidate absent 5 (ratio 0 1))) 5) (ratio 0 1))\n",
        "!(test (weighted-subset-mass-independent ((candidate scaled-loss 125 (ratio 2 5))) 125) (ratio 2 5))\n",
        "!(test (weighted-subset-posterior-independent () 0) (subset-posterior (ratio 1 1) ()))\n",
        "!(test (weighted-subset-posterior-independent ((candidate 1 0 (ratio 1 2)) (candidate 1.0 0 (ratio 1 3))) 0) (subset-posterior (ratio 1 1) ((candidate-posterior 1 (ratio 1 2)) (candidate-posterior 1.0 (ratio 1 3)))))\n",
        "!(test (weighted-subset-posterior-independent ((candidate (+ 1 2) 0 (ratio 1 2)) (candidate (Error a b) 0 (ratio 1 3))) 0) (quote (subset-posterior (ratio 1 1) ((candidate-posterior (+ 1 2) (ratio 1 2)) (candidate-posterior (Error a b) (ratio 1 3))))))\n",
        "!(test (collapse (let $rows (superpose (((candidate a 1 (ratio 1 2))) ((candidate a 1 (ratio 1 2))) ((candidate b 1 (ratio 1 3))))) (weighted-subset-mass-independent $rows 1))) ((ratio 1 2) (ratio 1 2) (ratio 1 3)))\n",
        "!(test (let $source (match &self (= (weighted-subset-mass-independent $rows $target) $body) (quote (|-> ($rows $target) $body))) (let $mass (eval $source) ($mass (quote ((candidate a 1 (ratio 1 3)))) 1))) (ratio 1 3))\n",
        "(subset-event from-space 2 (ratio 1 3))\n",
        "(subset-event other 3 (ratio 1 4))\n",
        "!(test (let $rows (collapse (match &self (subset-event $id $loss $prior) (quote (candidate $id $loss $prior)))) (weighted-subset-mass-independent $rows 2)) (ratio 1 4))\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "weighted_subset_posterior");
}
