/* Purpose: check yaml lib through the embedded source interface.
 * Source: examples/ch08-data/08-03-the-shipped-libraries/28-yaml_lib.metta.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=6022c3f48b6dc64752c6e49cfe9d985c7ac7a4e9].
 * Open Obligations: None.
 */
#include "common.h"
int main(void)
{
    metta *m = open_engine();
    const char *const program[] = {
        "!(import! &self (library lib_yaml))\n",
        "!(bind! &conf (yaml-decode \"name: petta\\nversion: 1.5\\ntags:\\n  - prolog\\n  - metta\\nlimits:\\n  depth: 3\\n  strict: true\\n  note:\\n  nothing: ~\\n\"))\n",
        "!(test (collapse (get-keys &conf)) (limits name tags version))\n",
        "!(test (get-value &conf name) \"petta\")\n",
        "!(test (get-value &conf version) 1.5)\n",
        "!(test (get-value &conf tags) (\"prolog\" \"metta\"))\n",
        "!(test (json-at &conf (tags 0)) \"prolog\")\n",
        "!(test (json-at &conf (limits depth)) 3)\n",
        "!(test (json-at &conf (limits strict)) true)\n",
        "!(test (json-at &conf (limits note)) \"\")\n",
        "!(test (json-at &conf (limits nothing)) Null)\n",
        "!(test (collapse (get-value &conf missing)) ())\n",
        "!(test (yaml-decode \"- 1\\n- 2\\n\") (1 2))\n",
        "!(test (yaml-decode \"just text\\n\") \"just text\")\n",
        "!(test (yaml-decode \"42\\n\") 42)\n",
        "!(test (yaml-decode \"true\\n\") true)\n",
        "!(test (yaml-decode \"null\\n\") Null)\n",
        "!(test (yaml-decode \"\") Null)\n",
        "!(test (json-at (yaml-decode \"k: no\\n\") (k)) \"no\")\n",
        "!(test (yaml-encode (yaml-decode \"a: 1\\nb:\\n  - x\\n\")) \"a: 1\\nb:\\n- x\\n\")\n",
        "!(test (yaml-encode (1 2 Null true)) \"- 1\\n- 2\\n- null\\n- true\\n\")\n",
        "!(test (yaml-encode \"text\") \"text\\n\")\n",
        "!(test (yaml-encode 7) \"7\\n\")\n",
        "!(test (yaml-encode Null) \"null\\n\")\n",
        "!(test (yaml-encode (dict-space ((a 1) (b \"two\")))) \"a: 1\\nb: two\\n\")\n",
        "!(test (json-at (yaml-decode (yaml-encode (dict-space ((k 1))))) (k)) 1)\n",
        "(= (write-and-read $dir) (let $path (path-join $dir \"conf.yaml\") (let $written (yaml-write! $path (dict-space ((host \"localhost\") (port 8080)))) (let $text (read-file! $path) ($text (json-at (yaml-read! $path) (port)))))))\n",
        "!(test (with-temp-dir \"yaml-lib\" write-and-read) (\"host: localhost\\nport: 8080\\n\" 8080))\n",
        "!(test (if-error (catch (yaml-decode \"a: 1\\n---\\nb: 2\\n\")) refused fine) refused)\n",
        "!(test (if-error (catch (yaml-decode \"k: !foo 1\\n\")) refused fine) refused)\n",
        "!(test (if-error (catch (yaml-decode \"a: [1,\\n\")) refused fine) refused)\n",
        "!(test (if-error (catch (yaml-decode \"dup: 1\\ndup: 2\\n\")) refused fine) refused)\n",
        "!(test (if-error (catch (yaml-decode 7)) refused fine) refused)\n",
        "!(bind! &notamap (new-space))\n",
        "!(add-atom &notamap (a 1 2))\n",
        "!(test (if-error (catch (yaml-encode &notamap)) refused fine) refused)\n",
        "!(test (yaml-encode (one two)) \"- one\\n- two\\n\")\n",
    };
    check_program(m, program, sizeof(program) / sizeof(program[0]));
    return done(m, "yaml_lib");
}
