"""Purpose: derive standalone C language programs from the committed corpus.
Guarantees: --check refuses generated drift [tested: make generated-check; commit=WORKTREE].
Open Obligations: None.
"""
import argparse
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render(example):
    """Keep source fragments below C11's minimum literal length guarantee."""
    fragments = []
    for form in example["forms"]:
        source = ("!" if form["kind"] == "runnable" else "") + form["text"] + "\n"
        fragments.extend(source[i:i + 1000] for i in range(0, len(source), 1000))
    literals = "\n".join("        " + json.dumps(text, ensure_ascii=False) + "," for text in fragments)
    count = ""
    if "count" in example:
        count = f'''    mt_answers *rows = mt_eval(m, mt_parse({json.dumps(example["count"]["goal"])}));
    check("open stream", rows != NULL);
    size_t total = 0;
    while (mt_next(rows)) ++total;
    check("streamed result count", mt_ok() && total == {example["count"]["expected"]});
    mt_answers_free(rows);
'''
    return f'''/* Purpose: check {example["subject"]} through the embedded source interface.
 * Source: {example["origin"]}.
 * Generated by tools/generate.py from corpus.json; edit that source.
 * Guarantees: embedded assertions run [tested: make check; commit=WORKTREE].
 * Open Obligations: {example.get("obligations", "None.")}
 */
#include "common.h"
int main(void)
{{
    metta *m = open_engine();
    const char *const program[] = {{
{literals}
    }};
    check_program(m, program, sizeof(program) / sizeof(program[0]));
{count}\
    return done(m, "{example["name"]}");
}}
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    corpus = json.loads((ROOT / "corpus.json").read_text())
    for asset in corpus.get("fixtures", []):
        path = ROOT / asset["path"]
        content = base64.b64decode(asset["base64"])
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                raise SystemExit(f"fixture drift: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    expected = set()
    for example in corpus["examples"]:
        path = ROOT / "language-feature-examples" / (example["name"] + ".c")
        expected.add(path)
        content = render(example)
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"generated drift: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    actual = set((ROOT / "language-feature-examples").glob("*.c"))
    if actual != expected:
        raise SystemExit(f"unexpected generated files: {sorted(actual - expected)}")
    print(f"{len(expected)} generated C programs verified" if args.check else f"wrote {len(expected)} C programs")


if __name__ == "__main__":
    main()
