"""Purpose: derive the example index and coverage tables from their source rosters.
Guarantees: --check rejects stale documents and missing counterparts
[tested: make generated-check; commit=WORKTREE].
Open Obligations: None.
"""
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = ("basics", "data", "gallery", "integration",
              "language-feature-examples", "live", "operations", "reasoning")
HEADER = "<!-- Purpose: index executable evidence. Generated by tools/index.py.\nOpen Obligations: see COVERAGE.md and ERRORS.md. -->\n\n"


def link(path):
    if not (ROOT / path).is_file():
        raise SystemExit(f"missing counterpart: {path}")
    return f"[{path}]({path})"


def render():
    corpus = json.loads((ROOT / "corpus.json").read_text())
    coverage = json.loads((ROOT / "coverage.json").read_text())
    sources = {d: sorted((ROOT / d).glob("*.c")) for d in CATEGORIES}
    generated = {e["name"]: e for e in corpus["examples"]}
    count = sum(map(len, sources.values()))
    index = [HEADER, "# Example index\n\n",
             f"{count} standalone C programs: {len(generated)} language twins and "
             f"{count - len(generated)} handwritten C examples.\n\n",
             "| Directory | Programs |\n| --- | ---: |\n"]
    for directory, files in sources.items():
        index.append(f"| [{directory}](#{directory}) | {len(files)} |\n")
    for directory, files in sources.items():
        index.append(f"\n## {directory}\n\n| Program | Asserted subject |\n| --- | --- |\n")
        for path in files:
            purpose = re.search(r"/\* Purpose: (.*?)\n \*", path.read_text(), re.S)
            if not purpose:
                raise SystemExit(f"missing purpose: {path}")
            subject = " ".join(purpose.group(1).replace("\n", " ").split())
            index.append(f"| {link(str(path.relative_to(ROOT)))} | {subject} |\n")
    topical = coverage["topical"]
    declared = {e["python"] for e in topical}
    expected = {p for p in coverage["roster"] if not p.startswith("language-feature-examples/")}
    if declared != expected:
        raise SystemExit("topical coverage does not match the Python roster")
    report = [HEADER, "# Coverage and boundaries\n\n",
              f"Source snapshot: Python `{coverage['python_revision']}`, "
              f"engine `{corpus['provenance']['engine']}`.\n\n",
              f"The roster records {len(coverage['roster'])} Python files plus `_common.py`. "
              f"Its {len(topical)} topical examples are mapped below. "
              f"The language corpus has {len(generated)} executed twins and "
              f"{len(corpus['omissions'])} explicit adaptations or omissions. "
              "Four additional Python files under the nested `examples/` folder are two "
              "host-import fixtures and the two algebra demonstrations mapped separately below. "
              "Directory names follow the Python corpus; C language files are flat.\n\n",
              "`native` identifies the corresponding C behavior. `adapted` identifies "
              "a different host implementation and states its limits. `gap` identifies "
              "behavior without a complete C or shared-engine service. These are "
              "coverage boundaries, not skipped binaries in `make check`.\n\n",
              "## Topical correspondence\n\n| Python example | Status | C evidence | Boundary |\n| --- | --- | --- | --- |\n"]
    for entry in topical:
        report.append(f"| `{entry['python']}` | {entry['status']} | "
                      + ", ".join(link(p) for p in entry["c"])
                      + f" | {entry['detail']} |\n")
    report.append("\n## Nested host demonstrations\n\n| Python example | Status | C evidence | Boundary |\n| --- | --- | --- | --- |\n")
    for entry in coverage["nested"]:
        if entry["python"] not in coverage["roster"]:
            raise SystemExit("nested example is absent from the source roster")
        report.append(f"| `{entry['python']}` | {entry['status']} | "
                      + ", ".join(link(p) for p in entry["c"])
                      + f" | {entry['detail']} |\n")
    report.append("\n## Language adaptations\n\n| Source | Reason | C evidence |\n| --- | --- | --- |\n")
    for entry in corpus["omissions"]:
        report.append(f"| `{entry['origin']}` | {entry['reason']} | "
                      + ", ".join(link(p) for p in entry["counterparts"]) + " |\n")
    report.append("\n## Additional boundaries\n\n")
    report.extend(f"- {gap}\n" for gap in coverage["additional_gaps"])
    report.append("\nLanguage source, runnable/definition boundaries, fixture bytes, "
                  "source hashes and adaptations live in `corpus.json`. "
                  "`tools/generate.py --check` checks every generated file and fixture. "
                  "The large matespace workload streams and counts all 1,572,862 answers "
                  "in C instead of materializing a single engine list.\n")
    return {"INDEX.md": "".join(index), "COVERAGE.md": "".join(report)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for name, content in render().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f"index drift: {name}")
        else:
            path.write_text(content)
    print("example index and coverage verified" if args.check else "wrote index and coverage")


if __name__ == "__main__":
    main()
