"""Purpose: derive INDEX.md, COVERAGE.md and README.md's coverage table from
the programs on disk, the corpus of originals, residue.json and coverage.json,
so no count in them is kept by hand.

Assumes: --engine names the engine tree whose examples/ are the originals and
whose extensions/python/examples/ are the Python seat's examples.
Guarantees: --check exits nonzero naming the first document that differs from
what this derives [tested: make check; commit=WORKTREE].
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TWINS = ROOT / "language-feature-examples"
HANDWRITTEN = ("basics", "data", "gallery", "integration", "live", "operations", "reasoning")
HEADER = ("<!-- Purpose: {purpose} Generated by tools/index.py; edit the programs, "
          "residue.json or coverage.json, then run `make index`. -->\n\n")
BEGIN, END = "<!-- coverage:begin -->", "<!-- coverage:end -->"


def purpose(path: Path) -> str:
    """A program's Purpose field, as one line."""
    hit = re.search(r"/\* Purpose: (.*?)(?:\n \* [A-Z][a-z-]+:|\*/)", path.read_text(), re.S)
    if not hit:
        raise SystemExit(f"{path.relative_to(ROOT)} has no Purpose field")
    text = " ".join(line.strip(" *") for line in hit.group(1).splitlines())
    return " ".join(text.split())


def chapters(engine: Path) -> dict[str, dict]:
    """Per chapter: its originals, the ones Python twins, the ones C twins."""
    examples = engine / "examples"
    python = engine / "extensions" / "python" / "examples" / "language-feature-examples"
    table: dict[str, dict] = defaultdict(lambda: {"originals": 0, "python": 0, "c": 0})
    for original in sorted(examples.glob("ch*/**/*.metta")):
        if "_fixtures" in original.parts:
            continue
        rel = original.relative_to(examples).with_suffix("")
        row = table[rel.parts[0]]
        row["originals"] += 1
        row["python"] += (python / rel).with_suffix(".py").exists()
        row["c"] += (TWINS / rel).with_suffix(".c").exists()
    return dict(sorted(table.items()))


def residue() -> list[dict]:
    return json.loads((TWINS / "residue.json").read_text())["entries"]


def coverage_table(engine: Path) -> str:
    table = chapters(engine)
    entries = residue()
    untwinned = defaultdict(int)
    declined = defaultdict(int)
    for entry in entries:
        chapter = entry["example"].split("/")[1]
        (untwinned if entry["kind"] == "untwinned" else declined)[chapter] += 1
    lines = ["| chapter | originals | Python twins | C twins | untwinned | declined claims |",
             "|---|---:|---:|---:|---:|---:|"]
    total = defaultdict(int)
    for chapter, row in table.items():
        values = (row["originals"], row["python"], row["c"], untwinned[chapter], declined[chapter])
        for key, value in zip(("o", "p", "c", "u", "d"), values):
            total[key] += value
        lines.append(f"| `{chapter}` | " + " | ".join(str(v) for v in values) + " |")
    lines.append("| **all** | " + " | ".join(str(total[k]) for k in ("o", "p", "c", "u", "d")) + " |")
    return "\n".join(lines) + "\n"


def index_document() -> str:
    twins = sorted(p for p in TWINS.rglob("*.c") if "_fixtures" not in p.parts)
    hand = {d: sorted((ROOT / d).glob("*.c")) for d in HANDWRITTEN}
    count = len(twins) + sum(len(v) for v in hand.values())
    out = [HEADER.format(purpose="every program in this repository and what it proves."),
           "# Example index\n\n",
           f"{count} C programs: {len(twins)} language twins, each at its MeTTa "
           f"original's path, and {count - len(twins)} C embedding examples.\n\n",
           "## Embedding examples\n\n| Program | What it shows |\n|---|---|\n"]
    for directory, files in hand.items():
        for path in files:
            rel = path.relative_to(ROOT)
            out.append(f"| [{rel}]({rel}) | {purpose(path)} |\n")
    out.append("\n## Language twins\n")
    section = None
    for path in twins:
        rel = path.relative_to(TWINS)
        group = "/".join(rel.parts[:-1])
        if group != section:
            section = group
            out.append(f"\n### {group}\n\n| Twin | What it proves |\n|---|---|\n")
        link = path.relative_to(ROOT)
        out.append(f"| [{rel.name}]({link}) | {purpose(path)} |\n")
    return "".join(out)


def coverage_document(engine: Path) -> str:
    coverage = json.loads((ROOT / "coverage.json").read_text())
    out = [HEADER.format(purpose="what the C corpus covers, and where it cannot follow."),
           "# Coverage\n\n",
           "Every MeTTa original the Python seat twins has a C twin at the same "
           "path or an `untwinned` entry in "
           "[residue.json](language-feature-examples/residue.json). The counts "
           "are derived from the files.\n\n",
           coverage_table(engine), "\n## Residue\n\n"]
    entries = residue()
    table = chapters(engine)
    missing = sum(row["python"] for row in table.values()) - sum(
        min(row["c"], row["python"]) for row in table.values()) - sum(
        e["kind"] == "untwinned" for e in entries)
    if missing > 0:
        out.append(f"{missing} originals the Python seat twins have neither a C twin "
                   "nor a residue entry yet.\n\n")
    if not entries and missing <= 0:
        out.append("None: every original in scope has a twin, and every twin proves "
                   "every claim its original makes.\n")
    for entry in entries:
        form = "" if entry.get("form") is None else f", form {entry['form']}"
        out.append(f"- `{entry['example']}`{form} ({entry['kind']}): missing "
                   f"{entry['missing']}; waits on {entry['waits_on']}.\n")
    out.append("\n## The Python seat's own examples\n\n"
               "Beside its twins the Python seat ships topical examples. Each is "
               "mapped to the C programs that cover the same ground.\n\n"
               "| Python example | Status | C evidence | Boundary |\n|---|---|---|---|\n")
    for entry in coverage["topical"] + coverage.get("nested", []):
        links = ", ".join(f"[{p}]({p})" for p in entry["c"])
        for p in entry["c"]:
            if not (ROOT / p).exists():
                raise SystemExit(f"coverage.json names {p}, which does not exist")
        out.append(f"| `{entry['python']}` | {entry['status']} | {links} | {entry['detail']} |\n")
    return "".join(out)


def readme(engine: Path) -> str:
    text = (ROOT / "README.md").read_text()
    if BEGIN not in text or END not in text:
        return text
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + BEGIN + "\n" + coverage_table(engine) + END + tail


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--engine", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    engine = args.engine.resolve()
    documents = {"INDEX.md": index_document(), "COVERAGE.md": coverage_document(engine),
                 "README.md": readme(engine)}
    for name, content in documents.items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                print(f"{name} differs from what tools/index.py derives; run make index")
                return 1
        else:
            path.write_text(content)
    print("index, coverage and README verified" if args.check else "wrote index, coverage and README")
    return 0


if __name__ == "__main__":
    sys.exit(main())
